[package]
name = "settings_json"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/settings_json.rs"
doctest = false

[features]
default = ["editing"]
editing = ["dep:tree-sitter", "dep:tree-sitter-json", "dep:serde_json"]

[dependencies]
anyhow.workspace = true
tree-sitter = { workspace = true, optional = true }
tree-sitter-json = { workspace = true, optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
serde_json_lenient.workspace = true
serde_path_to_error.workspace = true

[dev-dependencies]
serde_json.workspace = true
unindent.workspace = true
pretty_assertions.workspace = true
