use gpui2::{FontWeight, Hsla};
use indexmap::IndexMap;

pub struct StaticColors {
    pub mac_os_traffic_light_red: Hsla,
    pub mac_os_traffic_light_yellow: Hsla,
    pub mac_os_traffic_light_green: Hsla,
}

#[derive(Debug, Clone, Copy)]
pub struct PlayerColor {
    pub cursor: Hsla,
    pub background: Hsla,
    pub selection: Hsla,
}

type Players = [PlayerColor; 8];

#[derive(Debug, Clone, Copy)]
pub enum SyntaxColorName {
    Comment,
    CommentDoc,
    Primary,
    Predictive,
    Hint,
    Emphasis,
    EmphasisStrong,
    Title,
    LinkUri,
    LinkText,
    TextLiteral,
    Punctuation,
    PunctuationBracket,
    PunctuationDelimiter,
    PunctuationSpecial,
    PunctuationListMarker,
    String,
    StringSpecial,
    StringSpecialSymbol,
    StringEscape,
    StringRegex,
    Constructor,
    Variant,
    Type,
    TypeBuiltin,
    Variable,
    VariableSpecial,
    Label,
    Tag,
    Attribute,
    Property,
    Constant,
    Keyword,
    Enum,
    Operator,
    Number,
    Boolean,
    ConstantBuiltin,
    Function,
    FunctionBuiltin,
    FunctionDefinition,
    FunctionSpecialDefinition,
    FunctionMethod,
    FunctionMethodBuiltin,
    Preproc,
    Embedded,
}

#[derive(Debug, Clone, Copy)]
pub struct SyntaxStyle {
    pub color: Hsla,
    pub weight: FontWeight,
    pub underline: bool,
    pub italic: bool,
    // Nate: In the future I'd like to enable using background highlights for syntax highlighting
    // pub highlight: Hsla,
}

type SyntaxStyles = IndexMap<SyntaxColorName, SyntaxStyle>;

pub struct ThemeStyle {
    pub transparent: Hsla,
    pub border: Hsla,
    pub border_variant: Hsla,
    pub border_focused: Hsla,
    pub border_transparent: Hsla,
    pub elevated_surface: Hsla,
    pub surface: Hsla,
    pub background: Hsla,
    pub element: Hsla,
    pub element_hover: Hsla,
    pub element_active: Hsla,
    pub element_selected: Hsla,
    pub element_disabled: Hsla,
    pub element_placeholder: Hsla,
    pub ghost_element: Hsla,
    pub ghost_element_hover: Hsla,
    pub ghost_element_active: Hsla,
    pub ghost_element_selected: Hsla,
    pub ghost_element_disabled: Hsla,
    pub text: Hsla,
    pub text_muted: Hsla,
    pub text_placeholder: Hsla,
    pub text_disabled: Hsla,
    pub text_accent: Hsla,
    pub icon: Hsla,
    pub icon_muted: Hsla,
    pub icon_disabled: Hsla,
    pub icon_placeholder: Hsla,
    pub icon_accent: Hsla,
    pub syntax: SyntaxStyles,
    pub status_bar: Hsla,
    pub title_bar: Hsla,
    pub toolbar: Hsla,
    pub tab_bar: Hsla,
    pub editor: Hsla,
    pub editor_subheader: Hsla,
    pub editor_active_line: Hsla,
    pub terminal: Hsla,
    pub created: Hsla,
    pub modified: Hsla,
    pub deleted: Hsla,
    pub conflict: Hsla,
    pub hidden: Hsla,
    pub ignored: Hsla,
    pub renamed: Hsla,
    pub error: Hsla,
    pub warning: Hsla,
    pub info: Hsla,
    pub success: Hsla,
    pub git_created: Hsla,
    pub git_modified: Hsla,
    pub git_deleted: Hsla,
    pub git_conflict: Hsla,
    pub git_ignored: Hsla,
    pub git_renamed: Hsla,
    pub player: [PlayerColor; 8],
}
