[package]
name = "gpui_windows"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_windows.rs"
doctest = false

[features]
default = ["gpui/default"]
test-support = ["gpui/test-support"]
screen-capture = ["gpui/screen-capture", "scap"]

[dependencies]
gpui.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
accesskit.workspace = true
accesskit_windows.workspace = true
anyhow.workspace = true
collections.workspace = true
dunce.workspace = true
etagere.workspace = true
futures.workspace = true
gpui_util.workspace = true
image.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
raw-window-handle.workspace = true
smallvec.workspace = true
uuid = { workspace = true, features = ["v5"] }
windows = { workspace = true, features = [
    "Data_Xml_Dom",
    "UI_Notifications",
    "UI_ViewManagement",
    "Wdk_System_SystemServices",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_DirectManipulation",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Hlsl",
    "Win32_Media",
    "Win32_Security_Credentials",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_DataExchange",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_Pointer",
] }
windows-core.workspace = true
windows-numerics = "0.3"
windows-registry.workspace = true

[target.'cfg(target_os = "windows")'.dependencies.scap]
workspace = true
optional = true

[target.'cfg(target_os = "windows")'.build-dependencies]
windows-registry.workspace = true

[package.metadata.cargo-shear]
ignored = ["scap"]
