[package]
name = "libzed_core"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
name = "zed_core"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
rope.workspace = true
language.workspace = true
tree-sitter.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
