# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /app
ARG TZ=Etc/UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

COPY script/linux script/
RUN ./script/linux
COPY script/install-mold script/install-cmake script/
RUN ./script/install-mold "2.34.0"
RUN ./script/install-cmake "3.30.4"

COPY . .

# This line is superfluous but makes troubleshooting faster when things break
RUN . "$HOME/.cargo/env" && cargo fetch
RUN . "$HOME/.cargo/env" && cargo build
RUN . "$HOME/.cargo/env" && cargo run -- --help
