# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /app
ARG TZ=Etc/UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

COPY script/linux script/
RUN ./script/linux
COPY script/install-mold script/
RUN ./script/install-mold "2.34.0"

COPY . .
ARG GITHUB_SHA
RUN . "$HOME/.cargo/env" \
    && rustup toolchain install --no-self-update \
    && cargo fetch
RUN . "$HOME/.cargo/env" \
    && cargo run -- --help

# TODO:
# RUN . "$HOME/.cargo/env" ./script/bundle-linux
