# syntax=docker/dockerfile:1.10.0
ARG ARCH=aarch64
FROM quay.io/pypa/manylinux_2_28_${ARCH}:latest

# ENV ARCH=$ARCH
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

WORKDIR /app
COPY . .

ARG GITHUB_SHA
ENV GITHUB_SHA=$GITHUB_SHA

RUN true && \
    ./script/install-mold && \
    ./script/linux
