[package]
name = "http_client_tls"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/http_client_tls.rs"
doctest = true

[dependencies]
log.workspace = true
rustls-platform-verifier.workspace = true
webpki-roots.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
rustls = { workspace = true, features = ["ring"] }

[target.'cfg(not(target_os = "ios"))'.dependencies]
rustls = { workspace = true, features = ["aws_lc_rs", "prefer-post-quantum"] }
