is_debug = false
target_os = "linux"
target_cpu = "x64"
rtc_enable_protobuf = false
treat_warnings_as_errors = false
use_custom_libcxx = false
use_llvm_libatomic = false
use_libcxx_modules = false
use_custom_libcxx_for_host = false
rtc_include_tests = false
rtc_build_tools = false
rtc_build_examples = false
rtc_libvpx_build_vp9 = true
enable_libaom = true
is_component_build = false
enable_stripping = true
ffmpeg_branding = "Chrome"
rtc_use_h264 = true
rtc_use_h265 = true
rtc_use_pipewire = true
symbol_level = 0
enable_iterator_debugging = false
use_rtti = true
rtc_use_x11 = true
