interface context-server {
    ///
    record context-server-configuration {
        ///
        installation-instructions: string,
        ///
        settings-schema: string,
        ///
        default-settings: string,
    }
}
