[package]
name = "websocket_client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/websocket_client.rs"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
async-tungstenite.workspace = true
futures.workspace = true
futures-rustls.workspace = true
http_client.workspace = true
http_client_tls.workspace = true
log.workspace = true
parking_lot.workspace = true
proxy_handshake = { workspace = true, features = ["futures-io"] }
rustls.workspace = true
smol.workspace = true
url.workspace = true
