[package]
name = "bench_metrics"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/bench_metrics.rs"
doctest = false

[features]
test-support = []

[dependencies]
anyhow.workspace = true
criterion.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
perf-event.workspace = true
