.TH VIM 1 "11. april 2006"
.SH NAVN
vim \- Vi IMproved, en programmørs teksteditor
.SH SYNOPSIS
.br
.B vim
[tilvalg] [fil ..]
.br
.B vim
[tilvalg] \-
.br
.B vim
[tilvalg] \-t tag
.br
.B vim
[tilvalg] \-q [fejlfil]
.PP
.br
.B ex
.br
.B view
.br
.B gvim
.B gview
.B evim
.B eview
.br
.B rvim
.B rview
.B rgvim
.B rgview
.SH BESKRIVELSE
.B Vim
er en teksteditor som er opad kompatibel med Vi.
Den kan bruges til at redigere alle slags ren tekst.
Den er særlig nyttig til at redigere programmer.
.PP
Der er mange forbedringer over Vi: multiniveau fortryd,
multivinduer og -buffere, syntaksfremhævning, redigering af kommandolinje,
fuldførelse af filnavn, onlinehjælp, visuel markering, osv.
Se ":help vi_diff.txt" for et overblik over forskellene mellem
.B Vim
og Vi.
.PP
Mens
.B Vim
kører, kan der indhentes massere af hjælp fra online-hjælpesystemet, med
":help"-kommandoen.
Se ONLINEHJÆLP-sektionen nedenfor.
.PP
Oftest startes
.B Vim
for at redigere en enkelt fil med kommandoen
.PP
	vim fil
.PP
Mere generelt startes
.B Vim
med:
.PP
	vim [tilvalg] [filliste]
.PP
Hvis fillisten mangler, så startes editoren med en tom buffer.
Ellers kan én af følgende fire måder bruges til at vælge en eller
flere filer som skal redigeres.
.TP 12
fil ..
En liste over filnavne.
Den første bliver den nuværende fil og læses ind i bufferen.
Markøren placeres på den første linje i bufferen.
Du kan gå til de andre filer med ":next"-kommandoen. Skriv "\-\-" foran
fillisten, for at redigere en fil som begynder med en bindestreg.
.TP
\-
Filen som skal redigeres læses fra stdin. Kommandoer læses fra stderr, hvilket
skal være en tty.
.TP
\-t {tag}
Filen som skal redigeres og den indledende markørplacering afhænger af
et "tag", en slags gå til-etiket.
{tag} opslås i tags-filen, den tilknyttede fil bliver den nuværende
fil og den tilknyttede kommando udføres.
Det bruges mest til C-programmer, hvor {tag} kunne være et
funktionsnavn.
Virkningen er at filen som indeholder funktionen bliver den nuværende fil
og markøren placeres i begyndelsen af funktionen.
Se ":help tag\-commands".
.TP
\-q [fejlfil]
Start i quickFix-tilstand.
Filen [fejlfil] læses og den første fejl vises.
Hvis [fejlfil] udelades, så indhentes filnavnet fra 'errorfile'-valgmuligheden
(standard er "AztecC.Err" på Amiga, "errors.err" på andre
systemer).
Der kan hoppes til yderligere fejl med ":cn"-kommandoen.
Se ":help quickfix".
.PP
.B Vim
opfører sig anderledes, afhængig af navnet på kommandoen (eksekverbaren kan
stadig være den samme fil).
.TP 10
vim
Den "normale" måde, alt er standard.
.TP
ex
Start i Ex-tilstand.
Gå til normal tilstand med ":vi"-kommandoen.
Det kan også gøres med "\-e"-argumentet.
.TP
view
Start i skrivebeskyttet tilstand. Du vil være beskyttet mod at skrive filerne.
Det kan også gøres med "\-R"-argumentet.
.TP
gvim gview
GUI-versionen.
Starter et nyt vindue.
Det kan også gøres med "\-g"-argumentet.
.TP
evim eview
GUI-versionen i easy-tilstand.
Starter et nyt vindue.
Det kan også gøres med "\-y"-argumentet.
.TP
rvim rview rgvim rgview
Som dem ovenfor, men med restriktioner. Det vil ikke være muligt at starte
skalkommandoer, eller at suspendere
.B Vim\c
\&.
Det kan også gøres med "\-Z"-argumentet.
.SH TILVALG
Tilvalgene kan gives i vilkårlig rækkefølge, før eller efter filnavnene.
Tilvalg uden et argument kan kombineres efter en enkelt bindestreg.
.TP 12
+[nummer]
Ved den første fil, placeres markøren på linje "nummer".
Hvis "nummer" mangler, så placeres markøren på den sidste linje.
.TP
+/{sti}
Ved den første fil, placeres markøren på linjen med den
første forekomst af {sti}.
Se ":help search\-pattern" for tilgængelige søgemønstre.
.TP
+{kommando}
.TP
\-c {kommando}
{kommando} udføres efter den første fil er blevet læst.
{kommando} fortolkes som en Ex-kommando.
Hvis {kommando} indeholder mellemrum, så skal den omsluttes af
dobbelte citationstegn (det afhænger af den skal der bruges).
Eksempel: vim "+set si" main.c
.br
Bemærk: Du kan bruge op til 10 "+"- eller "\-c"-kommandoer.
.TP
\-S {fil}
{fil} bliver sourced efter den første fil er blevet læst.
Det svarer til \-c "source {fil}".
{fil} må ikke begynde med '\-'.
Hvis {fil} udelades, så bruges "Session.vim" (virker kun når \-S er det sidste
argument).
.TP
\-\-cmd {kommando}
Ligesom at bruge "\-c", men kommandoen udføres lige inden
behandlingen af vimrc-filer.
Du kan bruge op til 10 af disse kommandoer, uafhængigt af "\-c"-kommandoer.
.TP
\-A
Hvis
.B Vim
blev kompileret med understøttelse af ARABIC til redigering af filer som er
orienteret højre mod venstre og arabisk tastaturlayout, så starter tilvalget
.B Vim
i arabisk tilstand, dvs. 'arabic' sættes.
Ellers gives en fejlmeddelelse og
.B Vim
afbrydes.
.TP
\-b
Binær tilstand.
Der sættes nogle få valgmuligheder som gør det muligt at redigere en
binær eller eksekverbar fil.
.TP
\-C
Kompatibel. Sæt 'compatible'-valgmuligheden.
Det får
.B Vim
til at opføre sig mest som Vi, selvom der findes en .vimrc-fil.
.TP
\-d
Start i diff-tilstand.
Der skal være to, tre eller fire filnavneargumenter.
.B Vim
åbner alle filerne og viser forskellene mellem dem.
Virker ligesom vimdiff(1).
.TP
\-d {enhed}
Åbn {enhed} til brug som en terminal.
Kun på Amiga.
Eksempel:
"\-d con:20/30/600/150".
.TP
\-D
Fejlretning. Gå til fejlretningstilstand når den første kommando udføres fra
et script.
.TP
\-e
Start
.B Vim
i Ex-tilstand, ligesom hvis "ex"-eksekverbaren blev kaldt.
.TP
\-E
Start
.B Vim
i forbedret Ex-tilstand, ligesom hvis "exim"-eksekverbaren blev kaldt.
.TP
\-f
Forgrund. I GUI-versionen, vil
.B Vim
ikke fork'e og frigøre fra skallen som den blev startet i.
På Amiga, genstartes
.B Vim
ikke for at åbne et nyt vindue.
Tilvalget bør bruges når
.B Vim
udføres af et program der venter på at redigeringssession
bliver færdig (f.eks. mail).
På Amiga virker ":sh"- og ":!"-kommandoerne ikke.
.TP
\-\-nofork
Forgrund. I GUI-versionen, vil
.B Vim
ikke fork'e og frigøre fra skallen som den blev startet i.
.TP
\-F
Hvis
.B Vim
blev kompileret med understøttelse af FKMAP til redigering af filer som er
orienteret højre mod venstre og persisk tastaturlayout, så starter tilvalget
.B Vim
i persisk tilstand, dvs. 'fkmap' og 'rightleft' sættes.
Ellers gives en fejlmeddelelse og
.B Vim
afbrydes.
.TP
\-g
Hvis
.B Vim
blev kompileret med understøttelse af GUI, så aktiveres GUI'en af
denne valgmulighed. Hvis understøttelse af GUI ikke blev kompileret ind,
så gives en fejlmeddelelse og
.B Vim
afbrydes.
.TP
\-h
Giv lidt hjælp om kommandolinjeargumenterne og tilvalgene.
Herefter afsluttes
.B Vim\c
\&.
.TP
\-H
Hvis
.B Vim
blev kompileret med understøttelse af RIGHTLEFT til redigering af filer som er
orienteret højre mod venstre og hebraisk tastaturlayout, så starter tilvalget
.B Vim
i hebraisk tilstand, dvs. 'hkmap' og 'rightleft' sættes.
Ellers gives en fejlmeddelelse og
.B Vim
afbrydes.
.TP
\-i {viminfo}
Når brug af viminfo-filen er aktiveret, så sætter tilvalget det
filnavn som skal bruges, i stedet for standarden "~/.viminfo".
Det kan også bruges til at springe brugen af .viminfo-filen over,
ved at give navnet "NONE".
.TP
\-L
Samme som \-r.
.TP
\-l
Lisp-tilstand.
Sætter 'lisp'- og 'showmatch'-valgmulighederne til.
.TP
\-m
Ændring af filer er deaktiveret.
Nulstiller 'write'-valgmuligheden.
Du kan stadig ændre bufferen, men det er ikke muligt at skrive en fil.
.TP
\-M
Ændringer tillades ikke. 'modifiable'- og 'write'-valgmulighederne fjernes,
så ændringer ikke er tilladt og filer ikke kan skrives. Bemærk at
valgmulighederne kan sættes for at gøre det muligt at foretage ændringer.
.TP
\-N
No-compatible-tilstand. Nulstil 'compatible'-valgmuligheden.
Det får
.B Vim
til at opføre sig en smule bedre, men mindre Vi-kompatibel, selvom der ikke
findes en .vimrc-fil.
.TP
\-n
Der bruges ingen swap-fil.
Det er umuligt at gendanne efter programmet er holdt op med at virke.
God hvis du vil redigere en fil på et meget langsomt medie (f.eks. floppy).
Kan også gøres med ":set uc=0".
Kan fortrydes med ":set uc=200".
.TP
\-nb
Bliv en editor-server til NetBeans. Se dokumentationen for detaljer.
.TP
\-o[N]
Åbn N vinduer stablet.
Når N udelades, så åbnes ét vindue pr. fil.
.TP
\-O[N]
Åbn N vinduer side om side.
Når N udelades, så åbnes ét vindue pr. fil.
.TP
\-p[N]
Åbn N fanebladssider.
Når N udelades, så åbnes én fanebladsside pr. fil.
.TP
\-R
Skrivebeskyttet tilstand.
\&'readonly'-valgmuligheden sættes.
Du kan stadig redigere bufferen, men vil være forhindret i
fejlagtigt at overskrive en fil.
Hvis du vil overskrive en fil, så tilføj et
udråbstegn til Ex-kommandoen, som i ":w!".
\-R-tilvalget indebærer også \-n-tilvalget (se ovenfor).
\&'readonly'-valgmuligheden kan slås fra med ":set noro".
Se ":help 'readonly'".
.TP
\-r
Oplist swap-filer, med information om at bruge dem til gendannelse.
.TP
\-r {fil}
Gendannelsestilstand.
Swap-filen bruges til at gendanne en redigeringssession som holdt
op med at virke. Swap-filen er en fil med det samme filnavn som tekstfilen,
med ".swp" tilføjet i slutningen.
Se ":help recovery".
.TP
\-s
Stille tilstand. Kun når der startes som "Ex" eller
når "\-e"-tilvalget blev givet inden "\-s"-tilvalget.
.TP
\-s {scriptind}
Script-filen {scriptind} læses.
Tegnene i filen fortolkes som havde du skrevet dem.
Det samme kan gøres med kommandoen ":source! {scriptind}".
Hvis slutningen af filen nås inden editoren afslutter,
så læses yderligere tegn fra tastaturet.
.TP
\-T {terminal}
Fortæller
.B Vim
navnet på terminalen som du bruger.
Kræves kun når den automatisk måde ikke virker.
Skal være en terminal som kendes af
.B Vim
(indbygget) eller defineret i termcap- eller terminfo-filen.
.TP
\-u {vimrc}
Brug kommandoerne i {vimrc}-filen til initialiseringer.
Alle de andre initialiseringer springes over.
Brug den til at redigere en særlig slags filer.
Den kan også bruges til at springe alle initialiseringer over,
ved at give navnet "NONE". Se ":help initialization" i vim for flere detaljer.
.TP
\-U {gvimrc}
Brug kommandoerne i {gvimrc}-filen til GUI-initialiseringer.
Alle de andre GUI-initialiseringer springes over.
Den kan også bruges til at springe alle GUI-initialiseringer over,
ved at give navnet "NONE". Se ":help gui\-init" i vim for flere detaljer.
.TP
\-V[N]
Uddybende. Giv meddelelser om hvilke filer som er sourced og til læsning og
skrivning af en viminfo-fil. Det valgfrie nummer N er værdien af 'verbose'.
Standard er 10.
.TP
\-v
Start
.B Vim
i Vi-tilstand, ligesom eksekverbaren kaldet "vi". Det har kun virkning når
eksekverbaren kaldes "ex".
.TP
\-w {scriptud}
Alle tegnene som du skrev optages i filen {scriptud}, indtil du afslutter
.B Vim\c
\&.
Det er nyttigt hvis du vil oprette en script-fil som skal bruges med
"vim \-s" eller ":source!".
Hvis {scriptud}-filen findes, så tilføjes tegnene til slutningen.
.TP
\-W {scriptud}
Ligesom \-w, men en eksisterende fil overskrives.
.TP
\-x
Brug kryptering når der skrives filer. Spørger efter en krypteringsnøgle.
.TP
\-X
Opret ikke forbindelse til X-serveren. Afkorter opstartstiden i en terminal,
men vinduets titel og udklipsholder bruges ikke.
.TP
\-y
Start
.B Vim
i easy-tilstand, ligesom hvis "evim"- eller "eview"-eksekverbarene blev kaldt.
Får
.B Vim
til at opføre sig som en klik og skriv-editor.
.TP
\-Z
Restriktiv tilstand. Virker ligesom eksekverbaren som begynder med "r".
.TP
\-\-
Betegner slutningen af tilvalgene.
Argumenter efter dette håndteres som et filnavn.
Det kan bruges til at redigere et filnavn som begynder med et '\-'.
.TP
\-\-echo\-wid
Kun GTK GUI: Ekko vinduets id på stdout.
.TP
\-\-help
Giv en hjælpemeddelelse og afslut, ligesom "\-h".
.TP
\-\-literal
Tag filnavnets argumenter bogstaveligt, udvid ikke jokertegn.
Det har ingen virkning i Unix hvor skallen udvidder jokertegn.
.TP
\-\-noplugin
Spring indlæsning af plugins over. Indebæres af \-u NONE.
.TP
\-\-remote
Opret forbindelse til en Vim-server og få den til at redigere filerne
som gives i resten af argumenterne. Hvis der ikke findes nogen server,
så gives der en advarsel og filerne redigeres i den nuværende Vim.
.TP
\-\-remote\-expr {udtryk}
Opret forbindelse til en Vim-server, evaluer
{udtryk} i den og udskriv resultatet på stdout.
.TP
\-\-remote\-send {nøgler}
Opret forbindelse til en Vim-server and send {nøgler} til den.
.TP
\-\-remote\-silent
Som \-\-remote, men uden advarslen når der ikke findes nogen server.
.TP
\-\-remote\-wait
Som \-\-remote, men Vim afslutter ikke før filerne er blevet redigeret.
.TP
\-\-remote\-wait\-silent
Som \-\-remote\-wait, men uden advarslen når der ikke findes nogen server.
.TP
\-\-serverlist
Oplist navnene på alle Vim-servere som der kan findes.
.TP
\-\-servername {navn}
Brug servernavnet {navn}. Bruges til den nuværende Vim,
medmindre det bruges med et \-\-remote-argument,
så er det navnet på serveren som der skal oprettes forbindelse til.
.TP
\-\-socketid {id}
Kun GTK GUI: Brug GtkPlug-mekanismen til at køre gvim i et andet vindue.
.TP
\-\-version
Udskriv versionsinformation og afslut.
.SH ONLINEHJÆLP
Skriv ":help" i
.B Vim
for at begynde.
Skriv ":help emne" for at få hjælp til et bestemt emne.
F.eks.: ":help ZZ" for at få hjælpe til "ZZ"-kommandoen.
Brug <Tab> og CTRL-D for at fuldføre emner (":help cmdline\-completion").
Tags findes til at hoppe fra et sted til et andet (en slags hypertekst-links,
se ":help").
Alle dokumentationsfiler kan vises på denne måde, f.eks.
":help syntax.txt".
.SH FILER
.TP 15
/usr/local/lib/vim/doc/*.txt
.B Vim\c
-dokumentationsfilerne.
Brug ":help doc\-file\-list" for at få den fulde liste.
.TP
/usr/local/lib/vim/doc/tags
Tags-filen som bruges til at finde information i dokumentationsfilerne.
.TP
/usr/local/lib/vim/syntax/syntax.vim
Systembrede syntaksinitialiseringer.
.TP
/usr/local/lib/vim/syntax/*.vim
Syntaksfiler til diverse sprog.
.TP
/usr/local/lib/vim/vimrc
Systembrede
.B Vim\c
-initialiseringer.
.TP
~/.vimrc
Dine personlige
.B Vim\c
-initialiseringer.
.TP
/usr/local/lib/vim/gvimrc
Systembrede gvim-initialiseringer.
.TP
~/.gvimrc
Dine personlige gvim-initialiseringer.
.TP
/usr/local/lib/vim/optwin.vim
Script som bruges til ":options"-kommandoen,
en god måde til at vise og sætte valgmuligheder.
.TP
/usr/local/lib/vim/menu.vim
Systembrede menu-initialiseringer til gvim.
.TP
/usr/local/lib/vim/bugreport.vim
Script til at generere en fejlrapport. Se ":help bugs".
.TP
/usr/local/lib/vim/filetype.vim
Script til at registrere filtypen ud fra navnet. Se ":help 'filetype'".
.TP
/usr/local/lib/vim/scripts.vim
Script til at registrere filtypen ud fra indholdet. Se ":help 'filetype'".
.TP
/usr/local/lib/vim/print/*.ps
Filer som bruges til PostScript-udskrivning.
.PP
Læs VIM-hjemmesiden for seneste info:
.br
<URL:http://www.vim.org/>
.SH SE OGSÅ
vimtutor(1)
.SH FORFATTER
Det meste af
.B Vim
blev lavet af Bram Moolenaar, med en masse hjælp fra andre.
Se ":help credits" i
.B Vim\c
\&.
.br
.B Vim
er baseret på Stevie, arbejdet på af: Tim Thompson,
Tony Andrews og G.R. (Fred) Walter.
Selvom der næsten ikke er noget af den originale kode tilbage.
.SH FEJL
Formodentligt.
Se ":help todo" for en liste over kendte problemer.
.PP
Bemærk at flere ting som af nogle kan anses som værende fejl,
faktisk er pga. en for nær reproduktion af Vi's opførsel.
Og hvis du tænker at andre ting er fejl "fordi Vi gør det anderledes",
så kig nærmere på vi_diff.txt-filen (eller skriv :help vi_diff.txt i Vim).
Se også 'compatible'- og 'cpoptions'-valgmulighederne.
