[build]
# v0 mangling scheme provides more detailed backtraces around closures
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]

[alias]
xtask = "run --package xtask --"
perf-test = ["test", "--profile", "release-fast", "--lib", "--bins", "--tests", "--all-features", "--config", "target.'cfg(true)'.runner='cargo run -p perf --release'", "--config", "target.'cfg(true)'.rustflags=[\"--cfg\", \"perf_enabled\"]"]
# Keep similar flags here to share some ccache
perf-compare = ["run", "--profile", "release-fast", "-p", "perf", "--config", "target.'cfg(true)'.rustflags=[\"--cfg\", \"perf_enabled\"]", "--", "compare"]

[target.'cfg(target_os = "windows")']
rustflags = [
    "--cfg",
    "windows_slim_errors",        # This cfg will reduce the size of `windows::core::Error` from 16 bytes to 4 bytes
    "-C",
    "target-feature=+crt-static", # This fixes the linking issue when compiling livekit on Windows
]

# We need lld to link libwebrtc.a successfully on aarch64-linux
# +fp16 is needed for gemm-f16 (used by candle-core/denoise) on aarch64
# -larm_sme_stub provides stub implementations of ARM SME runtime functions missing in GCC 11
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-feature=+fp16", "-C", "link-arg=-L/home/hyx/.local/lib", "-C", "link-arg=-larm_sme_stub"]

[env]
MACOSX_DEPLOYMENT_TARGET = "10.15.7"
RUST_FONTCONFIG_DLOPEN = "1"
LIBRARY_PATH = "/home/hyx/.local/lib:/usr/lib/aarch64-linux-gnu"
