[package]
name = "fuzzy_nucleo"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/fuzzy_nucleo.rs"
doctest = false

[dependencies]
fuzzy.workspace = true
nucleo.workspace = true
gpui.workspace = true
gpui_util.workspace = true
num_cpus = "1.13"
path.workspace = true

[dev-dependencies]
criterion.workspace = true
gpui = { workspace = true, features = ["test-support"] }

[[bench]]
name = "match_benchmark"
harness = false
