[package]
name = "gpui_platform_core"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_platform_core.rs"
doctest = false

[dependencies]
anyhow.workspace = true
collections.workspace = true
gpui_shared_string.workspace = true
gpui_types.workspace = true
schemars.workspace = true
serde.workspace = true
uuid.workspace = true
