#!/usr/bin/env sh

if [ "$ZED_WSL_DEBUG_INFO" = true ]; then
	set -x
fi

ZED_PATH="$(dirname "$(dirname "$(realpath "$0")")")"

IN_WSL=false
if [ -n "$WSL_DISTRO_NAME" ]; then
	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
	IN_WSL=true
fi

if [ $IN_WSL = true ]; then
    PROJECT_DIR=$(wslpath -w "$(pwd)")
    "$ZED_PATH/Zed.exe" "$PROJECT_DIR" "$@" &
    exit 0
else
    echo "Only WSL is supported for now" >&2
    exit 1
fi
