[package]
name = "gpui_web"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"
autoexamples = false

[lints]
workspace = true

[features]
default = ["multithreaded"]
multithreaded = ["dep:wasm_thread", "scheduler/wasm-threads"]

[lib]
path = "src/gpui_web.rs"
doctest = false

[dependencies]
unicode-properties = "=0.1.3"
unicode-script.workspace = true
unicode-segmentation.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
gpui.workspace = true
scheduler.workspace = true
parking_lot = { workspace = true, features = ["nightly"] }
gpui_wgpu.workspace = true
http_client.workspace = true
anyhow.workspace = true
async-channel.workspace = true
futures.workspace = true
log.workspace = true
uuid.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-time.workspace = true
console_error_panic_hook.workspace = true
js-sys.workspace = true
raw-window-handle.workspace = true
smallvec.workspace = true
wasm_thread = { workspace = true, optional = true }
web-sys = { workspace = true, features = [
    "console",
    "Blob",
    "Clipboard",
    "ClipboardEvent",
    "ClipboardItem",
    "CompositionEvent",
    "CssStyleDeclaration",
    "DataTransfer",
    "DataTransferItem",
    "DataTransferItemList",
    "Document",
    "DomRect",
    "DragEvent",
    "Element",
    "EventTarget",
    "File",
    "FocusOptions",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlTextAreaElement",
    "IdleDeadline",
    "IdleRequestOptions",
    "ImageData",
    "InputEvent",
    "KeyboardEvent",
    "Location",
    "MediaQueryList",
    "MouseEvent",
    "Navigator",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "PointerEvent",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamReadResult",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverSize",
    "ResizeObserverOptions",
    "Screen",
    "Storage",
    "TextMetrics",
    "VisualViewport",
    "Headers",
    "Request",
    "RequestCredentials",
    "RequestInit",
    "RequestRedirect",
    "Response",
    "WheelEvent",
    "Window",
] }

[dev-dependencies]
anyhow.workspace = true
gpui.workspace = true
smallvec.workspace = true

[package.metadata.cargo-shear]
ignored = ["scheduler"]
