#!/usr/bin/env bash

set -e

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "Linux dependencies..."
  script/linux
else
  echo "installing foreman..."
  which foreman > /dev/null || brew install foreman
fi

# Install sqlx-cli if needed
if [[ "$(sqlx --version)" != "sqlx-cli 0.7.2" ]]; then
    echo "sqlx-cli not found or not the required version, installing version 0.7.2..."
    cargo install sqlx-cli --version 0.7.2
fi

cd crates/collab

# Export contents of .env.toml
eval "$(cargo run --bin dotenv)"

echo "creating databases..."
sqlx database create --database-url "$DATABASE_URL"
sqlx database create --database-url "$LLM_DATABASE_URL"
