#!/usr/bin/env bash

echo "installing foreman..."
which foreman > /dev/null || brew install foreman

echo "creating database..."
script/sqlx database create

echo "migrating database..."
(cd crates/collab && cargo run -- migrate)

echo "seeding database..."
script/seed-db

echo "Linux dependencies..."
script/linux
