#!/usr/bin/env bash

# Use a docker BASE_IMAGE to test building Zed.
# e.g: ./script/bundle-docker ubuntu:20.04
#
# Increasing resources available to podman may speed this up:
# podman machine stop
# podman machine set --memory 16384 --cpus 8 --disk-size 200
# podman machine start

set -euo pipefail

BASE_IMAGE=${BASE_IMAGE:-${1:-}}
if [ -z "$BASE_IMAGE" ]; then
    echo "Usage: $0 BASE_IMAGE" >&2
    exit 1
fi

export DOCKER_BUILDKIT=1
cd "$(dirname "$0")/.."

podman build . \
    -f Dockerfile-distros \
    -t many \
    --build-arg BASE_IMAGE="$BASE_IMAGE"
