#!/bin/bash

channel=$(cat crates/zed/RELEASE_CHANNEL)

tag_suffix=""
case $channel; in
  stable)
    ;;
  preview)
    tag_suffix="-pre"
    ;;
  *)
    echo "do this on a release branch where RELEASE_CHANNEL is either 'preview' or 'stable'" >&2
    exit 1
    ;;
esac

exec script/lib/bump-version.sh zed v $tag_suffix $@
