#!/bin/bash

set -e

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" != "main" ]; then
  echo "You must be on main to run this script"
  exit 1
fi

git pull --ff-only origin main
git tag -f nightly
git push -f origin nightly
