#!/usr/bin/env bash

set -euo pipefail

# Brackets are used around characters so these don't show up in normal search.
pattern='tod[o]!|FIXM[E]'
result=$(git grep --no-color --ignore-case --line-number --extended-regexp -e $pattern -- \
  ':(exclude).github/workflows/ci.yml' \
  ':(exclude)*criteria.md' \
  ':(exclude)*prompt.md' || true)
echo "${result}"
if [[ -n "${result}" ]]; then
  exit 1
fi
