#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <MAX_SIZE_IN_GB>"
    exit 1
fi

if ! [[ -d target ]]; then
    echo "target directory does not exist yet"
    exit 0
fi

max_size_gb=$1

current_size=$(du -s target | cut -f1)
current_size_gb=$(( ${current_size} / 1024 / 1024 ))

echo "target directory size: ${current_size_gb}gb. max size: ${max_size_gb}gb"

if [[ ${current_size_gb} -gt ${max_size_gb} ]]; then
    echo "clearing target directory"
    shopt -s dotglob
    rm -rf target/*
fi
