#!/usr/bin/env bash

set -eu
source script/lib/deploy-helpers.sh

if [[ $# != 1 ]]; then
  echo "Usage: $0 <production|staging>"
  exit 1
fi
environment=$1
tag="$(tag_for_environment $environment)"

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" != "main" ]; then
  echo "You must be on main to run this script"
  exit 1
fi

remote=$("$(dirname "$0")"/lib/get-zed-remote)
git pull --ff-only "$remote" main
git tag -f $tag
git push -f "$remote" $tag
