#!/bin/bash

set -e

export RUST_ANALYZER_URL="https://github.com/rust-analyzer/rust-analyzer/releases/download/2022-01-24/"

function download {
    local filename="rust-analyzer-$1"
    curl -L $RUST_ANALYZER_URL/$filename.gz | gunzip > vendor/bin/$filename
    chmod +x vendor/bin/$filename
}

mkdir -p vendor/bin
download "x86_64-apple-darwin"
download "aarch64-apple-darwin"

cd vendor/bin
lipo -create rust-analyzer-* -output rust-analyzer
rm rust-analyzer-*
