#!/bin/sh

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

arch=$(arch)
fd_version=23.08
flatpak install -y org.freedesktop.Platform/${arch}/${fd_version}
flatpak install -y org.freedesktop.Sdk/${arch}/${fd_version}
flatpak install -y org.freedesktop.Sdk.Extension.rust-stable/${arch}/${fd_version}