#!/usr/bin/env bash

set -euo pipefail

CARGO_ABOUT_VERSION="0.6.1"
OUTPUT_FILE="${1:-$(pwd)/assets/licenses.csv}"
TEMPLATE_FILE="script/licenses/template.csv.hbs"

if ! cargo install --list | grep "cargo-about v$CARGO_ABOUT_VERSION" > /dev/null; then
  echo "Installing cargo-about@$CARGO_ABOUT_VERSION..."
  cargo install "cargo-about@$CARGO_ABOUT_VERSION"
else
  echo "cargo-about@$CARGO_ABOUT_VERSION is already installed."
fi

echo "Generating cargo licenses"

stderr_file=$(mktemp)

cargo about generate \
    --fail \
    -c script/licenses/zed-licenses.toml \
    script/licenses/template.csv.hbs \
    2> >(tee "$stderr_file") \
    | awk 'NR==1{print;next} NF{print | "sort"}' \
    > $OUTPUT_FILE

# Check that there are no warnings.
if echo "$about_stderr" | grep -v "\[WARN\]" > /dev/null; then
    echo "Error: License check failed - warnings found" >&2
    exit 1
fi

echo "generate-licenses-csv completed. See $OUTPUT_FILE"
