#!/bin/bash

set -e

if ! command -v pandoc &> /dev/null
then
    brew install pandoc   # Install pandoc using Homebrew
fi

pandoc ./script/eula/eula.md -f markdown-smart -t html -o ./script/eula/eula.html
textutil -convert rtf ./script/eula/eula.html -output ./script/eula/eula.rtf
rm ./script/eula/eula.html
