#!/bin/bash

# Install the `plantuml` utility if it is not already installed.
if [[ -x plantuml ]]; then
  brew install plantuml
fi

# Generate SVGs from all of the UML files.
plantuml      \
  -nometadata \
  -overwrite  \
  -tsvg       \
  -o ../svg   \
  docs/diagrams/src/*