#!/usr/bin/env bash

# Install `mold` official binaries from GitHub Releases.
#
# Adapted from the official rui314/setup-mold@v1 action to:
# * use environment variables instead of action inputs
# * remove make-default support
# * use curl instead of wget
# * support doas for sudo
# See: https://github.com/rui314/setup-mold/blob/main/action.yml

set -euo pipefail

if [ "$(uname -s)" != "Linux" ]; then
    echo "Error: This script is intended for Linux systems only."
    exit 1
elif [ -z "$MOLD_VERSION" ]; then
    echo "Usage:"
    echo "  MOLD_VERSION=\"2.34.0\" $0"
    exit 1
elif /usr/local/bin/mold --version 2>/dev/null | grep -qF "$MOLD_VERSION"; then
    echo "mold $MOLD_VERSION is already installed."
    exit 0
elif [ -e /usr/local/bin/mold ]; then
    echo "Warning: existing mold found at /usr/local/bin/mold is not $MOLD_VERSION:"
    /usr/local/bin/mold --version
    exit
fi

if [ "$(whoami)" = root ]; then SUDO=; else SUDO="$(command sudo || command doas || true)"; fi

MOLD_REPO="${MOLD_REPO:-https://github.com/rui314/mold}"
MOLD_FILE="${MOLD_FILE:-mold-$MOLD_VERSION-$(uname -m)-linux.tar.gz}"
MOLD_URL="${MOLD_URL:-$MOLD_REPO}/v$MOLD_VERSION/$MOLD_FILE"

echo "Downloading $MOD_FILE from $MOLD_URL"
curl --location --show-error --silent --output --retry 3 --retry-delay 5 "$MOLD_URL" \
    | $SUDO tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -
