#!/usr/bin/env bash

set -euox pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <language> [version]"
  exit 1
fi

LANGUAGE=$1
VERSION=${2:-}

EXT_DIR="extensions/$LANGUAGE"
EXT_TOML="$EXT_DIR/extension.toml"
CARGO_TOML="$EXT_DIR/Cargo.toml"

if [ ! -d "$EXT_DIR" ]; then
  echo "Directory $EXT_DIR does not exist."
  exit 1
fi

if [ -z "$VERSION" ]; then
  grep -m 1 'version =' "$EXT_TOML" | awk -F\" '{print $2}'
  exit 0
fi

sed -i '' -e "s/^version = \".*\"/version = \"$VERSION\"/" "$EXT_TOML"
sed -i '' -e "s/^version = \".*\"/version = \"$VERSION\"/" "$CARGO_TOML"
cargo update
