#!/usr/bin/env bash

set -ex

# install the wasm toolchain
which rustup > /dev/null 2>&1 || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# if root or sudo is not installed, define an empty alias
if [ "$(id -u)" -eq 0 ]; then
    maysudo=''
else
    maysudo=$(command -v sudo || command -v doas || true)
fi

function mold_check() {
  mold --version &>/dev/null || {
    echo "No mold found. Please install mold or run scripts/install-mold and try again."
    exit 1
  }
}

# Ubuntu, Debian, etc.
# https://packages.ubuntu.com/
apt=$(command -v apt-get || true)
if [[ -n $apt ]]; then
  deps=(
    gcc
    g++
    libasound2-dev
    libfontconfig-dev
    libwayland-dev
    libxkbcommon-x11-dev
    libssl-dev
    libstdc++-12-dev
    libzstd-dev
    libvulkan1
    libgit2-dev
    make
    cmake
    clang
    mold
    jq
    gettext-base
    elfutils
    libsqlite3-dev
  )
  $maysudo "$apt" update
  $maysudo "$apt" install -y "${deps[@]}"
  exit 0
fi

# Fedora, CentOS, RHEL, Alma, Amazon, Oracle, etc.
# https://packages.fedoraproject.org/
dnf=$(command -v dnf || true)
if [[ -n $dnf ]]; then
  deps=(
    gcc
    clang
    cmake
    alsa-lib-devel
    fontconfig-devel
    wayland-devel
    libxkbcommon-x11-devel
    openssl-devel
    libzstd-devel
    vulkan-loader
    sqlite-devel
  )
  if grep -q '^ID="(fedora)' /etc/os-release; then
    deps+=(
      # Perl dependencies are needed for openssl-sys crate see https://docs.rs/openssl/latest/openssl/
      perl-FindBin
      perl-IPC-Cmd
      # perl-File-Compare
      # perl-File-Copy
    )
  fi
  # gcc-c++ is g++ on RHEL8 and 8.x clones
  if (grep -qP '^ID="(rhel|rocky|almalinux|ol)' /etc/os-release &&
      grep -qP '^VERSION_ID="8' /etc/os-release); then
    deps+=( "gcc-c++" )
    mold_check
  else
    deps+=(
      g++
      mold
    )
  fi

  # libxkbcommon-x11-devel is in the crb repo on RHEL and CentOS, not needed for Fedora
  if grep -qP '(Redhat|CentOS)' /etc/redhat-release; then
    if $maysudo "$dnf" config-manager --help &>/dev/null; then
      $maysudo "$dnf" install -y 'dnf-command(config-manager)'
    fi
    $maysudo "$dnf" config-manager --set-enabled crb
  fi

  $maysudo "$dnf" install -y "${deps[@]}"
  exit 0
fi

# openSUSE
# https://software.opensuse.org/
zyp=$(command -v zypper || true)
if [[ -n $zyp ]]; then
  deps=(
    gcc
    gcc-c++
    clang
    make
    cmake
    alsa-devel
    fontconfig-devel
    wayland-devel
    libxkbcommon-x11-devel
    openssl-devel
    libzstd-devel
    libvulkan1
    mold
    sqlite3-devel
  )
  $maysudo "$zyp" install -y "${deps[@]}"
  exit 0
fi

# Arch, Manjaro, etc.
# https://archlinux.org/packages
pacman=$(command -v pacman || true)
if [[ -n $pacman ]]; then
  deps=(
    gcc
    clang
    cmake
    alsa-lib
    fontconfig
    wayland
    libgit2
    libxkbcommon-x11
    openssl
    zstd
    pkgconf
    mold
    sqlite
    jq
  )
  $maysudo "$pacman" -S --needed --noconfirm "${deps[@]}"
  exit 0
fi

# Void
# https://voidlinux.org/packages/
xbps=$(command -v xbps-install || true)
if [[ -n $xbps ]]; then
  deps=(
    gettext-devel
    clang
    cmake
    jq
    elfutils-devel
    gcc
    alsa-lib-devel
    fontconfig-devel
    libxcb-devel
    libxkbcommon-devel
    libzstd-devel
    openssl-devel
    wayland-devel
    vulkan-loader
    mold
    sqlite-devel
  )
  $maysudo "$xbps" -Syu "${deps[@]}"
  exit 0
fi

# Gentoo
# https://packages.gentoo.org/
emerge=$(command -v emerge || true)
if [[ -n $emerge ]]; then
  deps=(
    app-arch/zstd
    dev-libs/openssl
    dev-libs/wayland
    dev-util/cmake
    media-libs/alsa-lib
    media-libs/fontconfig
    media-libs/vulkan-loader
    x11-libs/libxcb
    x11-libs/libxkbcommon
    sys-devel/mold
    dev-db/sqlite
  )
  $maysudo "$emerge" -u "${deps[@]}"
  exit 0
fi

echo "Unsupported Linux distribution in script/linux"
