#!/bin/bash
set -euxo pipefail

PRETTIER_VERSION=3.5.0

pnpm dlx "prettier@${PRETTIER_VERSION}" assets/settings/default.json --check || {
    echo "To fix, run from the root of the Zed repo:"
    echo "  pnpm dlx prettier@${PRETTIER_VERSION} assets/settings/default.json --write"
    false
}

cd docs
pnpm dlx "prettier@${PRETTIER_VERSION}" . --check || {
    echo "To fix, run from the root of the Zed repo:"
    echo "  cd docs && pnpm dlx prettier@${PRETTIER_VERSION} . --write && cd .."
    false
}
