#!/usr/bin/env bash

set -xeuo pipefail

# if root or if sudo/unavailable, define an empty variable
if [ "$(id -u)" -eq 0 ]
then maysudo=''
else maysudo="$(command -v sudo || command -v doas || true)"
fi

deps=(
  clang
)

$maysudo apt-get update
$maysudo apt-get install -y "${deps[@]}"
exit 0
