#!/bin/bash

# Based on the template in: https://docs.digitalocean.com/reference/api/spaces-api/
set -ux

# Step 1: Define the parameters for the Space you want to upload to.
SPACE="zed-nightly-host" # Find your endpoint in the control panel, under Settings.
REGION="nyc3" # Must be "us-east-1" when creating new Spaces. Otherwise, use the region in your endpoint (e.g. nyc3).

# Step 2: Define a function that uploads your object via cURL.
function uploadToSpaces
{
  file_to_upload="$1"
  file_name="$2"
  space_path="nightly"
  date=$(date +"%a, %d %b %Y %T %z")
  acl="x-amz-acl:private"
  content_type="application/octet-stream"
  storage_type="x-amz-storage-class:STANDARD"
  string="PUT\n\n${content_type}\n${date}\n${acl}\n${storage_type}\n/${SPACE}/${space_path}/${file_name}"
  signature=$(echo -en "${string}" | openssl sha1 -hmac "${DIGITALOCEAN_SPACES_SECRET_KEY}" -binary | base64)

  curl --fail -vv -s -X PUT -T "$file_to_upload" \
    -H "Host: ${SPACE}.${REGION}.digitaloceanspaces.com" \
    -H "Date: $date" \
    -H "Content-Type: $content_type" \
    -H "$storage_type" \
    -H "$acl" \
    -H "Authorization: AWS ${DIGITALOCEAN_SPACES_ACCESS_KEY}:$signature" \
    "https://${SPACE}.${REGION}.digitaloceanspaces.com/${space_path}/${file_name}"
}

sha=$(git rev-parse HEAD)
echo ${sha} > target/latest-sha

uploadToSpaces "target/release/Zed.dmg" "Zed.dmg"
uploadToSpaces "target/latest-sha" "latest-sha"
