#!/usr/bin/env bash

set -eu
source script/lib/deploy-helpers.sh

if [[ $# != 1 ]]; then
  echo "Usage: $0 <production|staging>"
  exit 1
fi

environment=$1
url="$(url_for_environment $environment)"
tag="$(tag_for_environment $environment)"

target_zed_kube_cluster

deployed_image_id=$(
  kubectl \
    --namespace=${environment} \
    get deployment collab \
    -o 'jsonpath={.spec.template.spec.containers[0].image}' \
    | cut -d: -f2
)

echo "Deployed image version: $deployed_image_id"

git fetch >/dev/null
if [[ "$(git rev-parse tags/$tag)" != $deployed_image_id ]]; then
    echo "NOTE: tags/$tag $(git rev-parse tags/$tag) is not yet deployed"
fi;
