#!/bin/bash

set -eu
source script/lib/deploy-helpers.sh

if [[ $# != 1 ]]; then
  echo "Usage: $0 <production|staging>"
  exit 1
fi

environment=$1
url="$(url_for_environment $environment)"
tag="$(tag_for_environment $environment)"

target_zed_kube_cluster

deployed_image_id=$(
  kubectl \
    --namespace=${environment} \
    get deployment collab \
    -o 'jsonpath={.spec.template.spec.containers[0].image}' \
    | cut -d: -f2
)
git fetch >/dev/null

echo "Deployed image version: $deployed_image_id"
echo "Version from the web: $(curl -sS $url)"
echo "Currently tagged version: $(git rev-parse tags/$tag)"
