project_id = "85f406f4-69f1-4f41-b8e2-45550cd925d7"
name = "zed"

[tools]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
]

[tools.foragers.cargo]
github = "wezel-build/forager_cargo"
