// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Border { width: number, color: string, overlay: boolean, top: boolean, right: boolean, bottom: boolean, left: boolean, }