// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Spacing = number | { top: number, left: number, bottom: number, right: number, };