[package]
name = "gpui_engine"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_engine.rs"
doctest = false

[features]
default = []
test-support = ["gpui_types/test-support"]
bench-support = ["test-support"]

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
etagere.workspace = true
gpui_shared_string.workspace = true
gpui_types.workspace = true
image.workspace = true
log.workspace = true
refineable.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-video.workspace = true

[dev-dependencies]
rand.workspace = true
