use std::sync::Arc;

use serde::{Deserialize, Serialize};
use strum::{EnumIter, EnumString, IntoStaticStr};

#[derive(
    Debug, PartialEq, Eq, Copy, Clone, EnumIter, EnumString, IntoStaticStr, Serialize, Deserialize,
)]
#[strum(serialize_all = "snake_case")]
pub enum IconName {
    Ai,
    AiAnthropic,
    AiBedrock,
    AiClaude,
    AiDeepSeek,
    AiEdit,
    AiGemini,
    AiGoogle,
    AiLmStudio,
    AiMistral,
    AiOllama,
    AiOpenAi,
    AiOpenAiCompat,
    AiOpenRouter,
    AiVZero,
    AiXAi,
    AiZed,
    #[serde(alias = "Update")]
    ArrowCircle,
    #[serde(alias = "ArrowDownFromLine")]
    ArrowDown,
    ArrowDown10,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowRightLeft,
    #[serde(alias = "ArrowUpAlt")]
    #[serde(alias = "ArrowUpFromLine")]
    ArrowUp,
    #[serde(alias = "ExternalLink")]
    #[serde(alias = "ArrowUpRightAlt")]
    ArrowUpRight,
    Attach,
    AtSign,
    AudioOff,
    AudioOn,
    #[serde(alias = "Delete")]
    Backspace,
    Bell,
    BellDot,
    BellOff,
    BellRing,
    Binary,
    Blocks,
    #[serde(alias = "Bolt")]
    BoltOutlined,
    #[serde(alias = "BoltFilledAlt")]
    BoltFilled,
    Book,
    BookCopy,
    #[serde(alias = "InlayHint")]
    CaseSensitive,
    #[serde(alias = "MessageBubbles")]
    Chat,
    Check,
    CheckDouble,
    #[serde(alias = "ChevronDownSmall")]
    ChevronDown,
    ChevronDownUp,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronUpDown,
    Circle,
    CircleHelp,
    #[serde(alias = "X")]
    Close,
    CloudDownload,
    Code,
    Cog,
    Command,
    Control,
    Copilot,
    CopilotDisabled,
    CopilotError,
    CopilotInit,
    Copy,
    CountdownTimer,
    Crosshair,
    CursorIBeam,
    Dash,
    DatabaseZap,
    Debug,
    DebugBreakpoint,
    DebugContinue,
    DebugDisabledBreakpoint,
    DebugDisabledLogBreakpoint,
    DebugDetach,
    DebugIgnoreBreakpoints,
    DebugLogBreakpoint,
    DebugPause,
    DebugStepBack,
    DebugStepInto,
    DebugStepOut,
    DebugStepOver,
    Diff,
    Disconnected,
    Download,
    EditorAtom,
    EditorCursor,
    EditorEmacs,
    EditorJetBrains,
    EditorSublime,
    EditorVsCode,
    Ellipsis,
    EllipsisVertical,
    Envelope,
    Eraser,
    Escape,
    Exit,
    ExpandDown,
    ExpandUp,
    ExpandVertical,
    Eye,
    File,
    FileCode,
    FileDiff,
    FileDoc,
    FileGeneric,
    FileGit,
    FileLock,
    #[serde(alias = "DocumentText")]
    FileMarkdown,
    FileRust,
    FileTextFilled,
    #[serde(alias = "FileText")]
    FileTextOutlined,
    FileToml,
    FileTree,
    Filter,
    Flame,
    Folder,
    FolderOpen,
    #[serde(alias = "FileSearch")]
    FolderSearch,
    Font,
    FontSize,
    FontWeight,
    ForwardArrow,
    GenericClose,
    GenericMaximize,
    GenericMinimize,
    GenericRestore,
    GitBranch,
    #[serde(alias = "GitBranchSmall")]
    GitBranchAlt,
    Github,
    Hash,
    HistoryRerun,
    Image,
    Indicator,
    Info,
    Json,
    Keyboard,
    Library,
    LineHeight,
    Link,
    ListCollapse,
    ListFilter,
    ListTodo,
    ListTree,
    ListX,
    LoadCircle,
    LocationEdit,
    LockOutlined,
    MagnifyingGlass,
    Maximize,
    Menu,
    MenuAlt,
    MenuAltTemp,
    Mic,
    MicMute,
    Minimize,
    #[serde(alias = "ScrollText")]
    Notepad,
    Option,
    PageDown,
    PageUp,
    Paperclip,
    Pencil,
    PencilUnavailable,
    Person,
    Pin,
    #[serde(alias = "Play")]
    PlayOutlined,
    PlayFilled,
    Plus,
    Power,
    Public,
    PullRequest,
    #[serde(alias = "SearchSelection")]
    Quote,
    #[serde(alias = "Context")]
    Reader,
    RefreshTitle,
    Regex,
    ReplNeutral,
    Replace,
    ReplaceAll,
    ReplaceNext,
    ReplyArrowRight,
    Rerun,
    Return,
    #[serde(alias = "DebugRestart")]
    RotateCcw,
    RotateCw,
    Scissors,
    Screen,
    SelectAll,
    Send,
    Server,
    Settings,
    ShieldCheck,
    Shift,
    Slash,
    Sliders,
    Space,
    Sparkle,
    Split,
    SplitAlt,
    SquareDot,
    SquareMinus,
    SquarePlus,
    Star,
    StarFilled,
    #[serde(alias = "StopFilled")]
    Stop,
    Supermaven,
    SupermavenDisabled,
    SupermavenError,
    SupermavenInit,
    SwatchBook,
    SweepAi,
    Tab,
    Terminal,
    TerminalAlt,
    TerminalGhost,
    TextSnippet,
    #[serde(alias = "NewTextThread")]
    TextThread,
    #[serde(alias = "NewThread")]
    Thread,
    #[serde(alias = "NewFromSummary")]
    ThreadFromSummary,
    ThumbsDown,
    ThumbsUp,
    TodoComplete,
    TodoPending,
    TodoProgress,
    ToolCopy,
    ToolDeleteFile,
    ToolDiagnostics,
    ToolFolder,
    #[serde(alias = "Hammer")]
    ToolHammer,
    ToolNotification,
    ToolPencil,
    ToolRead,
    ToolRegex,
    ToolSearch,
    ToolTerminal,
    #[serde(alias = "LightBulb")]
    ToolThink,
    #[serde(alias = "Globe")]
    ToolWeb,
    #[serde(alias = "TrashAlt")]
    Trash,
    Triangle,
    TriangleRight,
    Undo,
    Unpin,
    UserCheck,
    UserGroup,
    UserRoundPen,
    Warning,
    WholeWord,
    XCircle,
    XCircleFilled,
    ZedAgent,
    #[serde(alias = "ZedAssistantFilled")]
    ZedAssistant,
    ZedBurnMode,
    ZedBurnModeOn,
    ZedSrcCustom,
    ZedSrcExtension,
    ZedPredict,
    ZedPredictDisabled,
    ZedPredictDown,
    ZedPredictError,
    ZedPredictUp,
    ZedXCopilot,
    Linux,
}

impl IconName {
    /// Returns the path to this icon.
    pub fn path(&self) -> Arc<str> {
        let file_stem: &'static str = self.into();
        format!("icons/{file_stem}.svg").into()
    }
}
