use std::sync::Arc;

use serde::{Deserialize, Serialize, de};
use strum::{EnumIter, EnumString, IntoStaticStr};

#[derive(
    Debug, PartialEq, Eq, Copy, Clone, EnumIter, EnumString, IntoStaticStr, Serialize,
)]
#[strum(serialize_all = "snake_case")]
pub enum IconName {
    Ai,
    AiAnthropic,
    AiBedrock,
    AiClaude,
    AiDeepSeek,
    AiEdit,
    AiGemini,
    AiGoogle,
    AiLmStudio,
    AiMistral,
    AiOllama,
    AiOpenAi,
    AiOpenAiCompat,
    AiOpenRouter,
    AiVZero,
    AiXAi,
    AiZed,
    ArrowCircle,
    ArrowDown,
    ArrowDown10,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowRightLeft,
    ArrowUp,
    ArrowUpRight,
    AtSign,
    Attach,
    AudioOff,
    AudioOn,
    Backspace,
    Bell,
    BellDot,
    BellOff,
    BellRing,
    Binary,
    Blocks,
    BoltFilled,
    BoltOutlined,
    Book,
    BookCopy,
    Box,
    CaseSensitive,
    Chat,
    Check,
    CheckDouble,
    ChevronDown,
    ChevronDownUp,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronUpDown,
    Circle,
    CircleHelp,
    Close,
    CloudDownload,
    Code,
    Cog,
    Command,
    Control,
    Copilot,
    CopilotDisabled,
    CopilotError,
    CopilotInit,
    Copy,
    CountdownTimer,
    Crosshair,
    CursorIBeam,
    Dash,
    DatabaseZap,
    Debug,
    DebugBreakpoint,
    DebugContinue,
    DebugDetach,
    DebugDisabledBreakpoint,
    DebugDisabledLogBreakpoint,
    DebugIgnoreBreakpoints,
    DebugLogBreakpoint,
    DebugPause,
    DebugStepInto,
    DebugStepOut,
    DebugStepOver,
    Diff,
    Disconnected,
    Download,
    EditorAtom,
    EditorCursor,
    EditorEmacs,
    EditorJetBrains,
    EditorSublime,
    EditorVsCode,
    Ellipsis,
    EllipsisVertical,
    Envelope,
    Eraser,
    Escape,
    Exit,
    ExpandDown,
    ExpandUp,
    ExpandVertical,
    Eye,
    File,
    FileCode,
    FileDiff,
    FileDoc,
    FileGeneric,
    FileGit,
    FileLock,
    FileMarkdown,
    FileRust,
    FileTextFilled,
    FileTextOutlined,
    FileToml,
    FileTree,
    Filter,
    Flame,
    Folder,
    FolderOpen,
    FolderSearch,
    Font,
    FontSize,
    FontWeight,
    ForwardArrow,
    GenericClose,
    GenericMaximize,
    GenericMinimize,
    GenericRestore,
    GitBranch,
    GitBranchAlt,
    GitBranchPlus,
    Github,
    Hash,
    HistoryRerun,
    Image,
    Inception,
    Indicator,
    Info,
    Json,
    Keyboard,
    Library,
    LineHeight,
    Link,
    Linux,
    ListCollapse,
    ListFilter,
    ListTodo,
    ListTree,
    ListX,
    LoadCircle,
    LocationEdit,
    LockOutlined,
    MagnifyingGlass,
    Maximize,
    Menu,
    MenuAlt,
    MenuAltTemp,
    Mic,
    MicMute,
    Minimize,
    Notepad,
    Option,
    PageDown,
    PageUp,
    Paperclip,
    Pencil,
    PencilUnavailable,
    Person,
    Pin,
    PlayFilled,
    PlayOutlined,
    Plus,
    Power,
    Public,
    PullRequest,
    Quote,
    Reader,
    RefreshTitle,
    Regex,
    ReplNeutral,
    Replace,
    ReplaceAll,
    ReplaceNext,
    ReplyArrowRight,
    Rerun,
    Return,
    RotateCcw,
    RotateCw,
    Scissors,
    Screen,
    SelectAll,
    Send,
    Server,
    Settings,
    ShieldCheck,
    Shift,
    Slash,
    Sliders,
    Space,
    Sparkle,
    Split,
    SplitAlt,
    SquareDot,
    SquareMinus,
    SquarePlus,
    Star,
    StarFilled,
    Stop,
    Supermaven,
    SupermavenDisabled,
    SupermavenError,
    SupermavenInit,
    SwatchBook,
    SweepAi,
    Tab,
    Terminal,
    TerminalAlt,
    TerminalGhost,
    TextSnippet,
    TextThread,
    Thread,
    ThreadFromSummary,
    ThumbsDown,
    ThumbsUp,
    TodoComplete,
    TodoPending,
    TodoProgress,
    ToolCopy,
    ToolDeleteFile,
    ToolDiagnostics,
    ToolFolder,
    ToolHammer,
    ToolNotification,
    ToolPencil,
    ToolRead,
    ToolRegex,
    ToolSearch,
    ToolTerminal,
    ToolThink,
    ToolWeb,
    Trash,
    Triangle,
    TriangleRight,
    Undo,
    Unpin,
    UserCheck,
    UserGroup,
    UserRoundPen,
    Warning,
    WholeWord,
    XCircle,
    XCircleFilled,
    ZedAgent,
    ZedAgentTwo,
    ZedAssistant,
    ZedBurnMode,
    ZedBurnModeOn,
    ZedPredict,
    ZedPredictDisabled,
    ZedPredictDown,
    ZedPredictError,
    ZedPredictUp,
    ZedSrcCustom,
    ZedSrcExtension,
    ZedXCopilot,
}

impl IconName {
    /// Returns the path to this icon.
    pub fn path(&self) -> Arc<str> {
        let file_stem: &'static str = self.into();
        format!("icons/{file_stem}.svg").into()
    }
}

impl Default for IconName {
    fn default() -> Self {
        IconName::File
    }
}

impl<'de> Deserialize<'de> for IconName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: de::Deserializer<'de>,
    {
        struct IconNameVisitor;

        impl<'de> de::Visitor<'de> for IconNameVisitor {
            type Value = IconName;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("a valid icon name string")
            }

            fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
            where
                E: de::Error,
            {
                match value {
                    "Ai" => Ok(IconName::Ai),
                    "AiAnthropic" => Ok(IconName::AiAnthropic),
                    "AiBedrock" => Ok(IconName::AiBedrock),
                    "AiClaude" => Ok(IconName::AiClaude),
                    "AiDeepSeek" => Ok(IconName::AiDeepSeek),
                    "AiEdit" => Ok(IconName::AiEdit),
                    "AiGemini" => Ok(IconName::AiGemini),
                    "AiGoogle" => Ok(IconName::AiGoogle),
                    "AiLmStudio" => Ok(IconName::AiLmStudio),
                    "AiMistral" => Ok(IconName::AiMistral),
                    "AiOllama" => Ok(IconName::AiOllama),
                    "AiOpenAi" => Ok(IconName::AiOpenAi),
                    "AiOpenAiCompat" => Ok(IconName::AiOpenAiCompat),
                    "AiOpenRouter" => Ok(IconName::AiOpenRouter),
                    "AiVZero" => Ok(IconName::AiVZero),
                    "AiXAi" => Ok(IconName::AiXAi),
                    "AiZed" => Ok(IconName::AiZed),
                    "ArrowCircle" => Ok(IconName::ArrowCircle),
                    "ArrowDown" => Ok(IconName::ArrowDown),
                    "ArrowDown10" => Ok(IconName::ArrowDown10),
                    "ArrowDownRight" => Ok(IconName::ArrowDownRight),
                    "ArrowLeft" => Ok(IconName::ArrowLeft),
                    "ArrowRight" => Ok(IconName::ArrowRight),
                    "ArrowRightLeft" => Ok(IconName::ArrowRightLeft),
                    "ArrowUp" => Ok(IconName::ArrowUp),
                    "ArrowUpRight" => Ok(IconName::ArrowUpRight),
                    "AtSign" => Ok(IconName::AtSign),
                    "Attach" => Ok(IconName::Attach),
                    "AudioOff" => Ok(IconName::AudioOff),
                    "AudioOn" => Ok(IconName::AudioOn),
                    "Backspace" => Ok(IconName::Backspace),
                    "Bell" => Ok(IconName::Bell),
                    "BellDot" => Ok(IconName::BellDot),
                    "BellOff" => Ok(IconName::BellOff),
                    "BellRing" => Ok(IconName::BellRing),
                    "Binary" => Ok(IconName::Binary),
                    "Blocks" => Ok(IconName::Blocks),
                    "BoltFilled" => Ok(IconName::BoltFilled),
                    "BoltOutlined" => Ok(IconName::BoltOutlined),
                    "Book" => Ok(IconName::Book),
                    "BookCopy" => Ok(IconName::BookCopy),
                    "Box" => Ok(IconName::Box),
                    "CaseSensitive" => Ok(IconName::CaseSensitive),
                    "Chat" => Ok(IconName::Chat),
                    "Check" => Ok(IconName::Check),
                    "CheckDouble" => Ok(IconName::CheckDouble),
                    "ChevronDown" => Ok(IconName::ChevronDown),
                    "ChevronDownUp" => Ok(IconName::ChevronDownUp),
                    "ChevronLeft" => Ok(IconName::ChevronLeft),
                    "ChevronRight" => Ok(IconName::ChevronRight),
                    "ChevronUp" => Ok(IconName::ChevronUp),
                    "ChevronUpDown" => Ok(IconName::ChevronUpDown),
                    "Circle" => Ok(IconName::Circle),
                    "CircleHelp" => Ok(IconName::CircleHelp),
                    "Close" => Ok(IconName::Close),
                    "CloudDownload" => Ok(IconName::CloudDownload),
                    "Code" => Ok(IconName::Code),
                    "Cog" => Ok(IconName::Cog),
                    "Command" => Ok(IconName::Command),
                    "Control" => Ok(IconName::Control),
                    "Copilot" => Ok(IconName::Copilot),
                    "CopilotDisabled" => Ok(IconName::CopilotDisabled),
                    "CopilotError" => Ok(IconName::CopilotError),
                    "CopilotInit" => Ok(IconName::CopilotInit),
                    "Copy" => Ok(IconName::Copy),
                    "CountdownTimer" => Ok(IconName::CountdownTimer),
                    "Crosshair" => Ok(IconName::Crosshair),
                    "CursorIBeam" => Ok(IconName::CursorIBeam),
                    "Dash" => Ok(IconName::Dash),
                    "DatabaseZap" => Ok(IconName::DatabaseZap),
                    "Debug" => Ok(IconName::Debug),
                    "DebugBreakpoint" => Ok(IconName::DebugBreakpoint),
                    "DebugContinue" => Ok(IconName::DebugContinue),
                    "DebugDetach" => Ok(IconName::DebugDetach),
                    "DebugDisabledBreakpoint" => Ok(IconName::DebugDisabledBreakpoint),
                    "DebugDisabledLogBreakpoint" => Ok(IconName::DebugDisabledLogBreakpoint),
                    "DebugIgnoreBreakpoints" => Ok(IconName::DebugIgnoreBreakpoints),
                    "DebugLogBreakpoint" => Ok(IconName::DebugLogBreakpoint),
                    "DebugPause" => Ok(IconName::DebugPause),
                    "DebugStepInto" => Ok(IconName::DebugStepInto),
                    "DebugStepOut" => Ok(IconName::DebugStepOut),
                    "DebugStepOver" => Ok(IconName::DebugStepOver),
                    "Diff" => Ok(IconName::Diff),
                    "Disconnected" => Ok(IconName::Disconnected),
                    "Download" => Ok(IconName::Download),
                    "EditorAtom" => Ok(IconName::EditorAtom),
                    "EditorCursor" => Ok(IconName::EditorCursor),
                    "EditorEmacs" => Ok(IconName::EditorEmacs),
                    "EditorJetBrains" => Ok(IconName::EditorJetBrains),
                    "EditorSublime" => Ok(IconName::EditorSublime),
                    "EditorVsCode" => Ok(IconName::EditorVsCode),
                    "Ellipsis" => Ok(IconName::Ellipsis),
                    "EllipsisVertical" => Ok(IconName::EllipsisVertical),
                    "Envelope" => Ok(IconName::Envelope),
                    "Eraser" => Ok(IconName::Eraser),
                    "Escape" => Ok(IconName::Escape),
                    "Exit" => Ok(IconName::Exit),
                    "ExpandDown" => Ok(IconName::ExpandDown),
                    "ExpandUp" => Ok(IconName::ExpandUp),
                    "ExpandVertical" => Ok(IconName::ExpandVertical),
                    "Eye" => Ok(IconName::Eye),
                    "File" => Ok(IconName::File),
                    "FileCode" => Ok(IconName::FileCode),
                    "FileDiff" => Ok(IconName::FileDiff),
                    "FileDoc" => Ok(IconName::FileDoc),
                    "FileGeneric" => Ok(IconName::FileGeneric),
                    "FileGit" => Ok(IconName::FileGit),
                    "FileLock" => Ok(IconName::FileLock),
                    "FileMarkdown" => Ok(IconName::FileMarkdown),
                    "FileRust" => Ok(IconName::FileRust),
                    "FileTextFilled" => Ok(IconName::FileTextFilled),
                    "FileTextOutlined" => Ok(IconName::FileTextOutlined),
                    "FileToml" => Ok(IconName::FileToml),
                    "FileTree" => Ok(IconName::FileTree),
                    "Filter" => Ok(IconName::Filter),
                    "Flame" => Ok(IconName::Flame),
                    "Folder" => Ok(IconName::Folder),
                    "FolderOpen" => Ok(IconName::FolderOpen),
                    "FolderSearch" => Ok(IconName::FolderSearch),
                    "Font" => Ok(IconName::Font),
                    "FontSize" => Ok(IconName::FontSize),
                    "FontWeight" => Ok(IconName::FontWeight),
                    "ForwardArrow" => Ok(IconName::ForwardArrow),
                    "GenericClose" => Ok(IconName::GenericClose),
                    "GenericMaximize" => Ok(IconName::GenericMaximize),
                    "GenericMinimize" => Ok(IconName::GenericMinimize),
                    "GenericRestore" => Ok(IconName::GenericRestore),
                    "GitBranch" => Ok(IconName::GitBranch),
                    "GitBranchAlt" => Ok(IconName::GitBranchAlt),
                    "GitBranchPlus" => Ok(IconName::GitBranchPlus),
                    "Github" => Ok(IconName::Github),
                    "Hash" => Ok(IconName::Hash),
                    "HistoryRerun" => Ok(IconName::HistoryRerun),
                    "Image" => Ok(IconName::Image),
                    "Inception" => Ok(IconName::Inception),
                    "Indicator" => Ok(IconName::Indicator),
                    "Info" => Ok(IconName::Info),
                    "Json" => Ok(IconName::Json),
                    "Keyboard" => Ok(IconName::Keyboard),
                    "Library" => Ok(IconName::Library),
                    "LineHeight" => Ok(IconName::LineHeight),
                    "Link" => Ok(IconName::Link),
                    "Linux" => Ok(IconName::Linux),
                    "ListCollapse" => Ok(IconName::ListCollapse),
                    "ListFilter" => Ok(IconName::ListFilter),
                    "ListTodo" => Ok(IconName::ListTodo),
                    "ListTree" => Ok(IconName::ListTree),
                    "ListX" => Ok(IconName::ListX),
                    "LoadCircle" => Ok(IconName::LoadCircle),
                    "LocationEdit" => Ok(IconName::LocationEdit),
                    "LockOutlined" => Ok(IconName::LockOutlined),
                    "MagnifyingGlass" => Ok(IconName::MagnifyingGlass),
                    "Maximize" => Ok(IconName::Maximize),
                    "Menu" => Ok(IconName::Menu),
                    "MenuAlt" => Ok(IconName::MenuAlt),
                    "MenuAltTemp" => Ok(IconName::MenuAltTemp),
                    "Mic" => Ok(IconName::Mic),
                    "MicMute" => Ok(IconName::MicMute),
                    "Minimize" => Ok(IconName::Minimize),
                    "Notepad" => Ok(IconName::Notepad),
                    "Option" => Ok(IconName::Option),
                    "PageDown" => Ok(IconName::PageDown),
                    "PageUp" => Ok(IconName::PageUp),
                    "Paperclip" => Ok(IconName::Paperclip),
                    "Pencil" => Ok(IconName::Pencil),
                    "PencilUnavailable" => Ok(IconName::PencilUnavailable),
                    "Person" => Ok(IconName::Person),
                    "Pin" => Ok(IconName::Pin),
                    "PlayFilled" => Ok(IconName::PlayFilled),
                    "PlayOutlined" => Ok(IconName::PlayOutlined),
                    "Plus" => Ok(IconName::Plus),
                    "Power" => Ok(IconName::Power),
                    "Public" => Ok(IconName::Public),
                    "PullRequest" => Ok(IconName::PullRequest),
                    "Quote" => Ok(IconName::Quote),
                    "Reader" => Ok(IconName::Reader),
                    "RefreshTitle" => Ok(IconName::RefreshTitle),
                    "Regex" => Ok(IconName::Regex),
                    "ReplNeutral" => Ok(IconName::ReplNeutral),
                    "Replace" => Ok(IconName::Replace),
                    "ReplaceAll" => Ok(IconName::ReplaceAll),
                    "ReplaceNext" => Ok(IconName::ReplaceNext),
                    "ReplyArrowRight" => Ok(IconName::ReplyArrowRight),
                    "Rerun" => Ok(IconName::Rerun),
                    "Return" => Ok(IconName::Return),
                    "RotateCcw" => Ok(IconName::RotateCcw),
                    "RotateCw" => Ok(IconName::RotateCw),
                    "Scissors" => Ok(IconName::Scissors),
                    "Screen" => Ok(IconName::Screen),
                    "SelectAll" => Ok(IconName::SelectAll),
                    "Send" => Ok(IconName::Send),
                    "Server" => Ok(IconName::Server),
                    "Settings" => Ok(IconName::Settings),
                    "ShieldCheck" => Ok(IconName::ShieldCheck),
                    "Shift" => Ok(IconName::Shift),
                    "Slash" => Ok(IconName::Slash),
                    "Sliders" => Ok(IconName::Sliders),
                    "Space" => Ok(IconName::Space),
                    "Sparkle" => Ok(IconName::Sparkle),
                    "Split" => Ok(IconName::Split),
                    "SplitAlt" => Ok(IconName::SplitAlt),
                    "SquareDot" => Ok(IconName::SquareDot),
                    "SquareMinus" => Ok(IconName::SquareMinus),
                    "SquarePlus" => Ok(IconName::SquarePlus),
                    "Star" => Ok(IconName::Star),
                    "StarFilled" => Ok(IconName::StarFilled),
                    "Stop" => Ok(IconName::Stop),
                    "Supermaven" => Ok(IconName::Supermaven),
                    "SupermavenDisabled" => Ok(IconName::SupermavenDisabled),
                    "SupermavenError" => Ok(IconName::SupermavenError),
                    "SupermavenInit" => Ok(IconName::SupermavenInit),
                    "SwatchBook" => Ok(IconName::SwatchBook),
                    "SweepAi" => Ok(IconName::SweepAi),
                    "Tab" => Ok(IconName::Tab),
                    "Terminal" => Ok(IconName::Terminal),
                    "TerminalAlt" => Ok(IconName::TerminalAlt),
                    "TerminalGhost" => Ok(IconName::TerminalGhost),
                    "TextSnippet" => Ok(IconName::TextSnippet),
                    "TextThread" => Ok(IconName::TextThread),
                    "Thread" => Ok(IconName::Thread),
                    "ThreadFromSummary" => Ok(IconName::ThreadFromSummary),
                    "ThumbsDown" => Ok(IconName::ThumbsDown),
                    "ThumbsUp" => Ok(IconName::ThumbsUp),
                    "TodoComplete" => Ok(IconName::TodoComplete),
                    "TodoPending" => Ok(IconName::TodoPending),
                    "TodoProgress" => Ok(IconName::TodoProgress),
                    "ToolCopy" => Ok(IconName::ToolCopy),
                    "ToolDeleteFile" => Ok(IconName::ToolDeleteFile),
                    "ToolDiagnostics" => Ok(IconName::ToolDiagnostics),
                    "ToolFolder" => Ok(IconName::ToolFolder),
                    "ToolHammer" => Ok(IconName::ToolHammer),
                    "ToolNotification" => Ok(IconName::ToolNotification),
                    "ToolPencil" => Ok(IconName::ToolPencil),
                    "ToolRead" => Ok(IconName::ToolRead),
                    "ToolRegex" => Ok(IconName::ToolRegex),
                    "ToolSearch" => Ok(IconName::ToolSearch),
                    "ToolTerminal" => Ok(IconName::ToolTerminal),
                    "ToolThink" => Ok(IconName::ToolThink),
                    "ToolWeb" => Ok(IconName::ToolWeb),
                    "Trash" => Ok(IconName::Trash),
                    "Triangle" => Ok(IconName::Triangle),
                    "TriangleRight" => Ok(IconName::TriangleRight),
                    "Undo" => Ok(IconName::Undo),
                    "Unpin" => Ok(IconName::Unpin),
                    "UserCheck" => Ok(IconName::UserCheck),
                    "UserGroup" => Ok(IconName::UserGroup),
                    "UserRoundPen" => Ok(IconName::UserRoundPen),
                    "Warning" => Ok(IconName::Warning),
                    "WholeWord" => Ok(IconName::WholeWord),
                    "XCircle" => Ok(IconName::XCircle),
                    "XCircleFilled" => Ok(IconName::XCircleFilled),
                    "ZedAgent" => Ok(IconName::ZedAgent),
                    "ZedAgentTwo" => Ok(IconName::ZedAgentTwo),
                    "ZedAssistant" => Ok(IconName::ZedAssistant),
                    "ZedBurnMode" => Ok(IconName::ZedBurnMode),
                    "ZedBurnModeOn" => Ok(IconName::ZedBurnModeOn),
                    "ZedPredict" => Ok(IconName::ZedPredict),
                    "ZedPredictDisabled" => Ok(IconName::ZedPredictDisabled),
                    "ZedPredictDown" => Ok(IconName::ZedPredictDown),
                    "ZedPredictError" => Ok(IconName::ZedPredictError),
                    "ZedPredictUp" => Ok(IconName::ZedPredictUp),
                    "ZedSrcCustom" => Ok(IconName::ZedSrcCustom),
                    "ZedSrcExtension" => Ok(IconName::ZedSrcExtension),
                    "ZedXCopilot" => Ok(IconName::ZedXCopilot),
                    _ => Ok(IconName::default()),
                }
            }
        }

        deserializer.deserialize_str(IconNameVisitor)
    }
}
