// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

#[allow(unused)]
use crate::{
    Appearance, StatusColorsRefinement, ThemeColorsRefinement, UserFontStyle, UserFontWeight,
    UserHighlightStyle, UserSyntaxTheme, UserTheme, UserThemeFamily, UserThemeStylesRefinement,
};

pub fn andromeda() -> UserThemeFamily {
    UserThemeFamily {
        name: "Andromeda".into(),
        author: "Eliver Lara (EliverLara)".into(),
        themes: vec![
            UserTheme {
                name: "Andromeda".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x1b1d23ff).into()),
                        border_variant: Some(rgba(0x1b1d23ff).into()),
                        border_focused: Some(rgba(0x746f77ff).into()),
                        border_selected: Some(rgba(0x1b1d23ff).into()),
                        border_transparent: Some(rgba(0x1b1d23ff).into()),
                        border_disabled: Some(rgba(0x1b1d23ff).into()),
                        elevated_surface_background: Some(rgba(0x23262eff).into()),
                        surface_background: Some(rgba(0x23262eff).into()),
                        background: Some(rgba(0x23262eff).into()),
                        element_background: Some(rgba(0x00e8c5cc).into()),
                        element_hover: Some(rgba(0x23262eff).into()),
                        element_selected: Some(rgba(0x23262eff).into()),
                        drop_target_background: Some(rgba(0x3a404eff).into()),
                        ghost_element_hover: Some(rgba(0x23262eff).into()),
                        text: Some(rgba(0xd4cdd8ff).into()),
                        tab_inactive_background: Some(rgba(0x23262eff).into()),
                        tab_active_background: Some(rgba(0x23262eff).into()),
                        editor_background: Some(rgba(0x23262eff).into()),
                        editor_gutter_background: Some(rgba(0x23262eff).into()),
                        editor_line_number: Some(rgba(0x746f77ff).into()),
                        editor_active_line_number: Some(rgba(0xd4cdd8ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xee5d42ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x95e072ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xffe66dff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x7bb7ffff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xff00a9ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x00e8c6ff).into()),
                        terminal_ansi_red: Some(rgba(0xee5d42ff).into()),
                        terminal_ansi_green: Some(rgba(0x95e072ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xffe66dff).into()),
                        terminal_ansi_blue: Some(rgba(0x7bb7ffff).into()),
                        terminal_ansi_magenta: Some(rgba(0xff00a9ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x00e8c6ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        deleted: Some(rgba(0xfc634cff).into()),
                        error: Some(rgba(0xfc634cff).into()),
                        hidden: Some(rgba(0x746f77ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9fa0a6cc).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc64dedff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xffe66dff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc64dedff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xee5d42ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x95e072ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf92571ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x95e072ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xffe66dff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x00e8c6ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Andromeda Bordered".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x1b1d23ff).into()),
                        border_variant: Some(rgba(0x1b1d23ff).into()),
                        border_focused: Some(rgba(0x746f77ff).into()),
                        border_selected: Some(rgba(0x1b1d23ff).into()),
                        border_transparent: Some(rgba(0x1b1d23ff).into()),
                        border_disabled: Some(rgba(0x1b1d23ff).into()),
                        elevated_surface_background: Some(rgba(0x23262eff).into()),
                        surface_background: Some(rgba(0x23262eff).into()),
                        background: Some(rgba(0x262933ff).into()),
                        element_background: Some(rgba(0x00e8c5cc).into()),
                        element_hover: Some(rgba(0x23262eff).into()),
                        element_selected: Some(rgba(0x23262eff).into()),
                        drop_target_background: Some(rgba(0x3a404eff).into()),
                        ghost_element_hover: Some(rgba(0x23262eff).into()),
                        text: Some(rgba(0xd4cdd8ff).into()),
                        tab_inactive_background: Some(rgba(0x23262eff).into()),
                        tab_active_background: Some(rgba(0x262933ff).into()),
                        editor_background: Some(rgba(0x262933ff).into()),
                        editor_gutter_background: Some(rgba(0x262933ff).into()),
                        editor_line_number: Some(rgba(0x746f77ff).into()),
                        editor_active_line_number: Some(rgba(0xd4cdd8ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xee5d42ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x95e072ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xffe66dff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x7bb7ffff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xff00a9ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x00e8c6ff).into()),
                        terminal_ansi_red: Some(rgba(0xee5d42ff).into()),
                        terminal_ansi_green: Some(rgba(0x95e072ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xffe66dff).into()),
                        terminal_ansi_blue: Some(rgba(0x7bb7ffff).into()),
                        terminal_ansi_magenta: Some(rgba(0xff00a9ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x00e8c6ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        deleted: Some(rgba(0xfc634cff).into()),
                        error: Some(rgba(0xfc634cff).into()),
                        hidden: Some(rgba(0x746f77ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9fa0a6cc).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc64dedff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xffe66dff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc64dedff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf39c11ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xee5d42ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x95e072ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xf92571ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x95e072ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xffe66dff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x00e8c6ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
        ],
    }
}
