use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn andromeda() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Andromeda".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x2b2f38ff).into(),
        border_variant: rgba(0x2b2f38ff).into(),
        border_focused: rgba(0x183934ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x262933ff).into(),
        surface: rgba(0x21242bff).into(),
        background: rgba(0x262933ff).into(),
        filled_element: rgba(0x262933ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x12231fff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x12231fff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf7f7f8ff).into(),
        text_muted: rgba(0xaca8aeff).into(),
        text_placeholder: rgba(0xf82871ff).into(),
        text_disabled: rgba(0x6b6b73ff).into(),
        text_accent: rgba(0x10a793ff).into(),
        icon_muted: rgba(0xaca8aeff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("emphasis".into(), rgba(0x10a793ff).into()),
                ("punctuation.bracket".into(), rgba(0xd8d5dbff).into()),
                ("attribute".into(), rgba(0x10a793ff).into()),
                ("variable".into(), rgba(0xf7f7f8ff).into()),
                ("predictive".into(), rgba(0x315f70ff).into()),
                ("property".into(), rgba(0x10a793ff).into()),
                ("variant".into(), rgba(0x10a793ff).into()),
                ("embedded".into(), rgba(0xf7f7f8ff).into()),
                ("string.special".into(), rgba(0xf29c14ff).into()),
                ("keyword".into(), rgba(0x10a793ff).into()),
                ("tag".into(), rgba(0x10a793ff).into()),
                ("enum".into(), rgba(0xf29c14ff).into()),
                ("link_text".into(), rgba(0xf29c14ff).into()),
                ("primary".into(), rgba(0xf7f7f8ff).into()),
                ("punctuation".into(), rgba(0xd8d5dbff).into()),
                ("punctuation.special".into(), rgba(0xd8d5dbff).into()),
                ("function".into(), rgba(0xfee56cff).into()),
                ("number".into(), rgba(0x96df71ff).into()),
                ("preproc".into(), rgba(0xf7f7f8ff).into()),
                ("operator".into(), rgba(0xf29c14ff).into()),
                ("constructor".into(), rgba(0x10a793ff).into()),
                ("string.escape".into(), rgba(0xafabb1ff).into()),
                ("string.special.symbol".into(), rgba(0xf29c14ff).into()),
                ("string".into(), rgba(0xf29c14ff).into()),
                ("comment".into(), rgba(0xafabb1ff).into()),
                ("hint".into(), rgba(0x618399ff).into()),
                ("type".into(), rgba(0x08e7c5ff).into()),
                ("label".into(), rgba(0x10a793ff).into()),
                ("comment.doc".into(), rgba(0xafabb1ff).into()),
                ("text.literal".into(), rgba(0xf29c14ff).into()),
                ("constant".into(), rgba(0x96df71ff).into()),
                ("string.regex".into(), rgba(0xf29c14ff).into()),
                ("emphasis.strong".into(), rgba(0x10a793ff).into()),
                ("title".into(), rgba(0xf7f7f8ff).into()),
                ("punctuation.delimiter".into(), rgba(0xd8d5dbff).into()),
                ("link_uri".into(), rgba(0x96df71ff).into()),
                ("boolean".into(), rgba(0x96df71ff).into()),
                ("punctuation.list_marker".into(), rgba(0xd8d5dbff).into()),
            ],
        },
        status_bar: rgba(0x262933ff).into(),
        title_bar: rgba(0x262933ff).into(),
        toolbar: rgba(0x1e2025ff).into(),
        tab_bar: rgba(0x21242bff).into(),
        editor: rgba(0x1e2025ff).into(),
        editor_subheader: rgba(0x21242bff).into(),
        editor_active_line: rgba(0x21242bff).into(),
        terminal: rgba(0x1e2025ff).into(),
        image_fallback_background: rgba(0x262933ff).into(),
        git_created: rgba(0x96df71ff).into(),
        git_modified: rgba(0x10a793ff).into(),
        git_deleted: rgba(0xf82871ff).into(),
        git_conflict: rgba(0xfee56cff).into(),
        git_ignored: rgba(0x6b6b73ff).into(),
        git_renamed: rgba(0xfee56cff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x10a793ff).into(),
                selection: rgba(0x10a7933d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x96df71ff).into(),
                selection: rgba(0x96df713d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xc74cecff).into(),
                selection: rgba(0xc74cec3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf29c14ff).into(),
                selection: rgba(0xf29c143d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x893ea6ff).into(),
                selection: rgba(0x893ea63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x08e7c5ff).into(),
                selection: rgba(0x08e7c53d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf82871ff).into(),
                selection: rgba(0xf828713d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfee56cff).into(),
                selection: rgba(0xfee56c3d).into(),
            },
        ],
    }
}
