use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_forest_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Forest Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x665f5cff).into(),
        border_variant: rgba(0x665f5cff).into(),
        border_focused: rgba(0x182d5bff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x443c39ff).into(),
        surface: rgba(0x27211eff).into(),
        background: rgba(0x443c39ff).into(),
        filled_element: rgba(0x443c39ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x0f1c3dff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x0f1c3dff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf0eeedff).into(),
        text_muted: rgba(0xa79f9dff).into(),
        text_placeholder: rgba(0xf22c3fff).into(),
        text_disabled: rgba(0x8e8683ff).into(),
        text_accent: rgba(0x407ee6ff).into(),
        icon_muted: rgba(0xa79f9dff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("link_uri".into(), rgba(0x7a9726ff).into()),
                ("punctuation.list_marker".into(), rgba(0xe6e2e0ff).into()),
                ("type".into(), rgba(0xc38417ff).into()),
                ("punctuation.bracket".into(), rgba(0xa8a19fff).into()),
                ("punctuation".into(), rgba(0xe6e2e0ff).into()),
                ("preproc".into(), rgba(0xf0eeedff).into()),
                ("punctuation.special".into(), rgba(0xc33ff3ff).into()),
                ("variable.special".into(), rgba(0x6666eaff).into()),
                ("tag".into(), rgba(0x407ee6ff).into()),
                ("constructor".into(), rgba(0x407ee6ff).into()),
                ("title".into(), rgba(0xf0eeedff).into()),
                ("hint".into(), rgba(0xa77087ff).into()),
                ("constant".into(), rgba(0x7a9726ff).into()),
                ("number".into(), rgba(0xdf521fff).into()),
                ("emphasis.strong".into(), rgba(0x407ee6ff).into()),
                ("boolean".into(), rgba(0x7a9726ff).into()),
                ("comment".into(), rgba(0x766e6bff).into()),
                ("string.special".into(), rgba(0xc33ff3ff).into()),
                ("text.literal".into(), rgba(0xdf5321ff).into()),
                ("string.regex".into(), rgba(0x3c96b8ff).into()),
                ("enum".into(), rgba(0xdf5321ff).into()),
                ("operator".into(), rgba(0xa8a19fff).into()),
                ("embedded".into(), rgba(0xf0eeedff).into()),
                ("string.special.symbol".into(), rgba(0x7a9725ff).into()),
                ("predictive".into(), rgba(0x8f5b70ff).into()),
                ("comment.doc".into(), rgba(0xa8a19fff).into()),
                ("variant".into(), rgba(0xc38417ff).into()),
                ("label".into(), rgba(0x407ee6ff).into()),
                ("property".into(), rgba(0xf22c40ff).into()),
                ("keyword".into(), rgba(0x6666eaff).into()),
                ("function".into(), rgba(0x3f7ee7ff).into()),
                ("string.escape".into(), rgba(0xa8a19fff).into()),
                ("string".into(), rgba(0x7a9725ff).into()),
                ("primary".into(), rgba(0xe6e2e0ff).into()),
                ("function.method".into(), rgba(0x3f7ee7ff).into()),
                ("link_text".into(), rgba(0xdf5321ff).into()),
                ("attribute".into(), rgba(0x407ee6ff).into()),
                ("emphasis".into(), rgba(0x407ee6ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xc38417ff).into(),
                ),
                ("variable".into(), rgba(0xe6e2e0ff).into()),
                ("punctuation.delimiter".into(), rgba(0xa8a19fff).into()),
            ],
        },
        status_bar: rgba(0x443c39ff).into(),
        title_bar: rgba(0x443c39ff).into(),
        toolbar: rgba(0x1b1918ff).into(),
        tab_bar: rgba(0x27211eff).into(),
        editor: rgba(0x1b1918ff).into(),
        editor_subheader: rgba(0x27211eff).into(),
        editor_active_line: rgba(0x27211eff).into(),
        terminal: rgba(0x1b1918ff).into(),
        image_fallback_background: rgba(0x443c39ff).into(),
        git_created: rgba(0x7a9726ff).into(),
        git_modified: rgba(0x407ee6ff).into(),
        git_deleted: rgba(0xf22c3fff).into(),
        git_conflict: rgba(0xc38418ff).into(),
        git_ignored: rgba(0x8e8683ff).into(),
        git_renamed: rgba(0xc38418ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x407ee6ff).into(),
                selection: rgba(0x407ee63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x7a9726ff).into(),
                selection: rgba(0x7a97263d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xc340f2ff).into(),
                selection: rgba(0xc340f23d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xdf5321ff).into(),
                selection: rgba(0xdf53213d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x6565e9ff).into(),
                selection: rgba(0x6565e93d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x3d97b8ff).into(),
                selection: rgba(0x3d97b83d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf22c3fff).into(),
                selection: rgba(0xf22c3f3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xc38418ff).into(),
                selection: rgba(0xc384183d).into(),
            },
        ],
    }
}
