use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_dune_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Dune Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0xa8a48eff).into(),
        border_variant: rgba(0xa8a48eff).into(),
        border_focused: rgba(0xcdd1f5ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xcecab4ff).into(),
        surface: rgba(0xeeebd7ff).into(),
        background: rgba(0xcecab4ff).into(),
        filled_element: rgba(0xcecab4ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xe3e5faff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xe3e5faff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x20201dff).into(),
        text_muted: rgba(0x706d5fff).into(),
        text_placeholder: rgba(0xd73737ff).into(),
        text_disabled: rgba(0x878471ff).into(),
        text_accent: rgba(0x6684dfff).into(),
        icon_muted: rgba(0x706d5fff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("primary".into(), rgba(0x292824ff).into()),
                ("comment".into(), rgba(0x999580ff).into()),
                ("type".into(), rgba(0xae9512ff).into()),
                ("variant".into(), rgba(0xae9512ff).into()),
                ("label".into(), rgba(0x6684dfff).into()),
                ("function.method".into(), rgba(0x6583e1ff).into()),
                ("variable.special".into(), rgba(0xb854d4ff).into()),
                ("string.regex".into(), rgba(0x1ead82ff).into()),
                ("property".into(), rgba(0xd73737ff).into()),
                ("keyword".into(), rgba(0xb854d4ff).into()),
                ("number".into(), rgba(0xb65610ff).into()),
                ("punctuation.list_marker".into(), rgba(0x292824ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xae9512ff).into(),
                ),
                ("punctuation.special".into(), rgba(0xd43451ff).into()),
                ("punctuation".into(), rgba(0x292824ff).into()),
                ("punctuation.delimiter".into(), rgba(0x6e6b5eff).into()),
                ("tag".into(), rgba(0x6684dfff).into()),
                ("link_text".into(), rgba(0xb65712ff).into()),
                ("boolean".into(), rgba(0x61ac39ff).into()),
                ("hint".into(), rgba(0xb37979ff).into()),
                ("operator".into(), rgba(0x6e6b5eff).into()),
                ("constant".into(), rgba(0x61ac39ff).into()),
                ("function".into(), rgba(0x6583e1ff).into()),
                ("text.literal".into(), rgba(0xb65712ff).into()),
                ("string.special.symbol".into(), rgba(0x5fac38ff).into()),
                ("attribute".into(), rgba(0x6684dfff).into()),
                ("emphasis".into(), rgba(0x6684dfff).into()),
                ("preproc".into(), rgba(0x20201dff).into()),
                ("comment.doc".into(), rgba(0x6e6b5eff).into()),
                ("punctuation.bracket".into(), rgba(0x6e6b5eff).into()),
                ("string".into(), rgba(0x5fac38ff).into()),
                ("enum".into(), rgba(0xb65712ff).into()),
                ("variable".into(), rgba(0x292824ff).into()),
                ("string.special".into(), rgba(0xd43451ff).into()),
                ("embedded".into(), rgba(0x20201dff).into()),
                ("emphasis.strong".into(), rgba(0x6684dfff).into()),
                ("predictive".into(), rgba(0xc88a8aff).into()),
                ("title".into(), rgba(0x20201dff).into()),
                ("constructor".into(), rgba(0x6684dfff).into()),
                ("link_uri".into(), rgba(0x61ac39ff).into()),
                ("string.escape".into(), rgba(0x6e6b5eff).into()),
            ],
        },
        status_bar: rgba(0xcecab4ff).into(),
        title_bar: rgba(0xcecab4ff).into(),
        toolbar: rgba(0xfefbecff).into(),
        tab_bar: rgba(0xeeebd7ff).into(),
        editor: rgba(0xfefbecff).into(),
        editor_subheader: rgba(0xeeebd7ff).into(),
        editor_active_line: rgba(0xeeebd7ff).into(),
        terminal: rgba(0xfefbecff).into(),
        image_fallback_background: rgba(0xcecab4ff).into(),
        git_created: rgba(0x61ac39ff).into(),
        git_modified: rgba(0x6684dfff).into(),
        git_deleted: rgba(0xd73737ff).into(),
        git_conflict: rgba(0xae9414ff).into(),
        git_ignored: rgba(0x878471ff).into(),
        git_renamed: rgba(0xae9414ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x6684dfff).into(),
                selection: rgba(0x6684df3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x61ac39ff).into(),
                selection: rgba(0x61ac393d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd43652ff).into(),
                selection: rgba(0xd436523d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb65712ff).into(),
                selection: rgba(0xb657123d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb755d3ff).into(),
                selection: rgba(0xb755d33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x21ad82ff).into(),
                selection: rgba(0x21ad823d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd73737ff).into(),
                selection: rgba(0xd737373d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xae9414ff).into(),
                selection: rgba(0xae94143d).into(),
            },
        ],
    }
}
