
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_dune_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Dune Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x6c695cff).into(),
        border_variant: rgba(0x6c695cff).into(),
        border_focused: rgba(0x262f56ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x45433bff).into(),
        surface: rgba(0x262622ff).into(),
        background: rgba(0x45433bff).into(),
        filled_element: rgba(0x45433bff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x171e38ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x171e38ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xfefbecff).into(),
        text_muted: rgba(0xa4a08bff).into(),
        text_placeholder: rgba(0xd73837ff).into(),
        text_disabled: rgba(0x8f8b77ff).into(),
        text_accent: rgba(0x6684e0ff).into(),
        icon_muted: rgba(0xa4a08bff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("constructor".into(), rgba(0x6684e0ff).into()),
                ("punctuation".into(), rgba(0xe8e4cfff).into()),
                ("punctuation.delimiter".into(), rgba(0xa6a28cff).into()),
                ("string.special".into(), rgba(0xd43451ff).into()),
                ("string.escape".into(), rgba(0xa6a28cff).into()),
                ("comment".into(), rgba(0x7d7a68ff).into()),
                ("enum".into(), rgba(0xb65611ff).into()),
                ("variable.special".into(), rgba(0xb854d4ff).into()),
                ("primary".into(), rgba(0xe8e4cfff).into()),
                ("comment.doc".into(), rgba(0xa6a28cff).into()),
                ("label".into(), rgba(0x6684e0ff).into()),
                ("operator".into(), rgba(0xa6a28cff).into()),
                ("string".into(), rgba(0x5fac38ff).into()),
                ("variant".into(), rgba(0xae9512ff).into()),
                ("variable".into(), rgba(0xe8e4cfff).into()),
                ("function.method".into(), rgba(0x6583e1ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xae9512ff).into(),
                ),
                ("string.regex".into(), rgba(0x1ead82ff).into()),
                ("emphasis.strong".into(), rgba(0x6684e0ff).into()),
                ("punctuation.special".into(), rgba(0xd43451ff).into()),
                ("punctuation.bracket".into(), rgba(0xa6a28cff).into()),
                ("link_text".into(), rgba(0xb65611ff).into()),
                ("link_uri".into(), rgba(0x5fac39ff).into()),
                ("boolean".into(), rgba(0x5fac39ff).into()),
                ("hint".into(), rgba(0xb17272ff).into()),
                ("tag".into(), rgba(0x6684e0ff).into()),
                ("function".into(), rgba(0x6583e1ff).into()),
                ("title".into(), rgba(0xfefbecff).into()),
                ("property".into(), rgba(0xd73737ff).into()),
                ("type".into(), rgba(0xae9512ff).into()),
                ("constant".into(), rgba(0x5fac39ff).into()),
                ("attribute".into(), rgba(0x6684e0ff).into()),
                ("predictive".into(), rgba(0x9c6262ff).into()),
                ("string.special.symbol".into(), rgba(0x5fac38ff).into()),
                ("punctuation.list_marker".into(), rgba(0xe8e4cfff).into()),
                ("emphasis".into(), rgba(0x6684e0ff).into()),
                ("keyword".into(), rgba(0xb854d4ff).into()),
                ("text.literal".into(), rgba(0xb65611ff).into()),
                ("number".into(), rgba(0xb65610ff).into()),
                ("preproc".into(), rgba(0xfefbecff).into()),
                ("embedded".into(), rgba(0xfefbecff).into()),
            ],
        },
        status_bar: rgba(0x45433bff).into(),
        title_bar: rgba(0x45433bff).into(),
        toolbar: rgba(0x20201dff).into(),
        tab_bar: rgba(0x262622ff).into(),
        editor: rgba(0x20201dff).into(),
        editor_subheader: rgba(0x262622ff).into(),
        editor_active_line: rgba(0x262622ff).into(),
        terminal: rgba(0x20201dff).into(),
        image_fallback_background: rgba(0x45433bff).into(),
        git_created: rgba(0x5fac39ff).into(),
        git_modified: rgba(0x6684e0ff).into(),
        git_deleted: rgba(0xd73837ff).into(),
        git_conflict: rgba(0xae9414ff).into(),
        git_ignored: rgba(0x8f8b77ff).into(),
        git_renamed: rgba(0xae9414ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x6684e0ff).into(),
                selection: rgba(0x6684e03d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5fac39ff).into(),
                selection: rgba(0x5fac393d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd43651ff).into(),
                selection: rgba(0xd436513d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb65611ff).into(),
                selection: rgba(0xb656113d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb854d3ff).into(),
                selection: rgba(0xb854d33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x20ad83ff).into(),
                selection: rgba(0x20ad833d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd73837ff).into(),
                selection: rgba(0xd738373d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xae9414ff).into(),
                selection: rgba(0xae94143d).into(),
            },
        ],
    }
}
