
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_savanna_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Savanna Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x505e55ff).into(),
        border_variant: rgba(0x505e55ff).into(),
        border_focused: rgba(0x1f3233ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x353f39ff).into(),
        surface: rgba(0x1f2621ff).into(),
        background: rgba(0x353f39ff).into(),
        filled_element: rgba(0x353f39ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x151e20ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x151e20ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xecf4eeff).into(),
        text_muted: rgba(0x859188ff).into(),
        text_placeholder: rgba(0xb16038ff).into(),
        text_disabled: rgba(0x6f7e74ff).into(),
        text_accent: rgba(0x468b8fff).into(),
        icon_muted: rgba(0x859188ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("function.method".into(), rgba(0x468b8fff).into()),
                ("title".into(), rgba(0xecf4eeff).into()),
                ("label".into(), rgba(0x468b8fff).into()),
                ("text.literal".into(), rgba(0x9f703bff).into()),
                ("boolean".into(), rgba(0x479962ff).into()),
                ("punctuation.list_marker".into(), rgba(0xdfe7e2ff).into()),
                ("string.escape".into(), rgba(0x87928aff).into()),
                ("string.special".into(), rgba(0x857368ff).into()),
                ("punctuation.delimiter".into(), rgba(0x87928aff).into()),
                ("tag".into(), rgba(0x468b8fff).into()),
                ("property".into(), rgba(0xb16038ff).into()),
                ("preproc".into(), rgba(0xecf4eeff).into()),
                ("primary".into(), rgba(0xdfe7e2ff).into()),
                ("link_uri".into(), rgba(0x479962ff).into()),
                ("comment".into(), rgba(0x5f6d64ff).into()),
                ("type".into(), rgba(0xa07d3aff).into()),
                ("hint".into(), rgba(0x607e76ff).into()),
                ("punctuation".into(), rgba(0xdfe7e2ff).into()),
                ("string.special.symbol".into(), rgba(0x479962ff).into()),
                ("emphasis.strong".into(), rgba(0x468b8fff).into()),
                ("keyword".into(), rgba(0x55859bff).into()),
                ("comment.doc".into(), rgba(0x87928aff).into()),
                ("punctuation.bracket".into(), rgba(0x87928aff).into()),
                ("constant".into(), rgba(0x479962ff).into()),
                ("link_text".into(), rgba(0x9f703bff).into()),
                ("number".into(), rgba(0x9f703bff).into()),
                ("function".into(), rgba(0x468b8fff).into()),
                ("variable".into(), rgba(0xdfe7e2ff).into()),
                ("emphasis".into(), rgba(0x468b8fff).into()),
                ("punctuation.special".into(), rgba(0x857368ff).into()),
                ("constructor".into(), rgba(0x468b8fff).into()),
                ("variable.special".into(), rgba(0x55859bff).into()),
                ("operator".into(), rgba(0x87928aff).into()),
                ("enum".into(), rgba(0x9f703bff).into()),
                ("string.regex".into(), rgba(0x1b9aa0ff).into()),
                ("attribute".into(), rgba(0x468b8fff).into()),
                ("predictive".into(), rgba(0x506d66ff).into()),
                ("string".into(), rgba(0x479962ff).into()),
                ("embedded".into(), rgba(0xecf4eeff).into()),
                ("variant".into(), rgba(0xa07d3aff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xa07d3aff).into(),
                ),
            ],
        },
        status_bar: rgba(0x353f39ff).into(),
        title_bar: rgba(0x353f39ff).into(),
        toolbar: rgba(0x171c19ff).into(),
        tab_bar: rgba(0x1f2621ff).into(),
        editor: rgba(0x171c19ff).into(),
        editor_subheader: rgba(0x1f2621ff).into(),
        editor_active_line: rgba(0x1f2621ff).into(),
        terminal: rgba(0x171c19ff).into(),
        image_fallback_background: rgba(0x353f39ff).into(),
        git_created: rgba(0x479962ff).into(),
        git_modified: rgba(0x468b8fff).into(),
        git_deleted: rgba(0xb16038ff).into(),
        git_conflict: rgba(0xa07d3aff).into(),
        git_ignored: rgba(0x6f7e74ff).into(),
        git_renamed: rgba(0xa07d3aff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x468b8fff).into(),
                selection: rgba(0x468b8f3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x479962ff).into(),
                selection: rgba(0x4799623d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x857368ff).into(),
                selection: rgba(0x8573683d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x9f703bff).into(),
                selection: rgba(0x9f703b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x55859bff).into(),
                selection: rgba(0x55859b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x1d9aa0ff).into(),
                selection: rgba(0x1d9aa03d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb16038ff).into(),
                selection: rgba(0xb160383d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa07d3aff).into(),
                selection: rgba(0xa07d3a3d).into(),
            },
        ],
    }
}
