use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_heath_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Heath Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0xad9dadff).into(),
        border_variant: rgba(0xad9dadff).into(),
        border_focused: rgba(0xcac7faff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xc6b8c6ff).into(),
        surface: rgba(0xe0d5e0ff).into(),
        background: rgba(0xc6b8c6ff).into(),
        filled_element: rgba(0xc6b8c6ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xe2dffcff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xe2dffcff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x1b181bff).into(),
        text_muted: rgba(0x6b5e6bff).into(),
        text_placeholder: rgba(0xca402bff).into(),
        text_disabled: rgba(0x857785ff).into(),
        text_accent: rgba(0x5169ebff).into(),
        icon_muted: rgba(0x6b5e6bff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("enum".into(), rgba(0xa65927ff).into()),
                ("string.escape".into(), rgba(0x695d69ff).into()),
                ("link_uri".into(), rgba(0x918b3bff).into()),
                ("function.method".into(), rgba(0x506aecff).into()),
                ("comment.doc".into(), rgba(0x695d69ff).into()),
                ("property".into(), rgba(0xca3f2aff).into()),
                ("string.special".into(), rgba(0xcc32ccff).into()),
                ("tag".into(), rgba(0x5169ebff).into()),
                ("embedded".into(), rgba(0x1b181bff).into()),
                ("primary".into(), rgba(0x292329ff).into()),
                ("punctuation".into(), rgba(0x292329ff).into()),
                ("punctuation.special".into(), rgba(0xcc32ccff).into()),
                ("type".into(), rgba(0xbb8a34ff).into()),
                ("number".into(), rgba(0xa65825ff).into()),
                ("function".into(), rgba(0x506aecff).into()),
                ("preproc".into(), rgba(0x1b181bff).into()),
                ("punctuation.bracket".into(), rgba(0x695d69ff).into()),
                ("punctuation.delimiter".into(), rgba(0x695d69ff).into()),
                ("variable".into(), rgba(0x292329ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xbb8a34ff).into(),
                ),
                ("label".into(), rgba(0x5169ebff).into()),
                ("constructor".into(), rgba(0x5169ebff).into()),
                ("emphasis.strong".into(), rgba(0x5169ebff).into()),
                ("constant".into(), rgba(0x918b3bff).into()),
                ("keyword".into(), rgba(0x7b58bfff).into()),
                ("variable.special".into(), rgba(0x7b58bfff).into()),
                ("variant".into(), rgba(0xbb8a34ff).into()),
                ("title".into(), rgba(0x1b181bff).into()),
                ("attribute".into(), rgba(0x5169ebff).into()),
                ("comment".into(), rgba(0x9e8f9eff).into()),
                ("string.special.symbol".into(), rgba(0x918b3aff).into()),
                ("predictive".into(), rgba(0xa487bfff).into()),
                ("link_text".into(), rgba(0xa65927ff).into()),
                ("punctuation.list_marker".into(), rgba(0x292329ff).into()),
                ("boolean".into(), rgba(0x918b3bff).into()),
                ("text.literal".into(), rgba(0xa65927ff).into()),
                ("emphasis".into(), rgba(0x5169ebff).into()),
                ("string.regex".into(), rgba(0x149393ff).into()),
                ("hint".into(), rgba(0x8c70a6ff).into()),
                ("string".into(), rgba(0x918b3aff).into()),
                ("operator".into(), rgba(0x695d69ff).into()),
            ],
        },
        status_bar: rgba(0xc6b8c6ff).into(),
        title_bar: rgba(0xc6b8c6ff).into(),
        toolbar: rgba(0xf7f3f7ff).into(),
        tab_bar: rgba(0xe0d5e0ff).into(),
        editor: rgba(0xf7f3f7ff).into(),
        editor_subheader: rgba(0xe0d5e0ff).into(),
        editor_active_line: rgba(0xe0d5e0ff).into(),
        terminal: rgba(0xf7f3f7ff).into(),
        image_fallback_background: rgba(0xc6b8c6ff).into(),
        git_created: rgba(0x918b3bff).into(),
        git_modified: rgba(0x5169ebff).into(),
        git_deleted: rgba(0xca402bff).into(),
        git_conflict: rgba(0xbb8a35ff).into(),
        git_ignored: rgba(0x857785ff).into(),
        git_renamed: rgba(0xbb8a35ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x5169ebff).into(),
                selection: rgba(0x5169eb3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x918b3bff).into(),
                selection: rgba(0x918b3b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xcc34ccff).into(),
                selection: rgba(0xcc34cc3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa65927ff).into(),
                selection: rgba(0xa659273d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x7a5ac0ff).into(),
                selection: rgba(0x7a5ac03d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x189393ff).into(),
                selection: rgba(0x1893933d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xca402bff).into(),
                selection: rgba(0xca402b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xbb8a35ff).into(),
                selection: rgba(0xbb8a353d).into(),
            },
        ],
    }
}
