use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_forest_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Forest Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0xaaa3a1ff).into(),
        border_variant: rgba(0xaaa3a1ff).into(),
        border_focused: rgba(0xc6cef7ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xccc7c5ff).into(),
        surface: rgba(0xe9e6e4ff).into(),
        background: rgba(0xccc7c5ff).into(),
        filled_element: rgba(0xccc7c5ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xdfe3fbff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xdfe3fbff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x1b1918ff).into(),
        text_muted: rgba(0x6a6360ff).into(),
        text_placeholder: rgba(0xf22e40ff).into(),
        text_disabled: rgba(0x837b78ff).into(),
        text_accent: rgba(0x407ee6ff).into(),
        icon_muted: rgba(0x6a6360ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("punctuation.special".into(), rgba(0xc33ff3ff).into()),
                ("text.literal".into(), rgba(0xdf5421ff).into()),
                ("string.escape".into(), rgba(0x68615eff).into()),
                ("string.regex".into(), rgba(0x3c96b8ff).into()),
                ("number".into(), rgba(0xdf521fff).into()),
                ("preproc".into(), rgba(0x1b1918ff).into()),
                ("keyword".into(), rgba(0x6666eaff).into()),
                ("variable.special".into(), rgba(0x6666eaff).into()),
                ("punctuation.delimiter".into(), rgba(0x68615eff).into()),
                ("emphasis.strong".into(), rgba(0x407ee6ff).into()),
                ("boolean".into(), rgba(0x7a9728ff).into()),
                ("variant".into(), rgba(0xc38417ff).into()),
                ("predictive".into(), rgba(0xbe899eff).into()),
                ("tag".into(), rgba(0x407ee6ff).into()),
                ("property".into(), rgba(0xf22c40ff).into()),
                ("enum".into(), rgba(0xdf5421ff).into()),
                ("attribute".into(), rgba(0x407ee6ff).into()),
                ("function.method".into(), rgba(0x3f7ee7ff).into()),
                ("function".into(), rgba(0x3f7ee7ff).into()),
                ("emphasis".into(), rgba(0x407ee6ff).into()),
                ("primary".into(), rgba(0x2c2421ff).into()),
                ("variable".into(), rgba(0x2c2421ff).into()),
                ("constant".into(), rgba(0x7a9728ff).into()),
                ("title".into(), rgba(0x1b1918ff).into()),
                ("comment.doc".into(), rgba(0x68615eff).into()),
                ("constructor".into(), rgba(0x407ee6ff).into()),
                ("type".into(), rgba(0xc38417ff).into()),
                ("punctuation.list_marker".into(), rgba(0x2c2421ff).into()),
                ("punctuation".into(), rgba(0x2c2421ff).into()),
                ("string".into(), rgba(0x7a9725ff).into()),
                ("label".into(), rgba(0x407ee6ff).into()),
                ("string.special".into(), rgba(0xc33ff3ff).into()),
                ("embedded".into(), rgba(0x1b1918ff).into()),
                ("link_text".into(), rgba(0xdf5421ff).into()),
                ("punctuation.bracket".into(), rgba(0x68615eff).into()),
                ("comment".into(), rgba(0x9c9491ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xc38417ff).into(),
                ),
                ("link_uri".into(), rgba(0x7a9728ff).into()),
                ("operator".into(), rgba(0x68615eff).into()),
                ("hint".into(), rgba(0xa67287ff).into()),
                ("string.special.symbol".into(), rgba(0x7a9725ff).into()),
            ],
        },
        status_bar: rgba(0xccc7c5ff).into(),
        title_bar: rgba(0xccc7c5ff).into(),
        toolbar: rgba(0xf0eeedff).into(),
        tab_bar: rgba(0xe9e6e4ff).into(),
        editor: rgba(0xf0eeedff).into(),
        editor_subheader: rgba(0xe9e6e4ff).into(),
        editor_active_line: rgba(0xe9e6e4ff).into(),
        terminal: rgba(0xf0eeedff).into(),
        image_fallback_background: rgba(0xccc7c5ff).into(),
        git_created: rgba(0x7a9728ff).into(),
        git_modified: rgba(0x407ee6ff).into(),
        git_deleted: rgba(0xf22e40ff).into(),
        git_conflict: rgba(0xc38419ff).into(),
        git_ignored: rgba(0x837b78ff).into(),
        git_renamed: rgba(0xc38419ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x407ee6ff).into(),
                selection: rgba(0x407ee63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x7a9728ff).into(),
                selection: rgba(0x7a97283d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xc340f2ff).into(),
                selection: rgba(0xc340f23d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xdf5421ff).into(),
                selection: rgba(0xdf54213d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x6765e9ff).into(),
                selection: rgba(0x6765e93d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x3e96b8ff).into(),
                selection: rgba(0x3e96b83d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf22e40ff).into(),
                selection: rgba(0xf22e403d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xc38419ff).into(),
                selection: rgba(0xc384193d).into(),
            },
        ],
    }
}
