use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_lakeside_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Lakeside Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x4f6a78ff).into(),
        border_variant: rgba(0x4f6a78ff).into(),
        border_focused: rgba(0x1a2f3cff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x33444dff).into(),
        surface: rgba(0x1c2529ff).into(),
        background: rgba(0x33444dff).into(),
        filled_element: rgba(0x33444dff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x121c24ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x121c24ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xebf8ffff).into(),
        text_muted: rgba(0x7c9fb3ff).into(),
        text_placeholder: rgba(0xd22e72ff).into(),
        text_disabled: rgba(0x688c9dff).into(),
        text_accent: rgba(0x267eadff).into(),
        icon_muted: rgba(0x7c9fb3ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("punctuation.bracket".into(), rgba(0x7ea2b4ff).into()),
                ("punctuation.special".into(), rgba(0xb72cd2ff).into()),
                ("property".into(), rgba(0xd22c72ff).into()),
                ("function.method".into(), rgba(0x247eadff).into()),
                ("comment".into(), rgba(0x5a7b8cff).into()),
                ("constructor".into(), rgba(0x267eadff).into()),
                ("boolean".into(), rgba(0x558c3aff).into()),
                ("hint".into(), rgba(0x52809aff).into()),
                ("label".into(), rgba(0x267eadff).into()),
                ("string.special".into(), rgba(0xb72cd2ff).into()),
                ("title".into(), rgba(0xebf8ffff).into()),
                ("punctuation.list_marker".into(), rgba(0xc1e4f6ff).into()),
                ("emphasis.strong".into(), rgba(0x267eadff).into()),
                ("enum".into(), rgba(0x935b25ff).into()),
                ("type".into(), rgba(0x8a8a0eff).into()),
                ("tag".into(), rgba(0x267eadff).into()),
                ("punctuation.delimiter".into(), rgba(0x7ea2b4ff).into()),
                ("primary".into(), rgba(0xc1e4f6ff).into()),
                ("link_text".into(), rgba(0x935b25ff).into()),
                ("variable".into(), rgba(0xc1e4f6ff).into()),
                ("variable.special".into(), rgba(0x6a6ab7ff).into()),
                ("string.special.symbol".into(), rgba(0x558c3aff).into()),
                ("link_uri".into(), rgba(0x558c3aff).into()),
                ("function".into(), rgba(0x247eadff).into()),
                ("predictive".into(), rgba(0x426f88ff).into()),
                ("punctuation".into(), rgba(0xc1e4f6ff).into()),
                ("string.escape".into(), rgba(0x7ea2b4ff).into()),
                ("keyword".into(), rgba(0x6a6ab7ff).into()),
                ("attribute".into(), rgba(0x267eadff).into()),
                ("string.regex".into(), rgba(0x2c8f6eff).into()),
                ("embedded".into(), rgba(0xebf8ffff).into()),
                ("emphasis".into(), rgba(0x267eadff).into()),
                ("string".into(), rgba(0x558c3aff).into()),
                ("operator".into(), rgba(0x7ea2b4ff).into()),
                ("text.literal".into(), rgba(0x935b25ff).into()),
                ("constant".into(), rgba(0x558c3aff).into()),
                ("comment.doc".into(), rgba(0x7ea2b4ff).into()),
                ("number".into(), rgba(0x935c24ff).into()),
                ("preproc".into(), rgba(0xebf8ffff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0x8a8a0eff).into(),
                ),
                ("variant".into(), rgba(0x8a8a0eff).into()),
            ],
        },
        status_bar: rgba(0x33444dff).into(),
        title_bar: rgba(0x33444dff).into(),
        toolbar: rgba(0x161b1dff).into(),
        tab_bar: rgba(0x1c2529ff).into(),
        editor: rgba(0x161b1dff).into(),
        editor_subheader: rgba(0x1c2529ff).into(),
        editor_active_line: rgba(0x1c2529ff).into(),
        terminal: rgba(0x161b1dff).into(),
        image_fallback_background: rgba(0x33444dff).into(),
        git_created: rgba(0x558c3aff).into(),
        git_modified: rgba(0x267eadff).into(),
        git_deleted: rgba(0xd22e72ff).into(),
        git_conflict: rgba(0x8a8a10ff).into(),
        git_ignored: rgba(0x688c9dff).into(),
        git_renamed: rgba(0x8a8a10ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x267eadff).into(),
                selection: rgba(0x267ead3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x558c3aff).into(),
                selection: rgba(0x558c3a3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb72ed2ff).into(),
                selection: rgba(0xb72ed23d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x935b25ff).into(),
                selection: rgba(0x935b253d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x6a6ab7ff).into(),
                selection: rgba(0x6a6ab73d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x2d8f6fff).into(),
                selection: rgba(0x2d8f6f3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd22e72ff).into(),
                selection: rgba(0xd22e723d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x8a8a10ff).into(),
                selection: rgba(0x8a8a103d).into(),
            },
        ],
    }
}
