use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_estuary_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Estuary Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x5d5c4cff).into(),
        border_variant: rgba(0x5d5c4cff).into(),
        border_focused: rgba(0x1c3927ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x424136ff).into(),
        surface: rgba(0x2c2b23ff).into(),
        background: rgba(0x424136ff).into(),
        filled_element: rgba(0x424136ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x142319ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x142319ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf4f3ecff).into(),
        text_muted: rgba(0x91907fff).into(),
        text_placeholder: rgba(0xba6136ff).into(),
        text_disabled: rgba(0x7d7c6aff).into(),
        text_accent: rgba(0x36a165ff).into(),
        icon_muted: rgba(0x91907fff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("string.special.symbol".into(), rgba(0x7c9725ff).into()),
                ("comment".into(), rgba(0x6c6b5aff).into()),
                ("operator".into(), rgba(0x929181ff).into()),
                ("punctuation.delimiter".into(), rgba(0x929181ff).into()),
                ("keyword".into(), rgba(0x5f9182ff).into()),
                ("punctuation.special".into(), rgba(0x9d6b7bff).into()),
                ("preproc".into(), rgba(0xf4f3ecff).into()),
                ("title".into(), rgba(0xf4f3ecff).into()),
                ("string.escape".into(), rgba(0x929181ff).into()),
                ("boolean".into(), rgba(0x7d9726ff).into()),
                ("punctuation.bracket".into(), rgba(0x929181ff).into()),
                ("emphasis.strong".into(), rgba(0x36a165ff).into()),
                ("string".into(), rgba(0x7c9725ff).into()),
                ("constant".into(), rgba(0x7d9726ff).into()),
                ("link_text".into(), rgba(0xae7214ff).into()),
                ("tag".into(), rgba(0x36a165ff).into()),
                ("hint".into(), rgba(0x6f815aff).into()),
                ("punctuation".into(), rgba(0xe7e6dfff).into()),
                ("string.regex".into(), rgba(0x5a9d47ff).into()),
                ("variant".into(), rgba(0xa5980cff).into()),
                ("type".into(), rgba(0xa5980cff).into()),
                ("attribute".into(), rgba(0x36a165ff).into()),
                ("emphasis".into(), rgba(0x36a165ff).into()),
                ("enum".into(), rgba(0xae7214ff).into()),
                ("number".into(), rgba(0xae7312ff).into()),
                ("property".into(), rgba(0xba6135ff).into()),
                ("predictive".into(), rgba(0x5f724cff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xa5980cff).into(),
                ),
                ("link_uri".into(), rgba(0x7d9726ff).into()),
                ("variable.special".into(), rgba(0x5f9182ff).into()),
                ("text.literal".into(), rgba(0xae7214ff).into()),
                ("label".into(), rgba(0x36a165ff).into()),
                ("primary".into(), rgba(0xe7e6dfff).into()),
                ("variable".into(), rgba(0xe7e6dfff).into()),
                ("embedded".into(), rgba(0xf4f3ecff).into()),
                ("function.method".into(), rgba(0x35a166ff).into()),
                ("comment.doc".into(), rgba(0x929181ff).into()),
                ("string.special".into(), rgba(0x9d6b7bff).into()),
                ("constructor".into(), rgba(0x36a165ff).into()),
                ("punctuation.list_marker".into(), rgba(0xe7e6dfff).into()),
                ("function".into(), rgba(0x35a166ff).into()),
            ],
        },
        status_bar: rgba(0x424136ff).into(),
        title_bar: rgba(0x424136ff).into(),
        toolbar: rgba(0x22221bff).into(),
        tab_bar: rgba(0x2c2b23ff).into(),
        editor: rgba(0x22221bff).into(),
        editor_subheader: rgba(0x2c2b23ff).into(),
        editor_active_line: rgba(0x2c2b23ff).into(),
        terminal: rgba(0x22221bff).into(),
        image_fallback_background: rgba(0x424136ff).into(),
        git_created: rgba(0x7d9726ff).into(),
        git_modified: rgba(0x36a165ff).into(),
        git_deleted: rgba(0xba6136ff).into(),
        git_conflict: rgba(0xa5980fff).into(),
        git_ignored: rgba(0x7d7c6aff).into(),
        git_renamed: rgba(0xa5980fff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x36a165ff).into(),
                selection: rgba(0x36a1653d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x7d9726ff).into(),
                selection: rgba(0x7d97263d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x9d6b7bff).into(),
                selection: rgba(0x9d6b7b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xae7214ff).into(),
                selection: rgba(0xae72143d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5f9182ff).into(),
                selection: rgba(0x5f91823d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5a9d47ff).into(),
                selection: rgba(0x5a9d473d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xba6136ff).into(),
                selection: rgba(0xba61363d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa5980fff).into(),
                selection: rgba(0xa5980f3d).into(),
            },
        ],
    }
}
