
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_heath_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Heath Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x675b67ff).into(),
        border_variant: rgba(0x675b67ff).into(),
        border_focused: rgba(0x192961ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x433a43ff).into(),
        surface: rgba(0x252025ff).into(),
        background: rgba(0x433a43ff).into(),
        filled_element: rgba(0x433a43ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x0d1a43ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x0d1a43ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf7f3f7ff).into(),
        text_muted: rgba(0xa899a8ff).into(),
        text_placeholder: rgba(0xca3f2bff).into(),
        text_disabled: rgba(0x908190ff).into(),
        text_accent: rgba(0x5169ebff).into(),
        icon_muted: rgba(0xa899a8ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("preproc".into(), rgba(0xf7f3f7ff).into()),
                ("number".into(), rgba(0xa65825ff).into()),
                ("boolean".into(), rgba(0x918b3aff).into()),
                ("embedded".into(), rgba(0xf7f3f7ff).into()),
                ("variable.special".into(), rgba(0x7b58bfff).into()),
                ("operator".into(), rgba(0xab9babff).into()),
                ("punctuation.delimiter".into(), rgba(0xab9babff).into()),
                ("primary".into(), rgba(0xd8cad8ff).into()),
                ("punctuation.bracket".into(), rgba(0xab9babff).into()),
                ("comment.doc".into(), rgba(0xab9babff).into()),
                ("variant".into(), rgba(0xbb8a34ff).into()),
                ("attribute".into(), rgba(0x5169ebff).into()),
                ("property".into(), rgba(0xca3f2aff).into()),
                ("keyword".into(), rgba(0x7b58bfff).into()),
                ("hint".into(), rgba(0x8d70a8ff).into()),
                ("string.special.symbol".into(), rgba(0x918b3aff).into()),
                ("punctuation.special".into(), rgba(0xcc32ccff).into()),
                ("link_uri".into(), rgba(0x918b3aff).into()),
                ("link_text".into(), rgba(0xa65827ff).into()),
                ("enum".into(), rgba(0xa65827ff).into()),
                ("function".into(), rgba(0x506aecff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xbb8a34ff).into(),
                ),
                ("constant".into(), rgba(0x918b3aff).into()),
                ("title".into(), rgba(0xf7f3f7ff).into()),
                ("string.regex".into(), rgba(0x149393ff).into()),
                ("variable".into(), rgba(0xd8cad8ff).into()),
                ("comment".into(), rgba(0x776977ff).into()),
                ("predictive".into(), rgba(0x75588fff).into()),
                ("function.method".into(), rgba(0x506aecff).into()),
                ("type".into(), rgba(0xbb8a34ff).into()),
                ("punctuation".into(), rgba(0xd8cad8ff).into()),
                ("emphasis".into(), rgba(0x5169ebff).into()),
                ("emphasis.strong".into(), rgba(0x5169ebff).into()),
                ("tag".into(), rgba(0x5169ebff).into()),
                ("text.literal".into(), rgba(0xa65827ff).into()),
                ("string".into(), rgba(0x918b3aff).into()),
                ("string.escape".into(), rgba(0xab9babff).into()),
                ("constructor".into(), rgba(0x5169ebff).into()),
                ("label".into(), rgba(0x5169ebff).into()),
                ("punctuation.list_marker".into(), rgba(0xd8cad8ff).into()),
                ("string.special".into(), rgba(0xcc32ccff).into()),
            ],
        },
        status_bar: rgba(0x433a43ff).into(),
        title_bar: rgba(0x433a43ff).into(),
        toolbar: rgba(0x1b181bff).into(),
        tab_bar: rgba(0x252025ff).into(),
        editor: rgba(0x1b181bff).into(),
        editor_subheader: rgba(0x252025ff).into(),
        editor_active_line: rgba(0x252025ff).into(),
        terminal: rgba(0x1b181bff).into(),
        image_fallback_background: rgba(0x433a43ff).into(),
        git_created: rgba(0x918b3aff).into(),
        git_modified: rgba(0x5169ebff).into(),
        git_deleted: rgba(0xca3f2bff).into(),
        git_conflict: rgba(0xbb8a35ff).into(),
        git_ignored: rgba(0x908190ff).into(),
        git_renamed: rgba(0xbb8a35ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x5169ebff).into(),
                selection: rgba(0x5169eb3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x918b3aff).into(),
                selection: rgba(0x918b3a3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xcc34ccff).into(),
                selection: rgba(0xcc34cc3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa65827ff).into(),
                selection: rgba(0xa658273d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x7b58bfff).into(),
                selection: rgba(0x7b58bf3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x189393ff).into(),
                selection: rgba(0x1893933d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xca3f2bff).into(),
                selection: rgba(0xca3f2b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xbb8a35ff).into(),
                selection: rgba(0xbb8a353d).into(),
            },
        ],
    }
}
