
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_seaside_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Seaside Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x8ea88eff).into(),
        border_variant: rgba(0x8ea88eff).into(),
        border_focused: rgba(0xc9c4fdff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xb4ceb4ff).into(),
        surface: rgba(0xdaeedaff).into(),
        background: rgba(0xb4ceb4ff).into(),
        filled_element: rgba(0xb4ceb4ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xe1ddfeff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xe1ddfeff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x131513ff).into(),
        text_muted: rgba(0x5f705fff).into(),
        text_placeholder: rgba(0xe61c3dff).into(),
        text_disabled: rgba(0x718771ff).into(),
        text_accent: rgba(0x3e61f4ff).into(),
        icon_muted: rgba(0x5f705fff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("string.escape".into(), rgba(0x5e6e5eff).into()),
                ("boolean".into(), rgba(0x2aa32aff).into()),
                ("string.special".into(), rgba(0xe618c3ff).into()),
                ("comment".into(), rgba(0x809980ff).into()),
                ("number".into(), rgba(0x87711cff).into()),
                ("comment.doc".into(), rgba(0x5e6e5eff).into()),
                ("tag".into(), rgba(0x3e61f4ff).into()),
                ("string.special.symbol".into(), rgba(0x28a328ff).into()),
                ("primary".into(), rgba(0x242924ff).into()),
                ("string".into(), rgba(0x28a328ff).into()),
                ("enum".into(), rgba(0x87711fff).into()),
                ("operator".into(), rgba(0x5e6e5eff).into()),
                ("string.regex".into(), rgba(0x1899b3ff).into()),
                ("keyword".into(), rgba(0xac2aeeff).into()),
                ("emphasis".into(), rgba(0x3e61f4ff).into()),
                ("link_uri".into(), rgba(0x2aa32aff).into()),
                ("constant".into(), rgba(0x2aa32aff).into()),
                ("constructor".into(), rgba(0x3e61f4ff).into()),
                ("link_text".into(), rgba(0x87711fff).into()),
                ("emphasis.strong".into(), rgba(0x3e61f4ff).into()),
                ("punctuation.list_marker".into(), rgba(0x242924ff).into()),
                ("punctuation.delimiter".into(), rgba(0x5e6e5eff).into()),
                ("punctuation.special".into(), rgba(0xe618c3ff).into()),
                ("variant".into(), rgba(0x98981bff).into()),
                ("predictive".into(), rgba(0x00a2b5ff).into()),
                ("attribute".into(), rgba(0x3e61f4ff).into()),
                ("preproc".into(), rgba(0x131513ff).into()),
                ("embedded".into(), rgba(0x131513ff).into()),
                ("punctuation".into(), rgba(0x242924ff).into()),
                ("label".into(), rgba(0x3e61f4ff).into()),
                ("function.method".into(), rgba(0x3d62f5ff).into()),
                ("property".into(), rgba(0xe6183bff).into()),
                ("title".into(), rgba(0x131513ff).into()),
                ("variable".into(), rgba(0x242924ff).into()),
                ("function".into(), rgba(0x3d62f5ff).into()),
                ("variable.special".into(), rgba(0xac2aeeff).into()),
                ("type".into(), rgba(0x98981bff).into()),
                ("text.literal".into(), rgba(0x87711fff).into()),
                ("hint".into(), rgba(0x008fa1ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0x98981bff).into(),
                ),
                ("punctuation.bracket".into(), rgba(0x5e6e5eff).into()),
            ],
        },
        status_bar: rgba(0xb4ceb4ff).into(),
        title_bar: rgba(0xb4ceb4ff).into(),
        toolbar: rgba(0xf3faf3ff).into(),
        tab_bar: rgba(0xdaeedaff).into(),
        editor: rgba(0xf3faf3ff).into(),
        editor_subheader: rgba(0xdaeedaff).into(),
        editor_active_line: rgba(0xdaeedaff).into(),
        terminal: rgba(0xf3faf3ff).into(),
        image_fallback_background: rgba(0xb4ceb4ff).into(),
        git_created: rgba(0x2aa32aff).into(),
        git_modified: rgba(0x3e61f4ff).into(),
        git_deleted: rgba(0xe61c3dff).into(),
        git_conflict: rgba(0x98981cff).into(),
        git_ignored: rgba(0x718771ff).into(),
        git_renamed: rgba(0x98981cff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x3e61f4ff).into(),
                selection: rgba(0x3e61f43d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x2aa32aff).into(),
                selection: rgba(0x2aa32a3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xe61cc2ff).into(),
                selection: rgba(0xe61cc23d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x87711fff).into(),
                selection: rgba(0x87711f3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xac2dedff).into(),
                selection: rgba(0xac2ded3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x1c99b3ff).into(),
                selection: rgba(0x1c99b33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xe61c3dff).into(),
                selection: rgba(0xe61c3d3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x98981cff).into(),
                selection: rgba(0x98981c3d).into(),
            },
        ],
    }
}
