
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_savanna_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Savanna Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x8b968eff).into(),
        border_variant: rgba(0x8b968eff).into(),
        border_focused: rgba(0xbed4d6ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xbcc5bfff).into(),
        surface: rgba(0xe3ebe6ff).into(),
        background: rgba(0xbcc5bfff).into(),
        filled_element: rgba(0xbcc5bfff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xdae7e8ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xdae7e8ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x171c19ff).into(),
        text_muted: rgba(0x546259ff).into(),
        text_placeholder: rgba(0xb16139ff).into(),
        text_disabled: rgba(0x68766dff).into(),
        text_accent: rgba(0x488b90ff).into(),
        icon_muted: rgba(0x546259ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("text.literal".into(), rgba(0x9f713cff).into()),
                ("string".into(), rgba(0x479962ff).into()),
                ("punctuation.special".into(), rgba(0x857368ff).into()),
                ("type".into(), rgba(0xa07d3aff).into()),
                ("enum".into(), rgba(0x9f713cff).into()),
                ("title".into(), rgba(0x171c19ff).into()),
                ("comment".into(), rgba(0x77877cff).into()),
                ("predictive".into(), rgba(0x75958bff).into()),
                ("punctuation.list_marker".into(), rgba(0x232a25ff).into()),
                ("string.special.symbol".into(), rgba(0x479962ff).into()),
                ("constructor".into(), rgba(0x488b90ff).into()),
                ("variable".into(), rgba(0x232a25ff).into()),
                ("label".into(), rgba(0x488b90ff).into()),
                ("attribute".into(), rgba(0x488b90ff).into()),
                ("constant".into(), rgba(0x499963ff).into()),
                ("function".into(), rgba(0x468b8fff).into()),
                ("variable.special".into(), rgba(0x55859bff).into()),
                ("keyword".into(), rgba(0x55859bff).into()),
                ("number".into(), rgba(0x9f703bff).into()),
                ("boolean".into(), rgba(0x499963ff).into()),
                ("embedded".into(), rgba(0x171c19ff).into()),
                ("string.special".into(), rgba(0x857368ff).into()),
                ("emphasis.strong".into(), rgba(0x488b90ff).into()),
                ("string.regex".into(), rgba(0x1b9aa0ff).into()),
                ("hint".into(), rgba(0x66847cff).into()),
                ("preproc".into(), rgba(0x171c19ff).into()),
                ("link_uri".into(), rgba(0x499963ff).into()),
                ("variant".into(), rgba(0xa07d3aff).into()),
                ("function.method".into(), rgba(0x468b8fff).into()),
                ("punctuation.bracket".into(), rgba(0x526057ff).into()),
                ("punctuation.delimiter".into(), rgba(0x526057ff).into()),
                ("punctuation".into(), rgba(0x232a25ff).into()),
                ("primary".into(), rgba(0x232a25ff).into()),
                ("string.escape".into(), rgba(0x526057ff).into()),
                ("property".into(), rgba(0xb16038ff).into()),
                ("operator".into(), rgba(0x526057ff).into()),
                ("comment.doc".into(), rgba(0x526057ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xa07d3aff).into(),
                ),
                ("link_text".into(), rgba(0x9f713cff).into()),
                ("tag".into(), rgba(0x488b90ff).into()),
                ("emphasis".into(), rgba(0x488b90ff).into()),
            ],
        },
        status_bar: rgba(0xbcc5bfff).into(),
        title_bar: rgba(0xbcc5bfff).into(),
        toolbar: rgba(0xecf4eeff).into(),
        tab_bar: rgba(0xe3ebe6ff).into(),
        editor: rgba(0xecf4eeff).into(),
        editor_subheader: rgba(0xe3ebe6ff).into(),
        editor_active_line: rgba(0xe3ebe6ff).into(),
        terminal: rgba(0xecf4eeff).into(),
        image_fallback_background: rgba(0xbcc5bfff).into(),
        git_created: rgba(0x499963ff).into(),
        git_modified: rgba(0x488b90ff).into(),
        git_deleted: rgba(0xb16139ff).into(),
        git_conflict: rgba(0xa07d3bff).into(),
        git_ignored: rgba(0x68766dff).into(),
        git_renamed: rgba(0xa07d3bff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x488b90ff).into(),
                selection: rgba(0x488b903d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x499963ff).into(),
                selection: rgba(0x4999633d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x857368ff).into(),
                selection: rgba(0x8573683d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x9f713cff).into(),
                selection: rgba(0x9f713c3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x55859bff).into(),
                selection: rgba(0x55859b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x1e9aa0ff).into(),
                selection: rgba(0x1e9aa03d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb16139ff).into(),
                selection: rgba(0xb161393d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa07d3bff).into(),
                selection: rgba(0xa07d3b3d).into(),
            },
        ],
    }
}
