
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_plateau_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Plateau Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x564e4eff).into(),
        border_variant: rgba(0x564e4eff).into(),
        border_focused: rgba(0x2c2b45ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x3b3535ff).into(),
        surface: rgba(0x252020ff).into(),
        background: rgba(0x3b3535ff).into(),
        filled_element: rgba(0x3b3535ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x1c1b29ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x1c1b29ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf4ececff).into(),
        text_muted: rgba(0x898383ff).into(),
        text_placeholder: rgba(0xca4848ff).into(),
        text_disabled: rgba(0x756e6eff).into(),
        text_accent: rgba(0x7272caff).into(),
        icon_muted: rgba(0x898383ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("variant".into(), rgba(0xa06d3aff).into()),
                ("label".into(), rgba(0x7272caff).into()),
                ("punctuation.delimiter".into(), rgba(0x8a8585ff).into()),
                ("string.regex".into(), rgba(0x5485b6ff).into()),
                ("variable.special".into(), rgba(0x8464c4ff).into()),
                ("string".into(), rgba(0x4b8b8bff).into()),
                ("property".into(), rgba(0xca4848ff).into()),
                ("hint".into(), rgba(0x8a647aff).into()),
                ("comment.doc".into(), rgba(0x8a8585ff).into()),
                ("attribute".into(), rgba(0x7272caff).into()),
                ("tag".into(), rgba(0x7272caff).into()),
                ("constructor".into(), rgba(0x7272caff).into()),
                ("boolean".into(), rgba(0x4b8b8bff).into()),
                ("preproc".into(), rgba(0xf4ececff).into()),
                ("constant".into(), rgba(0x4b8b8bff).into()),
                ("punctuation.special".into(), rgba(0xbd5187ff).into()),
                ("function.method".into(), rgba(0x7272caff).into()),
                ("comment".into(), rgba(0x655d5dff).into()),
                ("variable".into(), rgba(0xe7dfdfff).into()),
                ("primary".into(), rgba(0xe7dfdfff).into()),
                ("title".into(), rgba(0xf4ececff).into()),
                ("emphasis".into(), rgba(0x7272caff).into()),
                ("emphasis.strong".into(), rgba(0x7272caff).into()),
                ("function".into(), rgba(0x7272caff).into()),
                ("type".into(), rgba(0xa06d3aff).into()),
                ("operator".into(), rgba(0x8a8585ff).into()),
                ("embedded".into(), rgba(0xf4ececff).into()),
                ("predictive".into(), rgba(0x795369ff).into()),
                ("punctuation".into(), rgba(0xe7dfdfff).into()),
                ("link_text".into(), rgba(0xb4593bff).into()),
                ("enum".into(), rgba(0xb4593bff).into()),
                ("string.special".into(), rgba(0xbd5187ff).into()),
                ("text.literal".into(), rgba(0xb4593bff).into()),
                ("string.escape".into(), rgba(0x8a8585ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xa06d3aff).into(),
                ),
                ("keyword".into(), rgba(0x8464c4ff).into()),
                ("link_uri".into(), rgba(0x4b8b8bff).into()),
                ("number".into(), rgba(0xb4593bff).into()),
                ("punctuation.bracket".into(), rgba(0x8a8585ff).into()),
                ("string.special.symbol".into(), rgba(0x4b8b8bff).into()),
                ("punctuation.list_marker".into(), rgba(0xe7dfdfff).into()),
            ],
        },
        status_bar: rgba(0x3b3535ff).into(),
        title_bar: rgba(0x3b3535ff).into(),
        toolbar: rgba(0x1b1818ff).into(),
        tab_bar: rgba(0x252020ff).into(),
        editor: rgba(0x1b1818ff).into(),
        editor_subheader: rgba(0x252020ff).into(),
        editor_active_line: rgba(0x252020ff).into(),
        terminal: rgba(0x1b1818ff).into(),
        image_fallback_background: rgba(0x3b3535ff).into(),
        git_created: rgba(0x4b8b8bff).into(),
        git_modified: rgba(0x7272caff).into(),
        git_deleted: rgba(0xca4848ff).into(),
        git_conflict: rgba(0xa06d3aff).into(),
        git_ignored: rgba(0x756e6eff).into(),
        git_renamed: rgba(0xa06d3aff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x7272caff).into(),
                selection: rgba(0x7272ca3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x4b8b8bff).into(),
                selection: rgba(0x4b8b8b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xbd5187ff).into(),
                selection: rgba(0xbd51873d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb4593bff).into(),
                selection: rgba(0xb4593b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x8464c4ff).into(),
                selection: rgba(0x8464c43d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5485b6ff).into(),
                selection: rgba(0x5485b63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xca4848ff).into(),
                selection: rgba(0xca48483d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa06d3aff).into(),
                selection: rgba(0xa06d3a3d).into(),
            },
        ],
    }
}
