use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_seaside_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Seaside Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x5c6c5cff).into(),
        border_variant: rgba(0x5c6c5cff).into(),
        border_focused: rgba(0x102667ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x3b453bff).into(),
        surface: rgba(0x1f231fff).into(),
        background: rgba(0x3b453bff).into(),
        filled_element: rgba(0x3b453bff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x051949ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x051949ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf3faf3ff).into(),
        text_muted: rgba(0x8ba48bff).into(),
        text_placeholder: rgba(0xe61c3bff).into(),
        text_disabled: rgba(0x778f77ff).into(),
        text_accent: rgba(0x3e62f4ff).into(),
        icon_muted: rgba(0x8ba48bff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("comment".into(), rgba(0x687d68ff).into()),
                ("predictive".into(), rgba(0x00788bff).into()),
                ("string.special".into(), rgba(0xe618c3ff).into()),
                ("string.regex".into(), rgba(0x1899b3ff).into()),
                ("boolean".into(), rgba(0x2aa329ff).into()),
                ("string".into(), rgba(0x28a328ff).into()),
                ("operator".into(), rgba(0x8ca68cff).into()),
                ("primary".into(), rgba(0xcfe8cfff).into()),
                ("number".into(), rgba(0x87711cff).into()),
                ("punctuation.special".into(), rgba(0xe618c3ff).into()),
                ("link_text".into(), rgba(0x87711dff).into()),
                ("title".into(), rgba(0xf3faf3ff).into()),
                ("comment.doc".into(), rgba(0x8ca68cff).into()),
                ("label".into(), rgba(0x3e62f4ff).into()),
                ("preproc".into(), rgba(0xf3faf3ff).into()),
                ("punctuation.bracket".into(), rgba(0x8ca68cff).into()),
                ("punctuation.delimiter".into(), rgba(0x8ca68cff).into()),
                ("function.method".into(), rgba(0x3d62f5ff).into()),
                ("tag".into(), rgba(0x3e62f4ff).into()),
                ("embedded".into(), rgba(0xf3faf3ff).into()),
                ("text.literal".into(), rgba(0x87711dff).into()),
                ("punctuation".into(), rgba(0xcfe8cfff).into()),
                ("string.special.symbol".into(), rgba(0x28a328ff).into()),
                ("link_uri".into(), rgba(0x2aa329ff).into()),
                ("keyword".into(), rgba(0xac2aeeff).into()),
                ("function".into(), rgba(0x3d62f5ff).into()),
                ("string.escape".into(), rgba(0x8ca68cff).into()),
                ("variant".into(), rgba(0x98981bff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0x98981bff).into(),
                ),
                ("constructor".into(), rgba(0x3e62f4ff).into()),
                ("constant".into(), rgba(0x2aa329ff).into()),
                ("hint".into(), rgba(0x008b9fff).into()),
                ("type".into(), rgba(0x98981bff).into()),
                ("emphasis".into(), rgba(0x3e62f4ff).into()),
                ("variable".into(), rgba(0xcfe8cfff).into()),
                ("emphasis.strong".into(), rgba(0x3e62f4ff).into()),
                ("attribute".into(), rgba(0x3e62f4ff).into()),
                ("enum".into(), rgba(0x87711dff).into()),
                ("property".into(), rgba(0xe6183bff).into()),
                ("punctuation.list_marker".into(), rgba(0xcfe8cfff).into()),
                ("variable.special".into(), rgba(0xac2aeeff).into()),
            ],
        },
        status_bar: rgba(0x3b453bff).into(),
        title_bar: rgba(0x3b453bff).into(),
        toolbar: rgba(0x131513ff).into(),
        tab_bar: rgba(0x1f231fff).into(),
        editor: rgba(0x131513ff).into(),
        editor_subheader: rgba(0x1f231fff).into(),
        editor_active_line: rgba(0x1f231fff).into(),
        terminal: rgba(0x131513ff).into(),
        image_fallback_background: rgba(0x3b453bff).into(),
        git_created: rgba(0x2aa329ff).into(),
        git_modified: rgba(0x3e62f4ff).into(),
        git_deleted: rgba(0xe61c3bff).into(),
        git_conflict: rgba(0x98981bff).into(),
        git_ignored: rgba(0x778f77ff).into(),
        git_renamed: rgba(0x98981bff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x3e62f4ff).into(),
                selection: rgba(0x3e62f43d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x2aa329ff).into(),
                selection: rgba(0x2aa3293d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xe61cc3ff).into(),
                selection: rgba(0xe61cc33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x87711dff).into(),
                selection: rgba(0x87711d3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xac2dedff).into(),
                selection: rgba(0xac2ded3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x1b99b3ff).into(),
                selection: rgba(0x1b99b33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xe61c3bff).into(),
                selection: rgba(0xe61c3b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x98981bff).into(),
                selection: rgba(0x98981b3d).into(),
            },
        ],
    }
}
