use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn atelier_cave_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Atelier Cave Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x8f8b96ff).into(),
        border_variant: rgba(0x8f8b96ff).into(),
        border_focused: rgba(0xc8c7f2ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xbfbcc5ff).into(),
        surface: rgba(0xe6e3ebff).into(),
        background: rgba(0xbfbcc5ff).into(),
        filled_element: rgba(0xbfbcc5ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xe1e0f9ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xe1e0f9ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x19171cff).into(),
        text_muted: rgba(0x5a5462ff).into(),
        text_placeholder: rgba(0xbd4677ff).into(),
        text_disabled: rgba(0x6e6876ff).into(),
        text_accent: rgba(0x586cdaff).into(),
        icon_muted: rgba(0x5a5462ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("link_text".into(), rgba(0xaa573cff).into()),
                ("string".into(), rgba(0x299292ff).into()),
                ("emphasis".into(), rgba(0x586cdaff).into()),
                ("label".into(), rgba(0x586cdaff).into()),
                ("property".into(), rgba(0xbe4677ff).into()),
                ("emphasis.strong".into(), rgba(0x586cdaff).into()),
                ("constant".into(), rgba(0x2b9292ff).into()),
                (
                    "function.special.definition".into(),
                    rgba(0xa06d3aff).into(),
                ),
                ("embedded".into(), rgba(0x19171cff).into()),
                ("punctuation.special".into(), rgba(0xbf3fbfff).into()),
                ("function".into(), rgba(0x576cdbff).into()),
                ("tag".into(), rgba(0x586cdaff).into()),
                ("number".into(), rgba(0xaa563bff).into()),
                ("primary".into(), rgba(0x26232aff).into()),
                ("text.literal".into(), rgba(0xaa573cff).into()),
                ("variant".into(), rgba(0xa06d3aff).into()),
                ("type".into(), rgba(0xa06d3aff).into()),
                ("punctuation".into(), rgba(0x26232aff).into()),
                ("string.escape".into(), rgba(0x585260ff).into()),
                ("keyword".into(), rgba(0x9559e7ff).into()),
                ("title".into(), rgba(0x19171cff).into()),
                ("constructor".into(), rgba(0x586cdaff).into()),
                ("punctuation.list_marker".into(), rgba(0x26232aff).into()),
                ("string.special".into(), rgba(0xbf3fbfff).into()),
                ("operator".into(), rgba(0x585260ff).into()),
                ("function.method".into(), rgba(0x576cdbff).into()),
                ("link_uri".into(), rgba(0x2b9292ff).into()),
                ("variable.special".into(), rgba(0x9559e7ff).into()),
                ("hint".into(), rgba(0x776d9dff).into()),
                ("punctuation.bracket".into(), rgba(0x585260ff).into()),
                ("string.special.symbol".into(), rgba(0x299292ff).into()),
                ("predictive".into(), rgba(0x887fafff).into()),
                ("attribute".into(), rgba(0x586cdaff).into()),
                ("enum".into(), rgba(0xaa573cff).into()),
                ("preproc".into(), rgba(0x19171cff).into()),
                ("boolean".into(), rgba(0x2b9292ff).into()),
                ("variable".into(), rgba(0x26232aff).into()),
                ("comment.doc".into(), rgba(0x585260ff).into()),
                ("string.regex".into(), rgba(0x388bc6ff).into()),
                ("punctuation.delimiter".into(), rgba(0x585260ff).into()),
                ("comment".into(), rgba(0x7d7787ff).into()),
            ],
        },
        status_bar: rgba(0xbfbcc5ff).into(),
        title_bar: rgba(0xbfbcc5ff).into(),
        toolbar: rgba(0xefecf4ff).into(),
        tab_bar: rgba(0xe6e3ebff).into(),
        editor: rgba(0xefecf4ff).into(),
        editor_subheader: rgba(0xe6e3ebff).into(),
        editor_active_line: rgba(0xe6e3ebff).into(),
        terminal: rgba(0xefecf4ff).into(),
        image_fallback_background: rgba(0xbfbcc5ff).into(),
        git_created: rgba(0x2b9292ff).into(),
        git_modified: rgba(0x586cdaff).into(),
        git_deleted: rgba(0xbd4677ff).into(),
        git_conflict: rgba(0xa06e3bff).into(),
        git_ignored: rgba(0x6e6876ff).into(),
        git_renamed: rgba(0xa06e3bff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x586cdaff).into(),
                selection: rgba(0x586cda3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x2b9292ff).into(),
                selection: rgba(0x2b92923d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xbf41bfff).into(),
                selection: rgba(0xbf41bf3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xaa573cff).into(),
                selection: rgba(0xaa573c3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x955ae6ff).into(),
                selection: rgba(0x955ae63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x3a8bc6ff).into(),
                selection: rgba(0x3a8bc63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xbd4677ff).into(),
                selection: rgba(0xbd46773d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa06e3bff).into(),
                selection: rgba(0xa06e3b3d).into(),
            },
        ],
    }
}
