use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn ayu_mirage() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Ayu Mirage".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x53565dff).into(),
        border_variant: rgba(0x53565dff).into(),
        border_focused: rgba(0x24556fff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x464a52ff).into(),
        surface: rgba(0x353944ff).into(),
        background: rgba(0x464a52ff).into(),
        filled_element: rgba(0x464a52ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x123950ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x123950ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xcccac2ff).into(),
        text_muted: rgba(0x9a9a98ff).into(),
        text_placeholder: rgba(0xf18779ff).into(),
        text_disabled: rgba(0x7b7d7fff).into(),
        text_accent: rgba(0x72cffeff).into(),
        icon_muted: rgba(0x9a9a98ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("text.literal".into(), rgba(0xfead66ff).into()),
                ("link_text".into(), rgba(0xfead66ff).into()),
                ("function".into(), rgba(0xffd173ff).into()),
                ("punctuation.delimiter".into(), rgba(0xb4b3aeff).into()),
                ("property".into(), rgba(0x72cffeff).into()),
                ("title".into(), rgba(0xcccac2ff).into()),
                ("boolean".into(), rgba(0xdfbfffff).into()),
                ("link_uri".into(), rgba(0xd5fe80ff).into()),
                ("label".into(), rgba(0x72cffeff).into()),
                ("primary".into(), rgba(0xcccac2ff).into()),
                ("number".into(), rgba(0xdfbfffff).into()),
                ("variant".into(), rgba(0x72cffeff).into()),
                ("enum".into(), rgba(0xfead66ff).into()),
                ("string.special.symbol".into(), rgba(0xfead66ff).into()),
                ("operator".into(), rgba(0xf29e74ff).into()),
                ("punctuation.special".into(), rgba(0xdfbfffff).into()),
                ("constructor".into(), rgba(0x72cffeff).into()),
                ("type".into(), rgba(0x73cfffff).into()),
                ("emphasis.strong".into(), rgba(0x72cffeff).into()),
                ("embedded".into(), rgba(0xcccac2ff).into()),
                ("comment".into(), rgba(0xb8cfe680).into()),
                ("tag".into(), rgba(0x72cffeff).into()),
                ("keyword".into(), rgba(0xffad65ff).into()),
                ("punctuation".into(), rgba(0xb4b3aeff).into()),
                ("preproc".into(), rgba(0xcccac2ff).into()),
                ("hint".into(), rgba(0x7399a3ff).into()),
                ("string.special".into(), rgba(0xffdfb3ff).into()),
                ("attribute".into(), rgba(0x72cffeff).into()),
                ("string.regex".into(), rgba(0x95e6cbff).into()),
                ("predictive".into(), rgba(0x6d839bff).into()),
                ("comment.doc".into(), rgba(0x9b9b99ff).into()),
                ("emphasis".into(), rgba(0x72cffeff).into()),
                ("string".into(), rgba(0xd4fe7fff).into()),
                ("constant".into(), rgba(0xdfbfffff).into()),
                ("string.escape".into(), rgba(0x9b9b99ff).into()),
                ("variable".into(), rgba(0xcccac2ff).into()),
                ("punctuation.bracket".into(), rgba(0xb4b3aeff).into()),
                ("punctuation.list_marker".into(), rgba(0xb4b3aeff).into()),
            ],
        },
        status_bar: rgba(0x464a52ff).into(),
        title_bar: rgba(0x464a52ff).into(),
        toolbar: rgba(0x242835ff).into(),
        tab_bar: rgba(0x353944ff).into(),
        editor: rgba(0x242835ff).into(),
        editor_subheader: rgba(0x353944ff).into(),
        editor_active_line: rgba(0x353944ff).into(),
        terminal: rgba(0x242835ff).into(),
        image_fallback_background: rgba(0x464a52ff).into(),
        git_created: rgba(0xd5fe80ff).into(),
        git_modified: rgba(0x72cffeff).into(),
        git_deleted: rgba(0xf18779ff).into(),
        git_conflict: rgba(0xfecf72ff).into(),
        git_ignored: rgba(0x7b7d7fff).into(),
        git_renamed: rgba(0xfecf72ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x72cffeff).into(),
                selection: rgba(0x72cffe3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd5fe80ff).into(),
                selection: rgba(0xd5fe803d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5bcde5ff).into(),
                selection: rgba(0x5bcde53d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfead66ff).into(),
                selection: rgba(0xfead663d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xdebffeff).into(),
                selection: rgba(0xdebffe3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x95e5cbff).into(),
                selection: rgba(0x95e5cb3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf18779ff).into(),
                selection: rgba(0xf187793d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfecf72ff).into(),
                selection: rgba(0xfecf723d).into(),
            },
        ],
    }
}
