use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn ayu_dark() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Ayu Dark".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x3f4043ff).into(),
        border_variant: rgba(0x3f4043ff).into(),
        border_focused: rgba(0x1b4a6eff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x313337ff).into(),
        surface: rgba(0x1f2127ff).into(),
        background: rgba(0x313337ff).into(),
        filled_element: rgba(0x313337ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x0d2f4eff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x0d2f4eff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xbfbdb6ff).into(),
        text_muted: rgba(0x8a8986ff).into(),
        text_placeholder: rgba(0xef7177ff).into(),
        text_disabled: rgba(0x696a6aff).into(),
        text_accent: rgba(0x5ac1feff).into(),
        icon_muted: rgba(0x8a8986ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("emphasis".into(), rgba(0x5ac1feff).into()),
                ("punctuation.bracket".into(), rgba(0xa6a5a0ff).into()),
                ("constructor".into(), rgba(0x5ac1feff).into()),
                ("predictive".into(), rgba(0x5a728bff).into()),
                ("emphasis.strong".into(), rgba(0x5ac1feff).into()),
                ("string.regex".into(), rgba(0x95e6cbff).into()),
                ("tag".into(), rgba(0x5ac1feff).into()),
                ("punctuation".into(), rgba(0xa6a5a0ff).into()),
                ("number".into(), rgba(0xd2a6ffff).into()),
                ("punctuation.special".into(), rgba(0xd2a6ffff).into()),
                ("primary".into(), rgba(0xbfbdb6ff).into()),
                ("boolean".into(), rgba(0xd2a6ffff).into()),
                ("variant".into(), rgba(0x5ac1feff).into()),
                ("link_uri".into(), rgba(0xaad84cff).into()),
                ("comment.doc".into(), rgba(0x8c8b88ff).into()),
                ("title".into(), rgba(0xbfbdb6ff).into()),
                ("text.literal".into(), rgba(0xfe8f40ff).into()),
                ("link_text".into(), rgba(0xfe8f40ff).into()),
                ("punctuation.delimiter".into(), rgba(0xa6a5a0ff).into()),
                ("string.escape".into(), rgba(0x8c8b88ff).into()),
                ("hint".into(), rgba(0x628b80ff).into()),
                ("type".into(), rgba(0x59c2ffff).into()),
                ("variable".into(), rgba(0xbfbdb6ff).into()),
                ("label".into(), rgba(0x5ac1feff).into()),
                ("enum".into(), rgba(0xfe8f40ff).into()),
                ("operator".into(), rgba(0xf29668ff).into()),
                ("function".into(), rgba(0xffb353ff).into()),
                ("preproc".into(), rgba(0xbfbdb6ff).into()),
                ("embedded".into(), rgba(0xbfbdb6ff).into()),
                ("string".into(), rgba(0xa9d94bff).into()),
                ("attribute".into(), rgba(0x5ac1feff).into()),
                ("keyword".into(), rgba(0xff8f3fff).into()),
                ("string.special.symbol".into(), rgba(0xfe8f40ff).into()),
                ("comment".into(), rgba(0xabb5be8c).into()),
                ("property".into(), rgba(0x5ac1feff).into()),
                ("punctuation.list_marker".into(), rgba(0xa6a5a0ff).into()),
                ("constant".into(), rgba(0xd2a6ffff).into()),
                ("string.special".into(), rgba(0xe5b572ff).into()),
            ],
        },
        status_bar: rgba(0x313337ff).into(),
        title_bar: rgba(0x313337ff).into(),
        toolbar: rgba(0x0d1016ff).into(),
        tab_bar: rgba(0x1f2127ff).into(),
        editor: rgba(0x0d1016ff).into(),
        editor_subheader: rgba(0x1f2127ff).into(),
        editor_active_line: rgba(0x1f2127ff).into(),
        terminal: rgba(0x0d1016ff).into(),
        image_fallback_background: rgba(0x313337ff).into(),
        git_created: rgba(0xaad84cff).into(),
        git_modified: rgba(0x5ac1feff).into(),
        git_deleted: rgba(0xef7177ff).into(),
        git_conflict: rgba(0xfeb454ff).into(),
        git_ignored: rgba(0x696a6aff).into(),
        git_renamed: rgba(0xfeb454ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x5ac1feff).into(),
                selection: rgba(0x5ac1fe3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xaad84cff).into(),
                selection: rgba(0xaad84c3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x39bae5ff).into(),
                selection: rgba(0x39bae53d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfe8f40ff).into(),
                selection: rgba(0xfe8f403d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd2a6feff).into(),
                selection: rgba(0xd2a6fe3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x95e5cbff).into(),
                selection: rgba(0x95e5cb3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xef7177ff).into(),
                selection: rgba(0xef71773d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfeb454ff).into(),
                selection: rgba(0xfeb4543d).into(),
            },
        ],
    }
}
