use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn ayu_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Ayu Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0xcfd1d2ff).into(),
        border_variant: rgba(0xcfd1d2ff).into(),
        border_focused: rgba(0xc4daf6ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xdcdddeff).into(),
        surface: rgba(0xececedff).into(),
        background: rgba(0xdcdddeff).into(),
        filled_element: rgba(0xdcdddeff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xdeebfaff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xdeebfaff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x5c6166ff).into(),
        text_muted: rgba(0x8b8e92ff).into(),
        text_placeholder: rgba(0xef7271ff).into(),
        text_disabled: rgba(0xa9acaeff).into(),
        text_accent: rgba(0x3b9ee5ff).into(),
        icon_muted: rgba(0x8b8e92ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("string".into(), rgba(0x86b300ff).into()),
                ("enum".into(), rgba(0xf98d3fff).into()),
                ("comment".into(), rgba(0x787b8099).into()),
                ("comment.doc".into(), rgba(0x898d90ff).into()),
                ("emphasis".into(), rgba(0x3b9ee5ff).into()),
                ("keyword".into(), rgba(0xfa8d3eff).into()),
                ("string.regex".into(), rgba(0x4bbf98ff).into()),
                ("text.literal".into(), rgba(0xf98d3fff).into()),
                ("string.escape".into(), rgba(0x898d90ff).into()),
                ("link_text".into(), rgba(0xf98d3fff).into()),
                ("punctuation".into(), rgba(0x73777bff).into()),
                ("constructor".into(), rgba(0x3b9ee5ff).into()),
                ("constant".into(), rgba(0xa37accff).into()),
                ("variable".into(), rgba(0x5c6166ff).into()),
                ("primary".into(), rgba(0x5c6166ff).into()),
                ("emphasis.strong".into(), rgba(0x3b9ee5ff).into()),
                ("string.special".into(), rgba(0xe6ba7eff).into()),
                ("number".into(), rgba(0xa37accff).into()),
                ("preproc".into(), rgba(0x5c6166ff).into()),
                ("punctuation.delimiter".into(), rgba(0x73777bff).into()),
                ("string.special.symbol".into(), rgba(0xf98d3fff).into()),
                ("boolean".into(), rgba(0xa37accff).into()),
                ("property".into(), rgba(0x3b9ee5ff).into()),
                ("title".into(), rgba(0x5c6166ff).into()),
                ("hint".into(), rgba(0x8ca7c2ff).into()),
                ("predictive".into(), rgba(0x9eb9d3ff).into()),
                ("operator".into(), rgba(0xed9365ff).into()),
                ("type".into(), rgba(0x389ee6ff).into()),
                ("function".into(), rgba(0xf2ad48ff).into()),
                ("variant".into(), rgba(0x3b9ee5ff).into()),
                ("label".into(), rgba(0x3b9ee5ff).into()),
                ("punctuation.list_marker".into(), rgba(0x73777bff).into()),
                ("punctuation.bracket".into(), rgba(0x73777bff).into()),
                ("embedded".into(), rgba(0x5c6166ff).into()),
                ("punctuation.special".into(), rgba(0xa37accff).into()),
                ("attribute".into(), rgba(0x3b9ee5ff).into()),
                ("tag".into(), rgba(0x3b9ee5ff).into()),
                ("link_uri".into(), rgba(0x85b304ff).into()),
            ],
        },
        status_bar: rgba(0xdcdddeff).into(),
        title_bar: rgba(0xdcdddeff).into(),
        toolbar: rgba(0xfcfcfcff).into(),
        tab_bar: rgba(0xececedff).into(),
        editor: rgba(0xfcfcfcff).into(),
        editor_subheader: rgba(0xececedff).into(),
        editor_active_line: rgba(0xececedff).into(),
        terminal: rgba(0xfcfcfcff).into(),
        image_fallback_background: rgba(0xdcdddeff).into(),
        git_created: rgba(0x85b304ff).into(),
        git_modified: rgba(0x3b9ee5ff).into(),
        git_deleted: rgba(0xef7271ff).into(),
        git_conflict: rgba(0xf1ad49ff).into(),
        git_ignored: rgba(0xa9acaeff).into(),
        git_renamed: rgba(0xf1ad49ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x3b9ee5ff).into(),
                selection: rgba(0x3b9ee53d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x85b304ff).into(),
                selection: rgba(0x85b3043d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x55b4d3ff).into(),
                selection: rgba(0x55b4d33d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf98d3fff).into(),
                selection: rgba(0xf98d3f3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa37accff).into(),
                selection: rgba(0xa37acc3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x4dbf99ff).into(),
                selection: rgba(0x4dbf993d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xef7271ff).into(),
                selection: rgba(0xef72713d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf1ad49ff).into(),
                selection: rgba(0xf1ad493d).into(),
            },
        ],
    }
}
