use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn gruvbox_dark_hard() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Gruvbox Dark Hard".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x5b534dff).into(),
        border_variant: rgba(0x5b534dff).into(),
        border_focused: rgba(0x303a36ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x4c4642ff).into(),
        surface: rgba(0x393634ff).into(),
        background: rgba(0x4c4642ff).into(),
        filled_element: rgba(0x4c4642ff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x1e2321ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x1e2321ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xfbf1c7ff).into(),
        text_muted: rgba(0xc5b597ff).into(),
        text_placeholder: rgba(0xfb4a35ff).into(),
        text_disabled: rgba(0x998b78ff).into(),
        text_accent: rgba(0x83a598ff).into(),
        icon_muted: rgba(0xc5b597ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("primary".into(), rgba(0xebdbb2ff).into()),
                ("label".into(), rgba(0x83a598ff).into()),
                ("punctuation.delimiter".into(), rgba(0xe5d5adff).into()),
                ("variant".into(), rgba(0x83a598ff).into()),
                ("type".into(), rgba(0xfabd2eff).into()),
                ("string.regex".into(), rgba(0xfe7f18ff).into()),
                ("function.builtin".into(), rgba(0xfb4833ff).into()),
                ("title".into(), rgba(0xb8bb25ff).into()),
                ("string".into(), rgba(0xb8bb25ff).into()),
                ("operator".into(), rgba(0x8ec07cff).into()),
                ("embedded".into(), rgba(0x8ec07cff).into()),
                ("punctuation.bracket".into(), rgba(0xa89984ff).into()),
                ("string.special".into(), rgba(0xd3869bff).into()),
                ("attribute".into(), rgba(0x83a598ff).into()),
                ("comment".into(), rgba(0xa89984ff).into()),
                ("link_text".into(), rgba(0x8ec07cff).into()),
                ("punctuation.special".into(), rgba(0xe5d5adff).into()),
                ("punctuation.list_marker".into(), rgba(0xebdbb2ff).into()),
                ("comment.doc".into(), rgba(0xc6b697ff).into()),
                ("preproc".into(), rgba(0xfbf1c7ff).into()),
                ("text.literal".into(), rgba(0x83a598ff).into()),
                ("function".into(), rgba(0xb8bb25ff).into()),
                ("predictive".into(), rgba(0x717363ff).into()),
                ("emphasis.strong".into(), rgba(0x83a598ff).into()),
                ("punctuation".into(), rgba(0xd5c4a1ff).into()),
                ("string.special.symbol".into(), rgba(0x8ec07cff).into()),
                ("property".into(), rgba(0xebdbb2ff).into()),
                ("keyword".into(), rgba(0xfb4833ff).into()),
                ("constructor".into(), rgba(0x83a598ff).into()),
                ("tag".into(), rgba(0x8ec07cff).into()),
                ("variable".into(), rgba(0x83a598ff).into()),
                ("enum".into(), rgba(0xfe7f18ff).into()),
                ("hint".into(), rgba(0x8c957dff).into()),
                ("number".into(), rgba(0xd3869bff).into()),
                ("constant".into(), rgba(0xfabd2eff).into()),
                ("boolean".into(), rgba(0xd3869bff).into()),
                ("link_uri".into(), rgba(0xd3869bff).into()),
                ("string.escape".into(), rgba(0xc6b697ff).into()),
                ("emphasis".into(), rgba(0x83a598ff).into()),
            ],
        },
        status_bar: rgba(0x4c4642ff).into(),
        title_bar: rgba(0x4c4642ff).into(),
        toolbar: rgba(0x1d2021ff).into(),
        tab_bar: rgba(0x393634ff).into(),
        editor: rgba(0x1d2021ff).into(),
        editor_subheader: rgba(0x393634ff).into(),
        editor_active_line: rgba(0x393634ff).into(),
        terminal: rgba(0x1d2021ff).into(),
        image_fallback_background: rgba(0x4c4642ff).into(),
        git_created: rgba(0xb7bb26ff).into(),
        git_modified: rgba(0x83a598ff).into(),
        git_deleted: rgba(0xfb4a35ff).into(),
        git_conflict: rgba(0xf9bd2fff).into(),
        git_ignored: rgba(0x998b78ff).into(),
        git_renamed: rgba(0xf9bd2fff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x83a598ff).into(),
                selection: rgba(0x83a5983d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xb7bb26ff).into(),
                selection: rgba(0xb7bb263d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa89984ff).into(),
                selection: rgba(0xa899843d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfd801bff).into(),
                selection: rgba(0xfd801b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd3869bff).into(),
                selection: rgba(0xd3869b3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x8ec07cff).into(),
                selection: rgba(0x8ec07c3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfb4a35ff).into(),
                selection: rgba(0xfb4a353d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf9bd2fff).into(),
                selection: rgba(0xf9bd2f3d).into(),
            },
        ],
    }
}
