use gpui::rgba;

use crate::{
    default_color_scales, Appearance, GitStatusColors, PlayerColor, PlayerColors, StatusColors,
    SyntaxTheme, SystemColors, ThemeColors, ThemeFamily, ThemeStyles, ThemeVariant,
};

pub fn gruvbox() -> ThemeFamily {
    ThemeFamily {
        id: "c0b7f0e7-f261-4a33-a2bf-baf2e140aac4".into(),
        name: "Gruvbox".into(),
        author: "morhetz".into(),
        themes: vec![
            ThemeVariant {
                id: "fb9f8f64-372b-4fda-8dbd-d610c97a9691".into(),
                name: "Gruvbox Dark Hard".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x3c3836ff).into(),
                        border_variant: rgba(0x3c3836ff).into(),
                        border_focused: rgba(0x3c3836ff).into(),
                        border_disabled: rgba(0x3c3836ff).into(),
                        border_selected: rgba(0x3c3836ff).into(),
                        border_transparent: rgba(0x3c3836ff).into(),
                        elevated_surface_background: rgba(0x18191bff).into(),
                        surface_background: rgba(0x18191bff).into(),
                        background: rgba(0x1d2021ff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xebdbb2ff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x1d2021ff).into(),
                        tab_active_background: rgba(0x32302fff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x1d2021ff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0xfb4833ff).into(),
                        terminal_ansi_bright_green: rgba(0xb8bb25ff).into(),
                        terminal_ansi_bright_yellow: rgba(0xfabd2eff).into(),
                        terminal_ansi_bright_blue: rgba(0x83a598ff).into(),
                        terminal_ansi_bright_magenta: rgba(0xd3869bff).into(),
                        terminal_ansi_bright_cyan: rgba(0x8ec07cff).into(),
                        terminal_ansi_bright_white: rgba(0xebdbb2ff).into(),
                        terminal_ansi_black: rgba(0x3c3836ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0xa89984ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "72f0ea45-33bc-49d8-9f52-87540f858fb4".into(),
                name: "Gruvbox Dark Medium".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x3c3836ff).into(),
                        border_variant: rgba(0x3c3836ff).into(),
                        border_focused: rgba(0x3c3836ff).into(),
                        border_disabled: rgba(0x3c3836ff).into(),
                        border_selected: rgba(0x3c3836ff).into(),
                        border_transparent: rgba(0x3c3836ff).into(),
                        elevated_surface_background: rgba(0x18191bff).into(),
                        surface_background: rgba(0x18191bff).into(),
                        background: rgba(0x282828ff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xebdbb2ff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x282828ff).into(),
                        tab_active_background: rgba(0x3c3836ff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x282828ff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0xfb4833ff).into(),
                        terminal_ansi_bright_green: rgba(0xb8bb25ff).into(),
                        terminal_ansi_bright_yellow: rgba(0xfabd2eff).into(),
                        terminal_ansi_bright_blue: rgba(0x83a598ff).into(),
                        terminal_ansi_bright_magenta: rgba(0xd3869bff).into(),
                        terminal_ansi_bright_cyan: rgba(0x8ec07cff).into(),
                        terminal_ansi_bright_white: rgba(0xebdbb2ff).into(),
                        terminal_ansi_black: rgba(0x3c3836ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0xa89984ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "5ea1cdf8-6ed0-4e54-b44a-14c6634701cf".into(),
                name: "Gruvbox Dark Soft".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x3c3836ff).into(),
                        border_variant: rgba(0x3c3836ff).into(),
                        border_focused: rgba(0x3c3836ff).into(),
                        border_disabled: rgba(0x3c3836ff).into(),
                        border_selected: rgba(0x3c3836ff).into(),
                        border_transparent: rgba(0x3c3836ff).into(),
                        elevated_surface_background: rgba(0x18191bff).into(),
                        surface_background: rgba(0x18191bff).into(),
                        background: rgba(0x32302fff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xebdbb2ff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x32302fff).into(),
                        tab_active_background: rgba(0x504945ff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x32302fff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0xfb4833ff).into(),
                        terminal_ansi_bright_green: rgba(0xb8bb25ff).into(),
                        terminal_ansi_bright_yellow: rgba(0xfabd2eff).into(),
                        terminal_ansi_bright_blue: rgba(0x83a598ff).into(),
                        terminal_ansi_bright_magenta: rgba(0xd3869bff).into(),
                        terminal_ansi_bright_cyan: rgba(0x8ec07cff).into(),
                        terminal_ansi_bright_white: rgba(0xebdbb2ff).into(),
                        terminal_ansi_black: rgba(0x3c3836ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0xa89984ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "b0c9082f-00c8-4a02-a4de-9fd7af97c7f2".into(),
                name: "Gruvbox Light Hard".into(),
                appearance: Appearance::Light,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0xebdbb2ff).into(),
                        border_variant: rgba(0xebdbb2ff).into(),
                        border_focused: rgba(0xebdbb2ff).into(),
                        border_disabled: rgba(0xebdbb2ff).into(),
                        border_selected: rgba(0xebdbb2ff).into(),
                        border_transparent: rgba(0xebdbb2ff).into(),
                        elevated_surface_background: rgba(0xf9f9fbff).into(),
                        surface_background: rgba(0xf9f9fbff).into(),
                        background: rgba(0xf9f5d7ff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0xe8e8ecff).into(),
                        element_active: rgba(0xe0e1e6ff).into(),
                        element_selected: rgba(0xe0e1e6ff).into(),
                        element_disabled: rgba(0x0000320f).into(),
                        element_placeholder: rgba(0x60646cff).into(),
                        element_drop_target: rgba(0x008bff0b).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0xe8e8ecff).into(),
                        ghost_element_active: rgba(0xe0e1e6ff).into(),
                        ghost_element_selected: rgba(0xe0e1e6ff).into(),
                        ghost_element_disabled: rgba(0x0000320f).into(),
                        text: rgba(0x3c3836ff).into(),
                        text_muted: rgba(0x60646cff).into(),
                        text_placeholder: rgba(0x80838dff).into(),
                        text_disabled: rgba(0x8b8d98ff).into(),
                        text_accent: rgba(0x0c73ceff).into(),
                        icon: rgba(0x60646cff).into(),
                        icon_muted: rgba(0x80838dff).into(),
                        icon_disabled: rgba(0x8b8d98ff).into(),
                        icon_placeholder: rgba(0x80838dff).into(),
                        icon_accent: rgba(0x0c73ceff).into(),
                        status_bar_background: rgba(0xf9f9fbff).into(),
                        title_bar_background: rgba(0xf9f9fbff).into(),
                        toolbar_background: rgba(0xfcfcfdff).into(),
                        tab_bar_background: rgba(0xf9f9fbff).into(),
                        tab_inactive_background: rgba(0xf9f5d7ff).into(),
                        tab_active_background: rgba(0xf2e5bcff).into(),
                        editor_background: rgba(0xfcfcfdff).into(),
                        editor_subheader_background: rgba(0xf9f9fbff).into(),
                        editor_active_line: rgba(0x0000320f).into(),
                        terminal_background: rgba(0xf9f5d7ff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0x9d0006ff).into(),
                        terminal_ansi_bright_green: rgba(0x79740eff).into(),
                        terminal_ansi_bright_yellow: rgba(0xb57613ff).into(),
                        terminal_ansi_bright_blue: rgba(0x066578ff).into(),
                        terminal_ansi_bright_magenta: rgba(0x8f3e71ff).into(),
                        terminal_ansi_bright_cyan: rgba(0x427b58ff).into(),
                        terminal_ansi_bright_white: rgba(0x3c3836ff).into(),
                        terminal_ansi_black: rgba(0xebdbb2ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0x7c6f64ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "172c281c-ff0a-496e-8794-880e2fc3aa49".into(),
                name: "Gruvbox Light Medium".into(),
                appearance: Appearance::Light,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0xebdbb2ff).into(),
                        border_variant: rgba(0xebdbb2ff).into(),
                        border_focused: rgba(0xebdbb2ff).into(),
                        border_disabled: rgba(0xebdbb2ff).into(),
                        border_selected: rgba(0xebdbb2ff).into(),
                        border_transparent: rgba(0xebdbb2ff).into(),
                        elevated_surface_background: rgba(0xf9f9fbff).into(),
                        surface_background: rgba(0xf9f9fbff).into(),
                        background: rgba(0xfbf1c7ff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0xe8e8ecff).into(),
                        element_active: rgba(0xe0e1e6ff).into(),
                        element_selected: rgba(0xe0e1e6ff).into(),
                        element_disabled: rgba(0x0000320f).into(),
                        element_placeholder: rgba(0x60646cff).into(),
                        element_drop_target: rgba(0x008bff0b).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0xe8e8ecff).into(),
                        ghost_element_active: rgba(0xe0e1e6ff).into(),
                        ghost_element_selected: rgba(0xe0e1e6ff).into(),
                        ghost_element_disabled: rgba(0x0000320f).into(),
                        text: rgba(0x3c3836ff).into(),
                        text_muted: rgba(0x60646cff).into(),
                        text_placeholder: rgba(0x80838dff).into(),
                        text_disabled: rgba(0x8b8d98ff).into(),
                        text_accent: rgba(0x0c73ceff).into(),
                        icon: rgba(0x60646cff).into(),
                        icon_muted: rgba(0x80838dff).into(),
                        icon_disabled: rgba(0x8b8d98ff).into(),
                        icon_placeholder: rgba(0x80838dff).into(),
                        icon_accent: rgba(0x0c73ceff).into(),
                        status_bar_background: rgba(0xf9f9fbff).into(),
                        title_bar_background: rgba(0xf9f9fbff).into(),
                        toolbar_background: rgba(0xfcfcfdff).into(),
                        tab_bar_background: rgba(0xf9f9fbff).into(),
                        tab_inactive_background: rgba(0xfbf1c7ff).into(),
                        tab_active_background: rgba(0xebdbb2ff).into(),
                        editor_background: rgba(0xfcfcfdff).into(),
                        editor_subheader_background: rgba(0xf9f9fbff).into(),
                        editor_active_line: rgba(0x0000320f).into(),
                        terminal_background: rgba(0xfbf1c7ff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0x9d0006ff).into(),
                        terminal_ansi_bright_green: rgba(0x79740eff).into(),
                        terminal_ansi_bright_yellow: rgba(0xb57613ff).into(),
                        terminal_ansi_bright_blue: rgba(0x066578ff).into(),
                        terminal_ansi_bright_magenta: rgba(0x8f3e71ff).into(),
                        terminal_ansi_bright_cyan: rgba(0x427b58ff).into(),
                        terminal_ansi_bright_white: rgba(0x3c3836ff).into(),
                        terminal_ansi_black: rgba(0xebdbb2ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0x7c6f64ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "b94f3305-b755-44f2-948c-cfd8c9d3158f".into(),
                name: "Gruvbox Light Soft".into(),
                appearance: Appearance::Light,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0xebdbb2ff).into(),
                        border_variant: rgba(0xebdbb2ff).into(),
                        border_focused: rgba(0xebdbb2ff).into(),
                        border_disabled: rgba(0xebdbb2ff).into(),
                        border_selected: rgba(0xebdbb2ff).into(),
                        border_transparent: rgba(0xebdbb2ff).into(),
                        elevated_surface_background: rgba(0xf9f9fbff).into(),
                        surface_background: rgba(0xf9f9fbff).into(),
                        background: rgba(0xf2e5bcff).into(),
                        element_background: rgba(0x44858780).into(),
                        element_hover: rgba(0xe8e8ecff).into(),
                        element_active: rgba(0xe0e1e6ff).into(),
                        element_selected: rgba(0xe0e1e6ff).into(),
                        element_disabled: rgba(0x0000320f).into(),
                        element_placeholder: rgba(0x60646cff).into(),
                        element_drop_target: rgba(0x008bff0b).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0xe8e8ecff).into(),
                        ghost_element_active: rgba(0xe0e1e6ff).into(),
                        ghost_element_selected: rgba(0xe0e1e6ff).into(),
                        ghost_element_disabled: rgba(0x0000320f).into(),
                        text: rgba(0x3c3836ff).into(),
                        text_muted: rgba(0x60646cff).into(),
                        text_placeholder: rgba(0x80838dff).into(),
                        text_disabled: rgba(0x8b8d98ff).into(),
                        text_accent: rgba(0x0c73ceff).into(),
                        icon: rgba(0x60646cff).into(),
                        icon_muted: rgba(0x80838dff).into(),
                        icon_disabled: rgba(0x8b8d98ff).into(),
                        icon_placeholder: rgba(0x80838dff).into(),
                        icon_accent: rgba(0x0c73ceff).into(),
                        status_bar_background: rgba(0xf9f9fbff).into(),
                        title_bar_background: rgba(0xf9f9fbff).into(),
                        toolbar_background: rgba(0xfcfcfdff).into(),
                        tab_bar_background: rgba(0xf9f9fbff).into(),
                        tab_inactive_background: rgba(0xf2e5bcff).into(),
                        tab_active_background: rgba(0xd5c4a1ff).into(),
                        editor_background: rgba(0xfcfcfdff).into(),
                        editor_subheader_background: rgba(0xf9f9fbff).into(),
                        editor_active_line: rgba(0x0000320f).into(),
                        terminal_background: rgba(0xf2e5bcff).into(),
                        terminal_ansi_bright_black: rgba(0x928374ff).into(),
                        terminal_ansi_bright_red: rgba(0x9d0006ff).into(),
                        terminal_ansi_bright_green: rgba(0x79740eff).into(),
                        terminal_ansi_bright_yellow: rgba(0xb57613ff).into(),
                        terminal_ansi_bright_blue: rgba(0x066578ff).into(),
                        terminal_ansi_bright_magenta: rgba(0x8f3e71ff).into(),
                        terminal_ansi_bright_cyan: rgba(0x427b58ff).into(),
                        terminal_ansi_bright_white: rgba(0x3c3836ff).into(),
                        terminal_ansi_black: rgba(0xebdbb2ff).into(),
                        terminal_ansi_red: rgba(0xcc241cff).into(),
                        terminal_ansi_green: rgba(0x989719ff).into(),
                        terminal_ansi_yellow: rgba(0xd79920ff).into(),
                        terminal_ansi_blue: rgba(0x448587ff).into(),
                        terminal_ansi_magenta: rgba(0xb16185ff).into(),
                        terminal_ansi_cyan: rgba(0x679d6aff).into(),
                        terminal_ansi_white: rgba(0x7c6f64ff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
        ],
        scales: default_color_scales(),
    }
}
