// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

#[allow(unused)]
use crate::{
    Appearance, StatusColorsRefinement, ThemeColorsRefinement, UserFontStyle, UserFontWeight,
    UserHighlightStyle, UserSyntaxTheme, UserTheme, UserThemeFamily, UserThemeStylesRefinement,
};

pub fn gruvbox_zed_1() -> UserThemeFamily {
    UserThemeFamily {
        name: "Gruvbox (Zed1)".into(),
        author: "Zed Industries".into(),
        themes: vec![
            UserTheme {
                name: "Gruvbox Light Hard (Zed1)".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0xc9b99aff).into()),
                        border_variant: Some(rgba(0xc9b99aff).into()),
                        background: Some(rgba(0xd9c8a4ff).into()),
                        text: Some(rgba(0x282828ff).into()),
                        title_bar_background: Some(rgba(0xd9c8a4ff).into()),
                        scrollbar_thumb_background: Some(rgba(0x2828284d).into()),
                        scrollbar_track_border: Some(rgba(0xefe2bcff).into()),
                        editor_foreground: Some(rgba(0x282828ff).into()),
                        editor_background: Some(rgba(0xf9f5d7ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0x958e43ff).into()),
                        deleted: Some(rgba(0x9d0408ff).into()),
                        modified: Some(rgba(0xb57616ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7c6f64ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x677562ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7d9881ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x3c3836ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x665c54ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Gruvbox Dark Soft (Zed1)".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x5b534dff).into()),
                        border_variant: Some(rgba(0x5b534dff).into()),
                        background: Some(rgba(0x4c4642ff).into()),
                        text: Some(rgba(0xebdbb2ff).into()),
                        title_bar_background: Some(rgba(0x4c4642ff).into()),
                        scrollbar_thumb_background: Some(rgba(0xfbf1c74d).into()),
                        scrollbar_track_border: Some(rgba(0x393634ff).into()),
                        editor_foreground: Some(rgba(0xebdbb2ff).into()),
                        editor_background: Some(rgba(0x32302fff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0xb8bb27ff).into()),
                        deleted: Some(rgba(0xd0382bff).into()),
                        modified: Some(rgba(0xf9bd30ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8d957eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x717363ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfbf1c7ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd5c4a1ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Gruvbox Light (Zed1)".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0xc9b99aff).into()),
                        border_variant: Some(rgba(0xc9b99aff).into()),
                        background: Some(rgba(0xd9c8a4ff).into()),
                        text: Some(rgba(0x282828ff).into()),
                        title_bar_background: Some(rgba(0xd9c8a4ff).into()),
                        scrollbar_thumb_background: Some(rgba(0x2828284d).into()),
                        scrollbar_track_border: Some(rgba(0xefe1b8ff).into()),
                        editor_foreground: Some(rgba(0x282828ff).into()),
                        editor_background: Some(rgba(0xfbf1c7ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0x958e43ff).into()),
                        deleted: Some(rgba(0x9d0408ff).into()),
                        modified: Some(rgba(0xb57616ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7c6f64ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x677562ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7d9881ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x3c3836ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x665c54ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Gruvbox Dark (Zed1)".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x5b534dff).into()),
                        border_variant: Some(rgba(0x5b534dff).into()),
                        background: Some(rgba(0x4c4642ff).into()),
                        text: Some(rgba(0xebdbb2ff).into()),
                        title_bar_background: Some(rgba(0x4c4642ff).into()),
                        scrollbar_thumb_background: Some(rgba(0xfbf1c74d).into()),
                        scrollbar_track_border: Some(rgba(0x373432ff).into()),
                        editor_foreground: Some(rgba(0xebdbb2ff).into()),
                        editor_background: Some(rgba(0x282828ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0xb8bb27ff).into()),
                        deleted: Some(rgba(0xd0382bff).into()),
                        modified: Some(rgba(0xf9bd30ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8d957eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x717363ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfbf1c7ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd5c4a1ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Gruvbox Light Soft (Zed1)".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0xc9b99aff).into()),
                        border_variant: Some(rgba(0xc9b99aff).into()),
                        background: Some(rgba(0xd9c8a4ff).into()),
                        text: Some(rgba(0x282828ff).into()),
                        title_bar_background: Some(rgba(0xd9c8a4ff).into()),
                        scrollbar_thumb_background: Some(rgba(0x2828284d).into()),
                        scrollbar_track_border: Some(rgba(0xeddeb5ff).into()),
                        editor_foreground: Some(rgba(0x282828ff).into()),
                        editor_background: Some(rgba(0xf2e5bcff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0x958e43ff).into()),
                        deleted: Some(rgba(0x9d0408ff).into()),
                        modified: Some(rgba(0xb57616ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7c6f64ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x677562ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9d0006ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x7d9881ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x3c3836ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x665c54ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x282828ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x413d3aff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x5d544eff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xaf3a03ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8f3f71ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x427b58ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x79740eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb57614ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x076678ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x0b6678ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Gruvbox Dark Hard (Zed1)".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x5b534dff).into()),
                        border_variant: Some(rgba(0x5b534dff).into()),
                        background: Some(rgba(0x4c4642ff).into()),
                        text: Some(rgba(0xebdbb2ff).into()),
                        title_bar_background: Some(rgba(0x4c4642ff).into()),
                        scrollbar_thumb_background: Some(rgba(0xfbf1c74d).into()),
                        scrollbar_track_border: Some(rgba(0x343130ff).into()),
                        editor_foreground: Some(rgba(0xebdbb2ff).into()),
                        editor_background: Some(rgba(0x1d2021ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        created: Some(rgba(0xb8bb27ff).into()),
                        deleted: Some(rgba(0xd0382bff).into()),
                        modified: Some(rgba(0xf9bd30ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "attribute".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "boolean".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "comment.doc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "constructor".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "embedded".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "emphasis.strong".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "enum".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "function.builtin".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "hint".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8d957eff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "keyword".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfb4934ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "label".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_text".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "link_uri".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "number".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "operator".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "predictive".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x717363ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "preproc".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfbf1c7ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "primary".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "property".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd5c4a1ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.bracket".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xa89984ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.delimiter".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.list_marker".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebdbb2ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xe5d5adff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.escape".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xc7b798ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.regex".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfe8019ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd3869bff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "string.special.symbol".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "tag".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x8ec07cff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "text.literal".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "title".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xb8bb26ff).into()),
                                    font_weight: Some(UserFontWeight(700.0)),
                                    ..Default::default()
                                },
                            ),
                            (
                                "type".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xfabd2fff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variable".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                            (
                                "variant".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x83a598ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
        ],
    }
}
