// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

mod andromeda;
mod atelier;
mod ayu;
mod gruvbox;
mod one;
mod rose_pine;
mod sandcastle;
mod solarized;
mod summercamp;

pub use andromeda::*;
pub use atelier::*;
pub use ayu::*;
pub use gruvbox::*;
pub use one::*;
pub use rose_pine::*;
pub use sandcastle::*;
pub use solarized::*;
pub use summercamp::*;

use crate::UserThemeFamily;

pub(crate) fn all_user_themes() -> Vec<UserThemeFamily> {
    vec![
        andromeda(),
        atelier(),
        ayu(),
        gruvbox(),
        one(),
        rose_pine(),
        sandcastle(),
        solarized(),
        summercamp(),
    ]
}
