use gpui::rgba;

use crate::{
    Appearance, ThemeColorsRefinement, UserTheme, UserThemeFamily, UserThemeStylesRefinement,
};

pub fn notctis() -> UserThemeFamily {
    UserThemeFamily {
        name: "Notctis".into(),
        author: "Liviu Schera (liviuschera)".into(),
        themes: vec![
            UserTheme {
                name: "Noctis Azureus".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x1579b6ff).into()),
                        border_variant: Some(rgba(0x1579b6ff).into()),
                        border_focused: Some(rgba(0x1579b6ff).into()),
                        border_selected: Some(rgba(0x1579b6ff).into()),
                        border_transparent: Some(rgba(0x1579b6ff).into()),
                        border_disabled: Some(rgba(0x1579b6ff).into()),
                        elevated_surface_background: Some(rgba(0x051b28ff).into()),
                        surface_background: Some(rgba(0x051b28ff).into()),
                        background: Some(rgba(0x07263aff).into()),
                        element_background: Some(rgba(0x007e99ff).into()),
                        text: Some(rgba(0xbecfdaff).into()),
                        tab_inactive_background: Some(rgba(0x08324eff).into()),
                        tab_active_background: Some(rgba(0x07263aff).into()),
                        terminal_background: Some(rgba(0x051b28ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x475e6cff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xbecfdaff).into()),
                        terminal_ansi_black: Some(rgba(0x28343dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xaec3d0ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Bordo".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x997582ff).into()),
                        border_variant: Some(rgba(0x997582ff).into()),
                        border_focused: Some(rgba(0x997582ff).into()),
                        border_selected: Some(rgba(0x997582ff).into()),
                        border_transparent: Some(rgba(0x997582ff).into()),
                        border_disabled: Some(rgba(0x997582ff).into()),
                        elevated_surface_background: Some(rgba(0x272022ff).into()),
                        surface_background: Some(rgba(0x272022ff).into()),
                        background: Some(rgba(0x322a2dff).into()),
                        element_background: Some(rgba(0x007e99ff).into()),
                        text: Some(rgba(0xcbbec2ff).into()),
                        tab_inactive_background: Some(rgba(0x413036ff).into()),
                        tab_active_background: Some(rgba(0x322a2dff).into()),
                        terminal_background: Some(rgba(0x272022ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x69545bff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xcbbec2ff).into()),
                        terminal_ansi_black: Some(rgba(0x47393eff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xb9acb0ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctus Hibernus".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x00c6e0ff).into()),
                        border_variant: Some(rgba(0x00c6e0ff).into()),
                        border_focused: Some(rgba(0x00c6e0ff).into()),
                        border_selected: Some(rgba(0x00c6e0ff).into()),
                        border_transparent: Some(rgba(0x00c6e0ff).into()),
                        border_disabled: Some(rgba(0x00c6e0ff).into()),
                        elevated_surface_background: Some(rgba(0xe1eeefff).into()),
                        surface_background: Some(rgba(0xe1eeefff).into()),
                        background: Some(rgba(0xf4f6f6ff).into()),
                        element_background: Some(rgba(0x089099ff).into()),
                        text: Some(rgba(0x005661ff).into()),
                        tab_inactive_background: Some(rgba(0xcaedf2ff).into()),
                        tab_active_background: Some(rgba(0xf4f6f6ff).into()),
                        terminal_background: Some(rgba(0xe1eeefff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x004d57ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xff3f00ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x00d17aff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xff8c00ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x0ea3ffff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xff6b9eff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x00cae6ff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xbbc3c4ff).into()),
                        terminal_ansi_black: Some(rgba(0x003b41ff).into()),
                        terminal_ansi_red: Some(rgba(0xe34d1bff).into()),
                        terminal_ansi_green: Some(rgba(0x00b368ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xf49724ff).into()),
                        terminal_ansi_blue: Some(rgba(0x0094f0ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xff5792ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x00bdd6ff).into()),
                        terminal_ansi_white: Some(rgba(0x8ca6a6ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Lilac".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0xaea4f4ff).into()),
                        border_variant: Some(rgba(0xaea4f4ff).into()),
                        border_focused: Some(rgba(0xaea4f4ff).into()),
                        border_selected: Some(rgba(0xaea4f4ff).into()),
                        border_transparent: Some(rgba(0xaea4f4ff).into()),
                        border_disabled: Some(rgba(0xaea4f4ff).into()),
                        elevated_surface_background: Some(rgba(0xe9e7f3ff).into()),
                        surface_background: Some(rgba(0xe9e7f3ff).into()),
                        background: Some(rgba(0xf2f1f8ff).into()),
                        element_background: Some(rgba(0x8d7ffeff).into()),
                        text: Some(rgba(0x0c006bff).into()),
                        tab_inactive_background: Some(rgba(0xe2dff6ff).into()),
                        tab_active_background: Some(rgba(0xf2f1f8ff).into()),
                        terminal_background: Some(rgba(0xe9e7f3ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x0f0080ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xff3f00ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x00d17aff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xff8c00ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x0ea3ffff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xff6b9eff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x00cae6ff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xbbc3c4ff).into()),
                        terminal_ansi_black: Some(rgba(0x0c006bff).into()),
                        terminal_ansi_red: Some(rgba(0xe34d1bff).into()),
                        terminal_ansi_green: Some(rgba(0x00b368ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xf49724ff).into()),
                        terminal_ansi_blue: Some(rgba(0x0094f0ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xff5792ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x00bdd6ff).into()),
                        terminal_ansi_white: Some(rgba(0x8ca6a6ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Lux".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x00c6e0ff).into()),
                        border_variant: Some(rgba(0x00c6e0ff).into()),
                        border_focused: Some(rgba(0x00c6e0ff).into()),
                        border_selected: Some(rgba(0x00c6e0ff).into()),
                        border_transparent: Some(rgba(0x00c6e0ff).into()),
                        border_disabled: Some(rgba(0x00c6e0ff).into()),
                        elevated_surface_background: Some(rgba(0xf6eddaff).into()),
                        surface_background: Some(rgba(0xf6eddaff).into()),
                        background: Some(rgba(0xfef8ecff).into()),
                        element_background: Some(rgba(0x089099ff).into()),
                        text: Some(rgba(0x005661ff).into()),
                        tab_inactive_background: Some(rgba(0xf0e9d6ff).into()),
                        tab_active_background: Some(rgba(0xfef8ecff).into()),
                        terminal_background: Some(rgba(0xf6eddaff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x004d57ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xff3f00ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x00d17aff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xff8c00ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x0ea3ffff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xff6b9eff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x00cae6ff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xbbc3c4ff).into()),
                        terminal_ansi_black: Some(rgba(0x003b41ff).into()),
                        terminal_ansi_red: Some(rgba(0xe34d1bff).into()),
                        terminal_ansi_green: Some(rgba(0x00b368ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xf49724ff).into()),
                        terminal_ansi_blue: Some(rgba(0x0094f0ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xff5792ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x00bdd6ff).into()),
                        terminal_ansi_white: Some(rgba(0x8ca6a6ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Minimus".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x496c83ff).into()),
                        border_variant: Some(rgba(0x496c83ff).into()),
                        border_focused: Some(rgba(0x496c83ff).into()),
                        border_selected: Some(rgba(0x496c83ff).into()),
                        border_transparent: Some(rgba(0x496c83ff).into()),
                        border_disabled: Some(rgba(0x496c83ff).into()),
                        elevated_surface_background: Some(rgba(0x0e1920ff).into()),
                        surface_background: Some(rgba(0x0e1920ff).into()),
                        background: Some(rgba(0x1b2932ff).into()),
                        element_background: Some(rgba(0x2e616bff).into()),
                        text: Some(rgba(0xc5cdd3ff).into()),
                        tab_inactive_background: Some(rgba(0x202d37ff).into()),
                        tab_active_background: Some(rgba(0x1b2932ff).into()),
                        terminal_background: Some(rgba(0x0e1920ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x425866ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xca8468ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x84c8abff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xd1aa7bff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x68a4caff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xc88da2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x84bfc8ff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xc5d1d3ff).into()),
                        terminal_ansi_black: Some(rgba(0x182935ff).into()),
                        terminal_ansi_red: Some(rgba(0xc08872ff).into()),
                        terminal_ansi_green: Some(rgba(0x72c09fff).into()),
                        terminal_ansi_yellow: Some(rgba(0xc8a984ff).into()),
                        terminal_ansi_blue: Some(rgba(0x6095b7ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xc28097ff).into()),
                        terminal_ansi_cyan: Some(rgba(0x72b7c0ff).into()),
                        terminal_ansi_white: Some(rgba(0xc5cdd3ff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x0d6571ff).into()),
                        border_variant: Some(rgba(0x0d6571ff).into()),
                        border_focused: Some(rgba(0x0d6571ff).into()),
                        border_selected: Some(rgba(0x0d6571ff).into()),
                        border_transparent: Some(rgba(0x0d6571ff).into()),
                        border_disabled: Some(rgba(0x0d6571ff).into()),
                        elevated_surface_background: Some(rgba(0x03181aff).into()),
                        surface_background: Some(rgba(0x03181aff).into()),
                        background: Some(rgba(0x052428ff).into()),
                        element_background: Some(rgba(0x089099ff).into()),
                        text: Some(rgba(0xb1c9ccff).into()),
                        tab_inactive_background: Some(rgba(0x052e32ff).into()),
                        tab_active_background: Some(rgba(0x052428ff).into()),
                        terminal_background: Some(rgba(0x03181aff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x47686cff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xc1d4d7ff).into()),
                        terminal_ansi_black: Some(rgba(0x324a4dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xb1c9ccff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Obscuro".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x0d6571ff).into()),
                        border_variant: Some(rgba(0x0d6571ff).into()),
                        border_focused: Some(rgba(0x0d6571ff).into()),
                        border_selected: Some(rgba(0x0d6571ff).into()),
                        border_transparent: Some(rgba(0x0d6571ff).into()),
                        border_disabled: Some(rgba(0x0d6571ff).into()),
                        elevated_surface_background: Some(rgba(0x020c0eff).into()),
                        surface_background: Some(rgba(0x020c0eff).into()),
                        background: Some(rgba(0x031316ff).into()),
                        element_background: Some(rgba(0x089099ff).into()),
                        text: Some(rgba(0xb1c9ccff).into()),
                        tab_inactive_background: Some(rgba(0x052e32ff).into()),
                        tab_active_background: Some(rgba(0x031316ff).into()),
                        terminal_background: Some(rgba(0x020c0eff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x47686cff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xc1d4d7ff).into()),
                        terminal_ansi_black: Some(rgba(0x324a4dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xb1c9ccff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Sereno".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x0d6571ff).into()),
                        border_variant: Some(rgba(0x0d6571ff).into()),
                        border_focused: Some(rgba(0x0d6571ff).into()),
                        border_selected: Some(rgba(0x0d6571ff).into()),
                        border_transparent: Some(rgba(0x0d6571ff).into()),
                        border_disabled: Some(rgba(0x0d6571ff).into()),
                        elevated_surface_background: Some(rgba(0x020c0eff).into()),
                        surface_background: Some(rgba(0x020c0eff).into()),
                        background: Some(rgba(0x031316ff).into()),
                        element_background: Some(rgba(0x089099ff).into()),
                        text: Some(rgba(0xb1c9ccff).into()),
                        tab_inactive_background: Some(rgba(0x052e32ff).into()),
                        tab_active_background: Some(rgba(0x031316ff).into()),
                        terminal_background: Some(rgba(0x020c0eff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x47686cff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xc1d4d7ff).into()),
                        terminal_ansi_black: Some(rgba(0x324a4dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xb1c9ccff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Uva".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x6d66a7ff).into()),
                        border_variant: Some(rgba(0x6d66a7ff).into()),
                        border_focused: Some(rgba(0x6d66a7ff).into()),
                        border_selected: Some(rgba(0x6d66a7ff).into()),
                        border_transparent: Some(rgba(0x6d66a7ff).into()),
                        border_disabled: Some(rgba(0x6d66a7ff).into()),
                        elevated_surface_background: Some(rgba(0x1f1d30ff).into()),
                        surface_background: Some(rgba(0x1f1d30ff).into()),
                        background: Some(rgba(0x292640ff).into()),
                        element_background: Some(rgba(0x007e99ff).into()),
                        text: Some(rgba(0xc5c2d6ff).into()),
                        tab_inactive_background: Some(rgba(0x2f2c49ff).into()),
                        tab_active_background: Some(rgba(0x292640ff).into()),
                        terminal_background: Some(rgba(0x1f1d30ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x504e65ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xc5c2d6ff).into()),
                        terminal_ansi_black: Some(rgba(0x302f3dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xb6b3ccff).into()),
                        ..Default::default()
                    },
                },
            },
            UserTheme {
                name: "Noctis Viola".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x8666a7ff).into()),
                        border_variant: Some(rgba(0x8666a7ff).into()),
                        border_focused: Some(rgba(0x8666a7ff).into()),
                        border_selected: Some(rgba(0x8666a7ff).into()),
                        border_transparent: Some(rgba(0x8666a7ff).into()),
                        border_disabled: Some(rgba(0x8666a7ff).into()),
                        elevated_surface_background: Some(rgba(0x291d35ff).into()),
                        surface_background: Some(rgba(0x291d35ff).into()),
                        background: Some(rgba(0x30243dff).into()),
                        element_background: Some(rgba(0x007e99ff).into()),
                        text: Some(rgba(0xccbfd9ff).into()),
                        tab_inactive_background: Some(rgba(0x3d2e4dff).into()),
                        tab_active_background: Some(rgba(0x30243dff).into()),
                        terminal_background: Some(rgba(0x291d35ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x594e65ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xe97749ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x5febb1ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xe69532ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x5fb5ebff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xe697b2ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0x5fdaebff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xccbfd9ff).into()),
                        terminal_ansi_black: Some(rgba(0x362f3dff).into()),
                        terminal_ansi_red: Some(rgba(0xe66432ff).into()),
                        terminal_ansi_green: Some(rgba(0x49e9a6ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xe4b781ff).into()),
                        terminal_ansi_blue: Some(rgba(0x49ace9ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xdf759aff).into()),
                        terminal_ansi_cyan: Some(rgba(0x49d5e9ff).into()),
                        terminal_ansi_white: Some(rgba(0xbfafcfff).into()),
                        ..Default::default()
                    },
                },
            },
        ],
    }
}
