
use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn one_light() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "One Light".into(),
            is_light: true,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0xc9c9caff).into(),
        border_variant: rgba(0xc9c9caff).into(),
        border_focused: rgba(0xcbcdf6ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0xdcdcddff).into(),
        surface: rgba(0xebebecff).into(),
        background: rgba(0xdcdcddff).into(),
        filled_element: rgba(0xdcdcddff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0xe2e2faff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0xe2e2faff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0x383a41ff).into(),
        text_muted: rgba(0x7e8087ff).into(),
        text_placeholder: rgba(0xd36151ff).into(),
        text_disabled: rgba(0xa1a1a3ff).into(),
        text_accent: rgba(0x5c78e2ff).into(),
        icon_muted: rgba(0x7e8087ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("string.special.symbol".into(), rgba(0xad6e26ff).into()),
                ("hint".into(), rgba(0x9294beff).into()),
                ("link_uri".into(), rgba(0x3882b7ff).into()),
                ("type".into(), rgba(0x3882b7ff).into()),
                ("string.regex".into(), rgba(0xad6e26ff).into()),
                ("constant".into(), rgba(0x669f59ff).into()),
                ("function".into(), rgba(0x5b79e3ff).into()),
                ("string.special".into(), rgba(0xad6e26ff).into()),
                ("punctuation.bracket".into(), rgba(0x4d4f52ff).into()),
                ("variable".into(), rgba(0x383a41ff).into()),
                ("punctuation".into(), rgba(0x383a41ff).into()),
                ("property".into(), rgba(0xd3604fff).into()),
                ("string".into(), rgba(0x649f57ff).into()),
                ("predictive".into(), rgba(0x9b9ec6ff).into()),
                ("attribute".into(), rgba(0x5c78e2ff).into()),
                ("number".into(), rgba(0xad6e25ff).into()),
                ("constructor".into(), rgba(0x5c78e2ff).into()),
                ("embedded".into(), rgba(0x383a41ff).into()),
                ("title".into(), rgba(0xd3604fff).into()),
                ("tag".into(), rgba(0x5c78e2ff).into()),
                ("boolean".into(), rgba(0xad6e25ff).into()),
                ("punctuation.list_marker".into(), rgba(0xd3604fff).into()),
                ("variant".into(), rgba(0x5b79e3ff).into()),
                ("emphasis".into(), rgba(0x5c78e2ff).into()),
                ("link_text".into(), rgba(0x5b79e3ff).into()),
                ("comment".into(), rgba(0xa2a3a7ff).into()),
                ("punctuation.special".into(), rgba(0xb92b46ff).into()),
                ("emphasis.strong".into(), rgba(0xad6e25ff).into()),
                ("primary".into(), rgba(0x383a41ff).into()),
                ("punctuation.delimiter".into(), rgba(0x4d4f52ff).into()),
                ("label".into(), rgba(0x5c78e2ff).into()),
                ("keyword".into(), rgba(0xa449abff).into()),
                ("string.escape".into(), rgba(0x7c7e86ff).into()),
                ("text.literal".into(), rgba(0x649f57ff).into()),
                ("variable.special".into(), rgba(0xad6e25ff).into()),
                ("comment.doc".into(), rgba(0x7c7e86ff).into()),
                ("enum".into(), rgba(0xd3604fff).into()),
                ("operator".into(), rgba(0x3882b7ff).into()),
                ("preproc".into(), rgba(0x383a41ff).into()),
            ],
        },
        status_bar: rgba(0xdcdcddff).into(),
        title_bar: rgba(0xdcdcddff).into(),
        toolbar: rgba(0xfafafaff).into(),
        tab_bar: rgba(0xebebecff).into(),
        editor: rgba(0xfafafaff).into(),
        editor_subheader: rgba(0xebebecff).into(),
        editor_active_line: rgba(0xebebecff).into(),
        terminal: rgba(0xfafafaff).into(),
        image_fallback_background: rgba(0xdcdcddff).into(),
        git_created: rgba(0x669f59ff).into(),
        git_modified: rgba(0x5c78e2ff).into(),
        git_deleted: rgba(0xd36151ff).into(),
        git_conflict: rgba(0xdec184ff).into(),
        git_ignored: rgba(0xa1a1a3ff).into(),
        git_renamed: rgba(0xdec184ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x5c78e2ff).into(),
                selection: rgba(0x5c78e23d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x669f59ff).into(),
                selection: rgba(0x669f593d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x984ea5ff).into(),
                selection: rgba(0x984ea53d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xad6e26ff).into(),
                selection: rgba(0xad6e263d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xa349abff).into(),
                selection: rgba(0xa349ab3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x3a82b7ff).into(),
                selection: rgba(0x3a82b73d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xd36151ff).into(),
                selection: rgba(0xd361513d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xdec184ff).into(),
                selection: rgba(0xdec1843d).into(),
            },
        ],
    }
}
