use gpui::rgba;

use crate::{
    default_color_scales, Appearance, GitStatusColors, PlayerColor, PlayerColors, StatusColors,
    SyntaxTheme, SystemColors, ThemeColors, ThemeFamily, ThemeStyles, ThemeVariant,
};

pub fn palenight() -> ThemeFamily {
    ThemeFamily {
        id: "3187cd2f-29da-4bde-9621-83016df3b393".into(),
        name: "Palenight".into(),
        author: "Olaolu Olawuyi (whizkydee)".into(),
        themes: vec![
            ThemeVariant {
                id: "0eaa3098-3aa2-4b8e-b1df-92d9ebd9a0b8".into(),
                name: "Palenight".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x282b3bff).into(),
                        border_variant: rgba(0x282b3bff).into(),
                        border_focused: rgba(0x282b3bff).into(),
                        border_disabled: rgba(0x282b3bff).into(),
                        border_selected: rgba(0x282b3bff).into(),
                        border_transparent: rgba(0x282b3bff).into(),
                        elevated_surface_background: rgba(0x292c3eff).into(),
                        surface_background: rgba(0x292c3eff).into(),
                        background: rgba(0x292c3eff).into(),
                        element_background: rgba(0x7d56c1cc).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xffffffff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x31364aff).into(),
                        tab_active_background: rgba(0x292c3eff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x111113ff).into(),
                        terminal_ansi_bright_black: rgba(0x676e95ff).into(),
                        terminal_ansi_bright_red: rgba(0xff5571ff).into(),
                        terminal_ansi_bright_green: rgba(0xc3e88dff).into(),
                        terminal_ansi_bright_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_bright_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_bright_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_bright_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_bright_white: rgba(0xffffffff).into(),
                        terminal_ansi_black: rgba(0x676e95ff).into(),
                        terminal_ansi_red: rgba(0xff5571ff).into(),
                        terminal_ansi_green: rgba(0xa9c77dff).into(),
                        terminal_ansi_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_white: rgba(0xffffffff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "b6a27c72-c5b1-431b-8bfe-29e33dbcb337".into(),
                name: "Palenight Operator".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x282b3bff).into(),
                        border_variant: rgba(0x282b3bff).into(),
                        border_focused: rgba(0x282b3bff).into(),
                        border_disabled: rgba(0x282b3bff).into(),
                        border_selected: rgba(0x282b3bff).into(),
                        border_transparent: rgba(0x282b3bff).into(),
                        elevated_surface_background: rgba(0x292c3eff).into(),
                        surface_background: rgba(0x292c3eff).into(),
                        background: rgba(0x292c3eff).into(),
                        element_background: rgba(0x7d56c1cc).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xffffffff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x31364aff).into(),
                        tab_active_background: rgba(0x292c3eff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x111113ff).into(),
                        terminal_ansi_bright_black: rgba(0x676e95ff).into(),
                        terminal_ansi_bright_red: rgba(0xff5571ff).into(),
                        terminal_ansi_bright_green: rgba(0xc3e88dff).into(),
                        terminal_ansi_bright_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_bright_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_bright_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_bright_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_bright_white: rgba(0xffffffff).into(),
                        terminal_ansi_black: rgba(0x676e95ff).into(),
                        terminal_ansi_red: rgba(0xff5571ff).into(),
                        terminal_ansi_green: rgba(0xa9c77dff).into(),
                        terminal_ansi_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_white: rgba(0xffffffff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
            ThemeVariant {
                id: "4015bf85-061c-45ff-81ba-a31f017aac83".into(),
                name: "Palenight (Mild Contrast)".into(),
                appearance: Appearance::Dark,
                styles: ThemeStyles {
                    system: SystemColors {
                        transparent: rgba(0x00000000).into(),
                        mac_os_traffic_light_red: rgba(0xec6b5fff).into(),
                        mac_os_traffic_light_yellow: rgba(0xf3bf4dff).into(),
                        mac_os_traffic_light_green: rgba(0x61c454ff).into(),
                    },
                    colors: ThemeColors {
                        border: rgba(0x2c2f40ff).into(),
                        border_variant: rgba(0x2c2f40ff).into(),
                        border_focused: rgba(0x2c2f40ff).into(),
                        border_disabled: rgba(0x2c2f40ff).into(),
                        border_selected: rgba(0x2c2f40ff).into(),
                        border_transparent: rgba(0x2c2f40ff).into(),
                        elevated_surface_background: rgba(0x25283aff).into(),
                        surface_background: rgba(0x25283aff).into(),
                        background: rgba(0x292c3eff).into(),
                        element_background: rgba(0x7d56c1cc).into(),
                        element_hover: rgba(0x272a2dff).into(),
                        element_active: rgba(0x2e3135ff).into(),
                        element_selected: rgba(0x2e3135ff).into(),
                        element_disabled: rgba(0xddeaf814).into(),
                        element_placeholder: rgba(0xb0b4baff).into(),
                        element_drop_target: rgba(0x1166fb18).into(),
                        ghost_element_background: rgba(0x00000000).into(),
                        ghost_element_hover: rgba(0x272a2dff).into(),
                        ghost_element_active: rgba(0x2e3135ff).into(),
                        ghost_element_selected: rgba(0x2e3135ff).into(),
                        ghost_element_disabled: rgba(0xddeaf814).into(),
                        text: rgba(0xffffffff).into(),
                        text_muted: rgba(0xb0b4baff).into(),
                        text_placeholder: rgba(0x767a83ff).into(),
                        text_disabled: rgba(0x696e77ff).into(),
                        text_accent: rgba(0x6fb8ffff).into(),
                        icon: rgba(0xb0b4baff).into(),
                        icon_muted: rgba(0x767a83ff).into(),
                        icon_disabled: rgba(0x696e77ff).into(),
                        icon_placeholder: rgba(0x767a83ff).into(),
                        icon_accent: rgba(0x6fb8ffff).into(),
                        status_bar_background: rgba(0x18191bff).into(),
                        title_bar_background: rgba(0x18191bff).into(),
                        toolbar_background: rgba(0x111113ff).into(),
                        tab_bar_background: rgba(0x18191bff).into(),
                        tab_inactive_background: rgba(0x31364aff).into(),
                        tab_active_background: rgba(0x25283aff).into(),
                        editor_background: rgba(0x111113ff).into(),
                        editor_subheader_background: rgba(0x18191bff).into(),
                        editor_active_line: rgba(0xddeaf814).into(),
                        terminal_background: rgba(0x111113ff).into(),
                        terminal_ansi_bright_black: rgba(0x676e95ff).into(),
                        terminal_ansi_bright_red: rgba(0xff5571ff).into(),
                        terminal_ansi_bright_green: rgba(0xc3e88dff).into(),
                        terminal_ansi_bright_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_bright_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_bright_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_bright_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_bright_white: rgba(0xffffffff).into(),
                        terminal_ansi_black: rgba(0x676e95ff).into(),
                        terminal_ansi_red: rgba(0xff5571ff).into(),
                        terminal_ansi_green: rgba(0xa9c77dff).into(),
                        terminal_ansi_yellow: rgba(0xffcb6bff).into(),
                        terminal_ansi_blue: rgba(0x82aaffff).into(),
                        terminal_ansi_magenta: rgba(0xc792eaff).into(),
                        terminal_ansi_cyan: rgba(0x89ddffff).into(),
                        terminal_ansi_white: rgba(0xffffffff).into(),
                    },
                    status: StatusColors {
                        conflict: rgba(0xff9592ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        error: rgba(0xff9592ff).into(),
                        hidden: rgba(0xb0b4baff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        info: rgba(0x6fb8ffff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                        success: rgba(0x70cf82ff).into(),
                        warning: rgba(0xf5e147ff).into(),
                    },
                    git: GitStatusColors {
                        conflict: rgba(0xffa057ff).into(),
                        created: rgba(0x70cf82ff).into(),
                        deleted: rgba(0xff9592ff).into(),
                        ignored: rgba(0xb0b4baff).into(),
                        modified: rgba(0xf5e147ff).into(),
                        renamed: rgba(0x6fb8ffff).into(),
                    },
                    player: PlayerColors(vec![
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                        PlayerColor {
                            cursor: rgba(0x00000000).into(),
                            background: rgba(0x00000000).into(),
                            selection: rgba(0x00000000).into(),
                        },
                    ]),
                    syntax: SyntaxTheme {
                        highlights: vec![
                            ("attribute".into(), rgba(0x4ccce6ff).into()),
                            ("boolean".into(), rgba(0xff977dff).into()),
                            ("comment".into(), rgba(0xb0b4baff).into()),
                            ("comment.doc".into(), rgba(0xe0dffeff).into()),
                            ("constant".into(), rgba(0x8c323aff).into()),
                            ("constructor".into(), rgba(0x8c323aff).into()),
                            ("embedded".into(), rgba(0x8c323aff).into()),
                            ("emphasis".into(), rgba(0x8c323aff).into()),
                            ("emphasis.strong".into(), rgba(0x8c323aff).into()),
                            ("enum".into(), rgba(0x8c323aff).into()),
                            ("function".into(), rgba(0x8c323aff).into()),
                            ("hint".into(), rgba(0x8c323aff).into()),
                            ("keyword".into(), rgba(0xffa057ff).into()),
                            ("label".into(), rgba(0x8c323aff).into()),
                            ("link_text".into(), rgba(0x8c323aff).into()),
                            ("link_uri".into(), rgba(0x8c323aff).into()),
                            ("number".into(), rgba(0x8c323aff).into()),
                            ("operator".into(), rgba(0x8c323aff).into()),
                            ("predictive".into(), rgba(0x8c323aff).into()),
                            ("preproc".into(), rgba(0x8c323aff).into()),
                            ("primary".into(), rgba(0x8c323aff).into()),
                            ("property".into(), rgba(0x8c323aff).into()),
                            ("punctuation".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.bracket".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.delimiter".into(), rgba(0xb0b4baff).into()),
                            ("punctuation.list_marker".into(), rgba(0x6fb8ffff).into()),
                            ("punctuation.special".into(), rgba(0x8c323aff).into()),
                            ("string".into(), rgba(0x1ed8a3ff).into()),
                            ("string.escape".into(), rgba(0x8c323aff).into()),
                            ("string.regex".into(), rgba(0xff977dff).into()),
                            ("string.special".into(), rgba(0x8c323aff).into()),
                            ("string.special.symbol".into(), rgba(0x8c323aff).into()),
                            ("tag".into(), rgba(0x8c323aff).into()),
                            ("text.literal".into(), rgba(0x8c323aff).into()),
                            ("title".into(), rgba(0x8c323aff).into()),
                            ("type".into(), rgba(0x8c323aff).into()),
                            ("variable".into(), rgba(0x8c323aff).into()),
                            ("variable.special".into(), rgba(0x8c323aff).into()),
                            ("variant".into(), rgba(0x8c323aff).into()),
                        ],
                    },
                },
            },
        ],
        scales: default_color_scales(),
    }
}
