// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

use crate::{
    Appearance, StatusColorsRefinement, ThemeColorsRefinement, UserHighlightStyle, UserSyntaxTheme,
    UserTheme, UserThemeFamily, UserThemeStylesRefinement,
};

pub fn rose_pine() -> UserThemeFamily {
    UserThemeFamily {
        name: "Rose Pine".into(),
        author: "Rosé Pine".into(),
        themes: vec![
            UserTheme {
                name: "Rose Pine".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x000000ff).into()),
                        border_variant: Some(rgba(0x000000ff).into()),
                        border_focused: Some(rgba(0x6e6a8633).into()),
                        border_selected: Some(rgba(0x000000ff).into()),
                        border_transparent: Some(rgba(0x000000ff).into()),
                        border_disabled: Some(rgba(0x000000ff).into()),
                        elevated_surface_background: Some(rgba(0x1f1d2eff).into()),
                        surface_background: Some(rgba(0x1f1d2eff).into()),
                        background: Some(rgba(0x191724ff).into()),
                        element_background: Some(rgba(0xebbcbaff).into()),
                        element_hover: Some(rgba(0x6e6a861a).into()),
                        element_selected: Some(rgba(0x6e6a8633).into()),
                        drop_target_background: Some(rgba(0x1f1d2eff).into()),
                        ghost_element_hover: Some(rgba(0x6e6a861a).into()),
                        text: Some(rgba(0xe0def4ff).into()),
                        tab_inactive_background: Some(rgba(0x000000ff).into()),
                        tab_active_background: Some(rgba(0x6e6a861a).into()),
                        editor_background: Some(rgba(0x191724ff).into()),
                        editor_gutter_background: Some(rgba(0x191724ff).into()),
                        editor_line_number: Some(rgba(0x908caaff).into()),
                        editor_active_line_number: Some(rgba(0xe0def4ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x908caaff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xeb6f92ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x30738fff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xf5c177ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x9ccfd8ff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xc4a7e7ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0xebbcbaff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xe0def4ff).into()),
                        terminal_ansi_black: Some(rgba(0x26233aff).into()),
                        terminal_ansi_red: Some(rgba(0xeb6f92ff).into()),
                        terminal_ansi_green: Some(rgba(0x30738fff).into()),
                        terminal_ansi_yellow: Some(rgba(0xf5c177ff).into()),
                        terminal_ansi_blue: Some(rgba(0x9ccfd8ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xc4a7e7ff).into()),
                        terminal_ansi_cyan: Some(rgba(0xebbcbaff).into()),
                        terminal_ansi_white: Some(rgba(0xe0def4ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        deleted: Some(rgba(0xeb6f92ff).into()),
                        error: Some(rgba(0xeb6f92ff).into()),
                        hidden: Some(rgba(0x908caaff).into()),
                        warning: Some(rgba(0xf5c177ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x6e6a86ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "something".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xebbcbaff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x6e6a86ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Rose Moon".into(),
                appearance: Appearance::Dark,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x000000ff).into()),
                        border_variant: Some(rgba(0x000000ff).into()),
                        border_focused: Some(rgba(0x817c9c26).into()),
                        border_selected: Some(rgba(0x000000ff).into()),
                        border_transparent: Some(rgba(0x000000ff).into()),
                        border_disabled: Some(rgba(0x000000ff).into()),
                        elevated_surface_background: Some(rgba(0x2a273eff).into()),
                        surface_background: Some(rgba(0x2a273eff).into()),
                        background: Some(rgba(0x232136ff).into()),
                        element_background: Some(rgba(0xea9a97ff).into()),
                        element_hover: Some(rgba(0x817c9c14).into()),
                        element_selected: Some(rgba(0x817c9c26).into()),
                        drop_target_background: Some(rgba(0x2a273eff).into()),
                        ghost_element_hover: Some(rgba(0x817c9c14).into()),
                        text: Some(rgba(0xe0def4ff).into()),
                        tab_inactive_background: Some(rgba(0x000000ff).into()),
                        tab_active_background: Some(rgba(0x817c9c14).into()),
                        editor_background: Some(rgba(0x232136ff).into()),
                        editor_gutter_background: Some(rgba(0x232136ff).into()),
                        editor_line_number: Some(rgba(0x908caaff).into()),
                        editor_active_line_number: Some(rgba(0xe0def4ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x908caaff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xeb6f92ff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x3d8fb0ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xf5c177ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x9ccfd8ff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0xc4a7e7ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0xea9a97ff).into()),
                        terminal_ansi_bright_white: Some(rgba(0xe0def4ff).into()),
                        terminal_ansi_black: Some(rgba(0x393552ff).into()),
                        terminal_ansi_red: Some(rgba(0xeb6f92ff).into()),
                        terminal_ansi_green: Some(rgba(0x3d8fb0ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xf5c177ff).into()),
                        terminal_ansi_blue: Some(rgba(0x9ccfd8ff).into()),
                        terminal_ansi_magenta: Some(rgba(0xc4a7e7ff).into()),
                        terminal_ansi_cyan: Some(rgba(0xea9a97ff).into()),
                        terminal_ansi_white: Some(rgba(0xe0def4ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        deleted: Some(rgba(0xeb6f92ff).into()),
                        error: Some(rgba(0xeb6f92ff).into()),
                        hidden: Some(rgba(0x908caaff).into()),
                        warning: Some(rgba(0xf5c177ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x6e6a86ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "something".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xea9a97ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x6e6a86ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
            UserTheme {
                name: "Rose Pine Dawn".into(),
                appearance: Appearance::Light,
                styles: UserThemeStylesRefinement {
                    colors: ThemeColorsRefinement {
                        border: Some(rgba(0x000000ff).into()),
                        border_variant: Some(rgba(0x000000ff).into()),
                        border_focused: Some(rgba(0x6e6a8614).into()),
                        border_selected: Some(rgba(0x000000ff).into()),
                        border_transparent: Some(rgba(0x000000ff).into()),
                        border_disabled: Some(rgba(0x000000ff).into()),
                        elevated_surface_background: Some(rgba(0xfffaf3ff).into()),
                        surface_background: Some(rgba(0xfffaf3ff).into()),
                        background: Some(rgba(0xfaf4edff).into()),
                        element_background: Some(rgba(0xd7827dff).into()),
                        element_hover: Some(rgba(0x6e6a860d).into()),
                        element_selected: Some(rgba(0x6e6a8614).into()),
                        drop_target_background: Some(rgba(0xfffaf3ff).into()),
                        ghost_element_hover: Some(rgba(0x6e6a860d).into()),
                        text: Some(rgba(0x575279ff).into()),
                        tab_inactive_background: Some(rgba(0x000000ff).into()),
                        tab_active_background: Some(rgba(0x6e6a860d).into()),
                        editor_background: Some(rgba(0xfaf4edff).into()),
                        editor_gutter_background: Some(rgba(0xfaf4edff).into()),
                        editor_line_number: Some(rgba(0x797593ff).into()),
                        editor_active_line_number: Some(rgba(0x575279ff).into()),
                        terminal_ansi_bright_black: Some(rgba(0x797593ff).into()),
                        terminal_ansi_bright_red: Some(rgba(0xb3627aff).into()),
                        terminal_ansi_bright_green: Some(rgba(0x276983ff).into()),
                        terminal_ansi_bright_yellow: Some(rgba(0xea9d34ff).into()),
                        terminal_ansi_bright_blue: Some(rgba(0x55949fff).into()),
                        terminal_ansi_bright_magenta: Some(rgba(0x9079a9ff).into()),
                        terminal_ansi_bright_cyan: Some(rgba(0xd7827dff).into()),
                        terminal_ansi_bright_white: Some(rgba(0x575279ff).into()),
                        terminal_ansi_black: Some(rgba(0xf2e9e1ff).into()),
                        terminal_ansi_red: Some(rgba(0xb3627aff).into()),
                        terminal_ansi_green: Some(rgba(0x276983ff).into()),
                        terminal_ansi_yellow: Some(rgba(0xea9d34ff).into()),
                        terminal_ansi_blue: Some(rgba(0x55949fff).into()),
                        terminal_ansi_magenta: Some(rgba(0x9079a9ff).into()),
                        terminal_ansi_cyan: Some(rgba(0xd7827dff).into()),
                        terminal_ansi_white: Some(rgba(0x575279ff).into()),
                        ..Default::default()
                    },
                    status: StatusColorsRefinement {
                        deleted: Some(rgba(0xb3627aff).into()),
                        error: Some(rgba(0xb3627aff).into()),
                        hidden: Some(rgba(0x797593ff).into()),
                        warning: Some(rgba(0xea9d34ff).into()),
                        ..Default::default()
                    },
                    syntax: Some(UserSyntaxTheme {
                        highlights: vec![
                            (
                                "comment".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9893a5ff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "something".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0xd7827dff).into()),
                                    font_style: Some(UserFontStyle::Italic),
                                    ..Default::default()
                                },
                            ),
                            (
                                "punctuation".into(),
                                UserHighlightStyle {
                                    color: Some(rgba(0x9893a5ff).into()),
                                    ..Default::default()
                                },
                            ),
                        ],
                    }),
                },
            },
        ],
    }
}
