use gpui2::rgba;

use crate::{PlayerTheme, SyntaxTheme, Theme, ThemeMetadata};

pub fn summercamp() -> Theme {
    Theme {
        metadata: ThemeMetadata {
            name: "Summercamp".into(),
            is_light: false,
        },
        transparent: rgba(0x00000000).into(),
        mac_os_traffic_light_red: rgba(0xec695eff).into(),
        mac_os_traffic_light_yellow: rgba(0xf4bf4eff).into(),
        mac_os_traffic_light_green: rgba(0x61c553ff).into(),
        border: rgba(0x302c21ff).into(),
        border_variant: rgba(0x302c21ff).into(),
        border_focused: rgba(0x193760ff).into(),
        border_transparent: rgba(0x00000000).into(),
        elevated_surface: rgba(0x2a261cff).into(),
        surface: rgba(0x231f16ff).into(),
        background: rgba(0x2a261cff).into(),
        filled_element: rgba(0x2a261cff).into(),
        filled_element_hover: rgba(0xffffff1e).into(),
        filled_element_active: rgba(0xffffff28).into(),
        filled_element_selected: rgba(0x0e2242ff).into(),
        filled_element_disabled: rgba(0x00000000).into(),
        ghost_element: rgba(0x00000000).into(),
        ghost_element_hover: rgba(0xffffff14).into(),
        ghost_element_active: rgba(0xffffff1e).into(),
        ghost_element_selected: rgba(0x0e2242ff).into(),
        ghost_element_disabled: rgba(0x00000000).into(),
        text: rgba(0xf8f5deff).into(),
        text_muted: rgba(0x736e55ff).into(),
        text_placeholder: rgba(0xe35041ff).into(),
        text_disabled: rgba(0x4c4735ff).into(),
        text_accent: rgba(0x499befff).into(),
        icon_muted: rgba(0x736e55ff).into(),
        syntax: SyntaxTheme {
            highlights: vec![
                ("predictive".into(), rgba(0x78434aff).into()),
                ("title".into(), rgba(0xf8f5deff).into()),
                ("primary".into(), rgba(0xf8f5deff).into()),
                ("punctuation.special".into(), rgba(0xbfbb9bff).into()),
                ("constant".into(), rgba(0x5dea5aff).into()),
                ("string.regex".into(), rgba(0xfaa11cff).into()),
                ("tag".into(), rgba(0x499befff).into()),
                ("preproc".into(), rgba(0xf8f5deff).into()),
                ("comment".into(), rgba(0x777159ff).into()),
                ("punctuation.bracket".into(), rgba(0xbfbb9bff).into()),
                ("constructor".into(), rgba(0x499befff).into()),
                ("type".into(), rgba(0x5aeabbff).into()),
                ("variable".into(), rgba(0xf8f5deff).into()),
                ("operator".into(), rgba(0xfaa11cff).into()),
                ("boolean".into(), rgba(0x5dea5aff).into()),
                ("attribute".into(), rgba(0x499befff).into()),
                ("link_text".into(), rgba(0xfaa11cff).into()),
                ("string.escape".into(), rgba(0x777159ff).into()),
                ("string.special".into(), rgba(0xfaa11cff).into()),
                ("string.special.symbol".into(), rgba(0xfaa11cff).into()),
                ("hint".into(), rgba(0x246e61ff).into()),
                ("link_uri".into(), rgba(0x5dea5aff).into()),
                ("comment.doc".into(), rgba(0x777159ff).into()),
                ("emphasis".into(), rgba(0x499befff).into()),
                ("punctuation".into(), rgba(0xbfbb9bff).into()),
                ("text.literal".into(), rgba(0xfaa11cff).into()),
                ("number".into(), rgba(0x5dea5aff).into()),
                ("punctuation.delimiter".into(), rgba(0xbfbb9bff).into()),
                ("label".into(), rgba(0x499befff).into()),
                ("function".into(), rgba(0xf1fe28ff).into()),
                ("property".into(), rgba(0x499befff).into()),
                ("keyword".into(), rgba(0x499befff).into()),
                ("embedded".into(), rgba(0xf8f5deff).into()),
                ("string".into(), rgba(0xfaa11cff).into()),
                ("punctuation.list_marker".into(), rgba(0xbfbb9bff).into()),
                ("enum".into(), rgba(0xfaa11cff).into()),
                ("emphasis.strong".into(), rgba(0x499befff).into()),
                ("variant".into(), rgba(0x499befff).into()),
            ],
        },
        status_bar: rgba(0x2a261cff).into(),
        title_bar: rgba(0x2a261cff).into(),
        toolbar: rgba(0x1b1810ff).into(),
        tab_bar: rgba(0x231f16ff).into(),
        editor: rgba(0x1b1810ff).into(),
        editor_subheader: rgba(0x231f16ff).into(),
        editor_active_line: rgba(0x231f16ff).into(),
        terminal: rgba(0x1b1810ff).into(),
        image_fallback_background: rgba(0x2a261cff).into(),
        git_created: rgba(0x5dea5aff).into(),
        git_modified: rgba(0x499befff).into(),
        git_deleted: rgba(0xe35041ff).into(),
        git_conflict: rgba(0xf1fe28ff).into(),
        git_ignored: rgba(0x4c4735ff).into(),
        git_renamed: rgba(0xf1fe28ff).into(),
        players: [
            PlayerTheme {
                cursor: rgba(0x499befff).into(),
                selection: rgba(0x499bef3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5dea5aff).into(),
                selection: rgba(0x5dea5a3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf59be6ff).into(),
                selection: rgba(0xf59be63d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfaa11cff).into(),
                selection: rgba(0xfaa11c3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xfe8080ff).into(),
                selection: rgba(0xfe80803d).into(),
            },
            PlayerTheme {
                cursor: rgba(0x5aeabbff).into(),
                selection: rgba(0x5aeabb3d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xe35041ff).into(),
                selection: rgba(0xe350413d).into(),
            },
            PlayerTheme {
                cursor: rgba(0xf1fe28ff).into(),
                selection: rgba(0xf1fe283d).into(),
            },
        ],
    }
}
