//! Generates SKILL.md files from aggregated curator patterns.
//! Writes to `~/.agents/skills/<slug>/SKILL.md`.

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};

use crate::curator::{CuratorPattern, Observation, classifier::PatternCategory, classifier::PatternClassifier};

pub struct SkillWriter;

impl SkillWriter {
    /// Generate and persist a SKILL.md file from a pattern observation.
    /// Returns the absolute path to the created file.
    pub fn write_skill(&self, pattern: &CuratorPattern, obs: &Observation) -> Result<String> {
        let slug = &pattern.slug;
        let skills_dir = self.ensure_skills_dir()?;
        let skill_dir = skills_dir.join(slug);
        std::fs::create_dir_all(&skill_dir)
            .with_context(|| format!("creating skill dir {skill_dir:?}"))?;

        let skill_path = skill_dir.join("SKILL.md");
        let body = self.render_skill_md(pattern, obs);
        std::fs::write(&skill_path, body)
            .with_context(|| format!("writing SKILL.md to {skill_path:?}"))?;

        Ok(skill_path.to_string_lossy().to_string())
    }

    fn ensure_skills_dir(&self) -> Result<PathBuf> {
        let home = std::env::var("HOME")
            .map_err(|_| anyhow::anyhow!("$HOME not set"))?;
        let dir = Path::new(&home).join(".agents").join("skills");
        std::fs::create_dir_all(&dir)
            .with_context(|| format!("creating skills dir {dir:?}"))?;
        Ok(dir)
    }

    fn render_skill_md(&self, pattern: &CuratorPattern, obs: &Observation) -> String {
        let classifier = PatternClassifier;
        let category = classifier.classify(obs);
        let description = self.describe(obs, &category);
        let steps = self.generate_steps(obs, &category);

        format!(
            r#"---
name: {name}
description: >-
  {description}
model_invocation: true
generated_by: curator
created_at: {date}
---

{steps}

---

*This skill was auto-generated by the curator after observing this pattern {n} time(s).*
"#,
            name = pattern.title,
            description = description,
            date = chrono_now(),
            steps = steps,
            n = pattern.occurrences,
        )
    }

    fn describe(&self, obs: &Observation, category: &PatternCategory) -> String {
        match category {
            PatternCategory::Fix => {
                if let Some(ref err) = obs.error_fragment {
                    format!("Fix for: {}", err)
                } else {
                    "Auto-detected fix pattern.".to_string()
                }
            }
            PatternCategory::Workflow => {
                let cmds = if obs.command_signature.is_empty() {
                    "commands".to_string()
                } else {
                    obs.command_signature.replace(',', ", ")
                };
                format!("Workflow involving: {}", cmds)
            }
            PatternCategory::Convention => {
                "Project convention detected by curator.".to_string()
            }
        }
    }

    fn generate_steps(&self, obs: &Observation, category: &PatternCategory) -> String {
        match category {
            PatternCategory::Fix => {
                let err_hint = obs
                    .error_fragment
                    .as_deref()
                    .unwrap_or("an error");

                let mut steps = String::from("When you encounter this error:\n\n");
                steps.push_str(&format!("1. Read the full error: `{}`\n", err_hint));
                steps.push_str("2. Identify the root cause (type mismatch, missing import, etc.)\n");
                steps.push_str("3. Apply the fix\n");
                if !obs.command_signature.is_empty() {
                    steps.push_str(&format!("4. Re-run: `{}`\n", obs.command_signature.replace(',', "` then `")));
                    steps.push_str("5. Repeat until clean\n");
                }
                steps
            }
            PatternCategory::Workflow => {
                let mut steps = String::from("Follow this workflow:\n\n");
                if !obs.command_signature.is_empty() {
                    for (i, cmd) in obs.command_signature.split(',').enumerate() {
                        steps.push_str(&format!("{}. Run `{}`\n", i + 1, cmd.trim()));
                    }
                }
                if !obs.edit_signature.is_empty() {
                    steps.push_str(&format!(
                        "{}. Edit `.{}` files as needed\n",
                        obs.command_signature.split(',').count() + 1,
                        obs.edit_signature.replace(',', "`, `."),
                    ));
                }
                steps
            }
            PatternCategory::Convention => {
                "Use the tools and patterns established in this project.\n\n1. Follow the existing code style\n2. Use the project's build system\n3. Run tests before committing\n".to_string()
            }
        }
    }
}

fn chrono_now() -> String {
    // Simple date formatting without pulling in chrono (already in deps)
    use std::time::{SystemTime, UNIX_EPOCH};
    let dur = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
    let secs = dur.as_secs();

    // Days since epoch
    let days = secs / 86400;
    let time_secs = secs % 86400;
    let hours = time_secs / 3600;
    let minutes = (time_secs % 3600) / 60;
    let seconds = time_secs % 60;

    // Year/month/day from days since epoch (civil date)
    let (year, month, day) = civil_from_days(days as i64);
    format!("{year:04}-{month:02}-{day:02}T{hours:02}:{minutes:02}:{seconds:02}Z")
}

/// Convert days since 1970-01-01 to (year, month, day).
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097; // day of era
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m as u32, d as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_civil_from_days() {
        // Known date: 2026-01-01
        let epoch_2026 = days_since_epoch(2026, 1, 1);
        let (y, m, d) = civil_from_days(epoch_2026);
        assert_eq!(y, 2026);
        assert_eq!(m, 1);
        assert_eq!(d, 1);
    }

    fn days_since_epoch(y: i64, m: u32, d: u32) -> i64 {
        let ym = if m <= 2 { y - 1 } else { y };
        let mp = if m <= 2 { m + 9 } else { m - 3 } as i64;
        let era = if ym >= 0 { ym } else { ym - 399 } / 400;
        let yoe = ym - era * 400;
        let doe = yoe * 365 + yoe / 4 - yoe / 100 + (mp * 153 + 2) / 5 + d as i64 - 1;
        let z = doe + era * 146097;
        z - 719468
    }

    #[test]
    fn test_render_skill_md() {
        let pattern = CuratorPattern {
            slug: "run-cargo-test".into(),
            title: "run-cargo-test".into(),
            occurrences: 3,
            last_observation: crate::curator::Observation {
                command_signature: "cargo test".into(),
                edit_signature: "rs".into(),
                tool_signature: "terminal,edit_file".into(),
                error_fragment: None,
                observed_at: 0,
            },
            skill_generated: false,
            skill_path: None,
        };
        let obs = crate::curator::Observation {
            command_signature: "cargo test".into(),
            edit_signature: "rs".into(),
            tool_signature: "terminal,edit_file".into(),
            error_fragment: None,
            observed_at: 0,
        };

        let writer = SkillWriter;
        let md = writer.render_skill_md(&pattern, &obs);

        assert!(md.contains("run-cargo-test"));
        assert!(md.contains("generated_by: curator"));
        assert!(md.contains("3 time(s)"));
        assert!(md.contains("```"));
    }
}
