name: Bump collab-staging Tag

on:
  schedule:
    # Fire every day at 16:00 UTC (At the start of the US workday)
    - cron: "0 16 * * *"

jobs:
  update-collab-staging-tag:
    if: github.repository_owner == 'zed-industries'
    runs-on: namespace-profile-2x4-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Update collab-staging tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f collab-staging
          git push origin collab-staging --force
