name: release-linux

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: ./script/linux

      - name: Build Zed bundle
        run: ./script/bundle-linux

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            target/release/zed-linux-x86_64.tar.gz \
            --target "${{ github.sha }}" \
            --generate-notes
