package zed:extension;

world extension {
    record github-release {
        version: string,
        assets: list<github-release-asset>,
    }

    record github-release-asset {
        name: string,
        download-url: string,
    }

    record github-release-options {
        require-assets: bool,
        pre-release: bool,
    }

    import npm-package-latest-version: func(package-name: string) -> result<string, string>;
    import latest-github-release: func(repo: string, options: github-release-options) -> result<github-release, string>;

    record command {
        command: string,
        args: list<string>,
        env: list<tuple<string, string>>,
    }

    resource worktree {
        read-text-file: func(path: string) -> result<string, string>;
    }

    export get-language-server-command: func(worktree: borrow<worktree>) -> result<command, string>;
}
