package zed:language-server-extension;

world language-server-extension {
    record command {
        command: string,
        args: list<string>,
        env: list<tuple<string, string>>,
    }

    record github-release {
        version: string,
        assets: list<github-release-asset>,
    }

    record github-release-asset {
        name: string,
        download-url: string,
    }

    record github-release-options {
        require-assets: bool,
        pre-release: bool,
    }

    import npm-package-latest-version: func(package-name: string) -> result<string, string>;
    import latest-github-release: func(repo: string, options: github-release-options) -> result<github-release, string>;

    export get-language-server-command: func() -> result<command, string>;
}
